<section>
    
    <div class="row">
        <div class="col-12 col-md-6">
            
            <div class="card mb-2">
                <div class="card-body">
                    <!-- Social shares button -->
                    <a class="activator waves-effect waves-light mr-4"><i class="fas fa-share-alt"></i></a>
                    <!-- Title -->
                    <h4 class="card-title">Images</h4>
                    <hr>
                    <!-- Text -->
                    <div class="row">
                        <!-- Company Cover Image -->
                        <div class="col-12">
                            <div class="form-element" style="">
                                <label for="company_cover_image">Cover Image:</label>
                                <input id="company_cover_image" name="company_cover_image" type="file" class="dropify" data-height="200"/>
                                <div id="company_cover_image-error" class="error w-100 text-center" style="">&nbsp;</div>
                            </div>
                        </div>
                        <!-- /Company Cover Image -->
                        
                        <div class="col-12 col-md-6 col-lg-8">
                        
                        </div>
                    </div>
                </div>
            </div>
        
        </div>
        
        <div class="col-12 col-md-6">
            
            <!-- Provider Keywords -->
            <div id="provider_keyword" class="card mb-2 keyword">
                <div class="card-body p-0">
                    <input class="user-release-input form-control form-control-lg" type="text" placeholder="type something here...">
                    <div class="container my-2 chips_container">
                    
                    </div>
                    <div class="text-right w-100">
                        <button type="button" class="btn btn-primary btn-round btn-sm waves-effect waves-light">submit</button>
                    </div>
                </div>
            </div>
            <!-- /Provider Keywords -->
            
            <!-- Provider Short Description -->
            <div class="card mb-2">
                <div class="card-body">
                    
                    <!-- Title -->
                    <h4 class="card-title">Short Description</h4>
                    <hr>
                    <!-- Text -->
                    
                    <div class="row">
                        <div class="col-12">
                            <div class="form-element" style="">
                                <label for="provider_description_short" style="display:none">&nbsp;</label>
                                <textarea id="provider_description_short" name="provider_description_short" class="md-textarea form-control" rows="4"></textarea>
                                <div id="provider_description_short-error" class="error w-100 text-center" style="">&nbsp;</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Provider Short Description -->
        
        </div>
    
    </div>
    
    <div class="row">
        
        <div class="col-12 col-lg-6 mb-1">
            
            <!-- Detailed Provider Description -->
            <div class="card mb-2">
                <div class="card-body">
                    <!-- Social shares button -->
                    <a id="button_provider_description_long_toggle" class="activator but_toggle waves-effect waves-light mr-4" data-texted="provider_description_long">
                        <i class="fas fa-sliders-h"></i>
                    </a>
                    <!-- Title -->
                    <h4 class="card-title">Detailed Description</h4>
                    <hr>
                    <!-- Text -->
                    
                    <div class="row">
                        <div class="col-12">
                            <div class="form-element" style="">
                                <label for="provider_description_long" style="display:none">Cover Image:</label>
                                <textarea id="provider_description_long" name="provider_description_long" class="md-textarea tmceEl form-control" rows="4"></textarea>
                                <div id="provider_description_long-error" class="error w-100 text-center" style="">&nbsp;</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Detailed Provider Description -->
        
        </div>

    </div>

</section>
<script>
    /*
    $.fn.BuildKeyword = function (settings) {
        const el = $(this)
        const _keyword_input = el.find("input.user-release-input")
        const _keyword_button = el.find("button.keyword_button")
        const _keyword_list = el.find("div.keyword_list")
        
        if (!_keyword_input || !_keyword_button || !_keyword_list) {
            return
        }
        
        if (!settings) {
            settings = ""
        }
        
        let keywords = settings.split(",").map(function (value) {
            return value.trim()
        })
        
        $(_keyword_button)
          .on("click", function () {
              let keyword = (_keyword_input.val() !== "") ? _keyword_input.val() : null
              if (keyword) {
                  
                  if (!keywords.indexOf(keyword) !== -1) {
                      addKeyWord(keyword)
                  }
                  
              }
          })
        
        const addKeyWord = function (key) {
            buildChip(key)
        }
        
        const buildChip = function (data) {
            
            let removeIcon = $("<i>")
              .addClass("close fas fa-times")
            
            let chipEl = $("<div>")
              .addClass("chip")
              .data("key", data)
              .text(data)
            chipEl.append(removeIcon)
            $(_keyword_list).append(chipEl)
        }
        
        const init = function (keywords) {
            $.each(keywords, function (k, chip) {
                buildChip(chip)
            })
        }
        
        init(keywords)
    }
    
    const _provider_keyword = document.getElementById("provider_keyword")
    
    const init = function (settings) {
        
    }
    
    $(document).ready(function () {
        let keywords = "key1, key2, key3"
        $(_provider_keyword).BuildKeyword(keywords)
    })
//*/
</script>
