<section>
	<form id="companyImageManager" novalidate>
		
		<div class="row">
			
			<!-- Image Input -->
			<div class="col-12 col-md-6">
				
				<div class="card mb-2">
					<div class="card-body">
						<!-- Actions -->
						<a id="image_manager_cancel_upload" class="activator waves-effect waves-light mr-4">
							<i class="fas fa-times"></i>
						</a>
						<!-- Title -->
						<h4 class="card-title">Images</h4>
						<h6 class="card-subtitle mb-2 text-muted">Panel subtitle</h6>
						<hr>
						
						<div class="row">
							
							<!-- Company Image -->
							<div class="col-12">
								<div class="form-element">
									<input id="image_manager_upload" name="image_manager_upload" type="file" class="" data-height="200"/>
									<div id="image_manager_upload-error" class="error w-100 text-center">&nbsp;</div>
								</div>
							</div>
							<!-- /Company Image -->
						
						</div>
						
						<div id="image_manager_form_data" style="display:none">
							<div class="row">
								<div class="col-12 col-md-6">
									<div class="form-element">
										<label for="image_manager_id">Image Id: </label>
										<input type="text" id="image_manager_id" name="image_manager_id" class="form-control" value="" readonly/>
										<div id="image_manager_id-error" class="error w-100 text-center">&nbsp;</div>
									</div>
								</div>
								<div class="col-12 col-md-6 d-flex align-self-center justify-content-end pb-2">
									<div class="custom-control custom-switch">
										<input id="image_manager_is_cover" name="image_manager_is_cover" type="checkbox" value="1" class="custom-control-input">
										<label for="image_manager_is_cover" class="custom-control-label p-0">Is Cover</label>
									</div>
								</div>
							</div>
							
							<div class="row">
								<div class="col-12 col-md-5">
									<div class="form-element">
										<label for="image_manager_title">Image Title: </label>
										<input type="text" id="image_manager_title" name="image_manager_title" class="form-control" value=""/>
										<div id="image_manager_title-error" class="error w-100 text-center">&nbsp;</div>
									</div>
								</div>
								
								<div class="col-12 col-md-4">
									<div class="form-element">
										<label for="image_manager_alt_text">Image Alt Text:</label>
										<input type="text" id="image_manager_alt_text" name="image_manager_alt_text" class="form-control" value=""/>
										<div id="image_manager_alt_text-error" class="error w-100 text-center">&nbsp;</div>
									</div>
								</div>
							</div>
							
							<div class="row">
								<div class="col-12">
									<div class="form-element">
										<label for="image_manager_caption">Caption</label>
										<textarea id="image_manager_caption" name="image_manager_caption" class="md-textarea form-control" rows="3"></textarea>
										<div id="image_manager_caption-error" class="error w-100 text-center">&nbsp;</div>
									</div>
								</div>
							</div>
							
							<div id="progress-wrp">
								<div class="progress-bar"></div>
								<div class="status">0%</div>
							</div>
							
							<div class="text-right w-100">
								<button type="button" id="image_manager_clear_button" class="btn btn-primary-outline btn-round btn-sm waves-effect waves-light">cancel</button>
								<button type="button" id="image_manager_upload_button" class="btn btn-primary btn-round btn-sm waves-effect waves-light">upload</button>
							
							</div>
						
						</div>
					
					</div>
				</div>
			
			</div>
			<!-- /Image Input -->
			
			<!-- Company Images -->
			<div class="col-12 col-md-6" id="companyImages">
				<div class="card mb-2">
					<div class="card-body">
						<!-- Actions -->
						<a id="image_manager_cancel_upload" class="activator waves-effect waves-light mr-4">
							<i class="fas fa-times"></i>
						</a>
						<!-- Title -->
						<h4 class="card-title">Image Carousel</h4>
						<h6 class="card-subtitle mb-2 text-muted">Panel subtitle</h6>
						<hr>
						<div id="carousel-companyImageManager" class="carousel slide carousel-fade" data-ride="carousel">
							
							<!--Indicators-->
							<ol class="carousel-indicators" id="carousel-indicators-companyImageManager">
								<!--
								<li data-target="#carousel-companyImageManager" data-slide-to="0" class="active"></li>
								<li data-target="#carousel-companyImageManager" data-slide-to="1"></li>
								<li data-target="#carousel-companyImageManager" data-slide-to="2"></li>
								-->
							</ol>
							<!--/.Indicators-->
							
							<!--Slides-->
							<div class="carousel-inner" role="listbox">
								<!--
								<div class="carousel-item active">
									<div class="view">
										<img class="d-block w-100 h-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(68).jpg"
											 alt="First slide">
										<div class="mask rgba-blue-light"></div>
									</div>
									<div class="carousel-caption">
										<h3 class="h3-responsive">Title</h3>
										<p>First text</p>
									</div>
								</div>
								<div class="carousel-item">
									<div class="view">
										<img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(6).jpg"
											 alt="Second slide">
										<div class="mask rgba-blue-light"></div>
									</div>
									<div class="carousel-caption">
										<h3 class="h3-responsive">Title</h3>
										<p>Secondary text</p>
									</div>
								</div>
								<div class="carousel-item">
									<div class="view">
										<img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(9).jpg"
											 alt="Third slide">
										<div class="mask rgba-blue-light"></div>
									</div>
									<div class="carousel-caption">
										<h3 class="h3-responsive">Title</h3>
										<p>Third text</p>
									</div>
								</div>
								-->
							</div>
							<!--/.Slides-->
							
							<!--Controls-->
							<a class="carousel-control-prev" href="#carousel-companyImageManager" role="button" data-slide="prev">
								<span class="carousel-control-prev-icon" aria-hidden="true"></span>
								<span class="sr-only">Previous</span>
							</a>
							<a class="carousel-control-next" href="#carousel-companyImageManager" role="button" data-slide="next">
								<span class="carousel-control-next-icon" aria-hidden="true"></span>
								<span class="sr-only">Next</span>
							</a>
							<!--/.Controls-->
						</div>
					</div>
				</div>
			</div>
			<!-- /Company Images -->
		
		</div>
	
	</form>
	
	<div class="row">
		
		<!-- Provider Short Description -->
		<div class="col-12 col-md-6">
			<div class="card mb-2">
				<div class="card-body">
					
					<!-- Title -->
					<h4 class="card-title">Short Description</h4>
					<hr>
					<!-- Text -->
					
					<div class="row">
						<div class="col-12">
							<div class="form-element">
								<label for="provider_description_short" style="display:none">&nbsp;</label>
								<textarea id="provider_description_short" name="provider_description_short" class="md-textarea form-control" rows="4"></textarea>
								<div id="provider_description_short-error" class="error w-100 text-center">&nbsp;</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- /Provider Short Description -->
		
		<!-- Detailed Provider Description -->
		<div class="col-12 col-md-6">
			<div class="card mb-2">
				<div class="card-body">
					<!-- Social shares button -->
					<a id="button_provider_description_long_toggle" class="activator but_toggle waves-effect waves-light mr-4" data-texted="provider_description_long">
						<i class="fas fa-sliders-h"></i>
					</a>
					<!-- Title -->
					<h4 class="card-title">Detailed Description</h4>
					<hr>
					<!-- Text -->
					
					<div class="row">
						<div class="col-12">
							<div class="form-element">
								<label for="provider_description_long" style="display:none">Cover Image:</label>
								<textarea id="provider_description_long" name="provider_description_long" class="md-textarea tmceEl form-control" rows="4"></textarea>
								<div id="provider_description_long-error" class="error w-100 text-center">&nbsp;</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- /Detailed Provider Description -->
	
	</div>
	
	<div class="row">
		
		<!-- Provider Keywords -->
		<div class="col-12 col-md-6">
			<div id="provider_keyword" class="card mb-2 keyword">
				<div class="card-body p-0">
					<input class="user-release-input form-control form-control-lg" type="text" placeholder="Keywords..."/>
					<div class="container my-2 chips_container">
					
					</div>
					<div class="text-right w-100">
						<button type="button" class="btn btn-primary btn-round btn-sm waves-effect waves-light">submit</button>
					</div>
				</div>
			</div>
		</div>
		<!-- /Provider Keywords -->
	
	</div>
	
	<div class="row">
		
		<!-- First column -->
		<div class="col-md-12">
			
			<div id="image_gallery"></div>
			
			<div class="mdb-lightbox">
				
				<figure class="col-md-4">
					
					<a href="https://mdbootstrap.com/img/Photos/Lightbox/Original/img%20(145).jpg" data-size="1600x1067">
						<img src="https://mdbootstrap.com/img/Photos/Lightbox/Thumbnail/img%20(145).jpg" class="img-fluid">
					</a>
					
					<figcaption itemprop="caption description">
						Lightbox description text
					</figcaption>
				
				</figure>
			
			</div>
		
		</div>
		<!-- First column -->
	
	</div>

</section>


