<!-- Edit Provider Form -->
<form id="form_edit_provider" name="form_edit_provider" class="" novalidate>
    <div class="card mb-2">
        <div class="card-body">
            
            <!-- Card Header -->
            <h4 class="card-title">Provider Details</h4>
            <h6 class="card-subtitle mb-2 text-muted">Panel subtitle</h6>
            <hr class="ml-3 mr-3 mt-1 mb-3 color-dark">
            <!-- /Card Header -->
            
            <!-- Card Content -->
            <div class="row">
                
                <!-- Provider Name -->
                <div class="col-12 col-lg-3 ">
                    <div class="form-element">
                        <label for="provider_name" class="active">Provider Name:</label>
                        <input type="text" id="provider_name" name="provider_name" class="form-control" aria-label="Provider Name" placeholder="" autocomplete="off" readonly="readonly">
                        <div id="provider_name-error" class="error w-100 text-center">&nbsp;</div>
                    </div>
                </div>
                <!-- /Provider Name -->
                
                <!-- Provider Id -->
                <div class="col-12 col-lg-3 ">
                    <div class="form-element">
                        <label for="provider_id">Provider Id:</label>
                        <input type="text" id="provider_id" name="provider_id" class="form-control" aria-label="Provider Id" placeholder="" autocomplete="off" readonly="readonly"/>
                        <div id="provider_id-error" class="error w-100 text-center">&nbsp;</div>
                    </div>
                </div>
                <!-- /Provider Id -->
                
                <!-- Provider Company Id -->
                <div class="col-12 col-lg-3 ">
                    <div class="form-element">
                        <label for="provider_company_id">Provider Company Id:</label>
                        <input type="text" id="provider_company_id" name="provider_company_id" class="form-control" aria-label="Provider Id" placeholder="" autocomplete="off" readonly="readonly"/>
                        <div id="provider_company_id-error" class="error w-100 text-center">&nbsp;</div>
                    </div>
                </div>
                <!-- /Provider Company Id -->
                
                <!-- Provider Enabled -->
                <div class="col-12 col-lg-2 d-flex align-self-end justify-content-end pb-2">
                    <div class="form-element">
                        <div class="custom-control custom-switch">
                            <input id="provider_enabled" name="provider_enabled" type="checkbox" value="1" class="custom-control-input">
                            <label for="provider_enabled" class="custom-control-label p-0">Enabled</label>
                        </div>
                    </div>
                </div>
                <!-- /Provider Enabled -->
            
            </div>
            <!-- /Card Content -->
            
            <div class="row">
                
                <!-- Code Direct Id -->
                <div class="col-12 col-lg-6 ">
                    <div class="form-element">
                        <label for="provider_code_direct_id">Code Direct Id:</label>
                        <input type="text" id="provider_code_direct_id" name="provider_code_direct_id" class="form-control" aria-label="Provider Code Direct Id" placeholder="" autocomplete="off" readonly="readonly"/>
                        <div id="provider_code_direct_id-error" class="error w-100 text-center">&nbsp;</div>
                    </div>
                </div>
                <!-- /Code Direct Id -->
            
            </div>
        </div>
    </div>
</form>
<!-- /Edit Provider Form -->
