<section>
    <form id="companyImageManager" novalidate>
        <div class="row">
            <div class="col-12 col-md-6">
                
                <div class="card mb-2">
                    <div class="card-body">
                        <!-- Social shares button -->
                        <a class="activator waves-effect waves-light mr-4"><i class="fas fa-share-alt"></i></a>
                        <!-- Title -->
                        <h4 class="card-title">Images</h4>
                        <hr>
                        
                        <div class="row">
                            
                            <!-- Company Image -->
                            <div class="col-12">
                                <div class="form-element" style="">
                                    <input id="image_manager_upload" name="image_manager_upload" type="file" class="dropify" data-height="200"/>
                                    <div id="image_manager_upload-error" class="error w-100 text-center" style="">&nbsp;</div>
                                </div>
                            </div>
                            <!-- /Company Image -->
                        </div>
                        
                        <div id="image_manager_form_data" style="display:none">
                            <div class="row">
                                <div class="col-12 col-md-3 d-flex align-self-center justify-content-end pb-2">
                                    <div class="custom-control custom-switch" style="">
                                        <input id="image_manager_is_cover_image" name="image_manager_is_cover_image" type="checkbox" value="1" class="custom-control-input" style="">
                                        <label for="image_manager_is_cover_image" class="custom-control-label p-0" style="">Is Cover</label>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row" style="">
                                <div class="col-12 col-md-5">
                                    <div class="form-element" style="">
                                        <label for="image_manager_title">Image Title: </label>
                                        <input type="text" id="image_manager_title" name="image_manager_title" class="form-control" value=""/>
                                        <div id="image_manager_title-error" class="error w-100 text-center" style="">&nbsp;</div>
                                    </div>
                                </div>
                                
                                <div class="col-12 col-md-4">
                                    <div class="form-element" style="">
                                        <label for="image_manager_alt_text">Image Alt Text:</label>
                                        <input type="text" id="image_manager_alt_text" name="image_manager_alt_text" class="form-control" value=""/>
                                        <div id="image_manager_alt_text-error" class="error w-100 text-center" style="">&nbsp;</div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row" style="">
                                <div class="col-12">
                                    <div class="form-element" style="">
                                        <label for="image_manager_caption">Caption</label>
                                        <textarea id="image_manager_caption" name="image_manager_caption" class="md-textarea form-control" rows="3"></textarea>
                                        <div id="image_manager_caption-error" class="error w-100 text-center" style="">&nbsp;</div>
                                    </div>
                                </div>
                            </div>

                            <div id="progress-wrp">
                                <div class="progress-bar"></div>
                                <div class="status">0%</div>
                            </div>
                            
                            <div class="text-right w-100" style="">
                                <button type="button" id="image_manager_upload_button" class="btn btn-primary btn-round btn-sm waves-effect waves-light">upload</button>
                            </div>
                        
                        </div>
                    
                    </div>
                </div>
            
            </div>
            
            <div id="companyImages" class="col-12 col-md-6">
                <!--Carousel Wrapper-->
                <div id="carousel-companyImageManager" class="carousel slide carousel-fade" data-ride="carousel">

                    <!--Indicators-->
                    <ol class="carousel-indicators" id="carousel-indicators-companyImageManager">
                        <!--
                        <li data-target="#carousel-companyImageManager" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-companyImageManager" data-slide-to="1"></li>
                        <li data-target="#carousel-companyImageManager" data-slide-to="2"></li>
                        -->
                    </ol>
                    <!--/.Indicators-->

                    <!--Slides-->
                    <div class="carousel-inner" role="listbox">
                        <!--
                        <div class="carousel-item active">
                            <div class="view">
                                <img class="d-block w-100 h-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(68).jpg"
                                     alt="First slide">
                                <div class="mask rgba-blue-light"></div>
                            </div>
                            <div class="carousel-caption">
                                <h3 class="h3-responsive">Title</h3>
                                <p>First text</p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="view">
                                <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(6).jpg"
                                     alt="Second slide">
                                <div class="mask rgba-blue-light"></div>
                            </div>
                            <div class="carousel-caption">
                                <h3 class="h3-responsive">Title</h3>
                                <p>Secondary text</p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="view">
                                <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(9).jpg"
                                     alt="Third slide">
                                <div class="mask rgba-blue-light"></div>
                            </div>
                            <div class="carousel-caption">
                                <h3 class="h3-responsive">Title</h3>
                                <p>Third text</p>
                            </div>
                        </div>
                        -->
                    </div>
                    <!--/.Slides-->

                    <!--Controls-->
                    <a class="carousel-control-prev" href="#carousel-companyImageManager" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carousel-companyImageManager" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                    <!--/.Controls-->
                </div>
                <!--/.Carousel Wrapper-->
            
            </div>
        
        </div>
    </form>
    
    <div class="row">
        
        <div class="col-12 col-md-6">
            
            <!-- Provider Keywords -->
            <div id="provider_keyword" class="card mb-2 keyword">
                <div class="card-body p-0">
                    
                    <input class="user-release-input form-control form-control-lg" type="text" placeholder="Keywords..."/>
                    
                    <div class="container my-2 chips_container">
                    
                    </div>
                    <div class="text-right w-100">
                        <button type="button" class="btn btn-primary btn-round btn-sm waves-effect waves-light">submit</button>
                    </div>
                </div>
            </div>
            <!-- /Provider Keywords -->
            
            <!-- Provider Short Description -->
            <div class="card mb-2">
                <div class="card-body">
                    
                    <!-- Title -->
                    <h4 class="card-title">Short Description</h4>
                    <hr>
                    <!-- Text -->
                    
                    <div class="row">
                        <div class="col-12">
                            <div class="form-element" style="">
                                <label for="provider_description_short" style="display:none">&nbsp;</label>
                                <textarea id="provider_description_short" name="provider_description_short" class="md-textarea form-control" rows="4"></textarea>
                                <div id="provider_description_short-error" class="error w-100 text-center" style="">&nbsp;</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Provider Short Description -->
        
        </div>
    
    </div>
    
    <div class="row">
        
        <div class="col-12 col-lg-6 mb-1">
            
            <!-- Detailed Provider Description -->
            <div class="card mb-2">
                <div class="card-body">
                    <!-- Social shares button -->
                    <a id="button_provider_description_long_toggle" class="activator but_toggle waves-effect waves-light mr-4" data-texted="provider_description_long">
                        <i class="fas fa-sliders-h"></i>
                    </a>
                    <!-- Title -->
                    <h4 class="card-title">Detailed Description</h4>
                    <hr>
                    <!-- Text -->
                    
                    <div class="row">
                        <div class="col-12">
                            <div class="form-element" style="">
                                <label for="provider_description_long" style="display:none">Cover Image:</label>
                                <textarea id="provider_description_long" name="provider_description_long" class="md-textarea tmceEl form-control" rows="4"></textarea>
                                <div id="provider_description_long-error" class="error w-100 text-center" style="">&nbsp;</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Detailed Provider Description -->
        
        </div>
    
    </div>

</section>
<script>
    /*
    $.fn.BuildKeyword = function (settings) {
        const el = $(this)
        const _keyword_input = el.find("input.user-release-input")
        const _keyword_button = el.find("button.keyword_button")
        const _keyword_list = el.find("div.keyword_list")
        
        if (!_keyword_input || !_keyword_button || !_keyword_list) {
            return
        }
        
        if (!settings) {
            settings = ""
        }
        
        let keywords = settings.split(",").map(function (value) {
            return value.trim()
        })
        
        $(_keyword_button)
          .on("click", function () {
              let keyword = (_keyword_input.val() !== "") ? _keyword_input.val() : null
              if (keyword) {
                  
                  if (!keywords.indexOf(keyword) !== -1) {
                      addKeyWord(keyword)
                  }
                  
              }
          })
        
        const addKeyWord = function (key) {
            buildChip(key)
        }
        
        const buildChip = function (data) {
            
            let removeIcon = $("<i>")
              .addClass("close fas fa-times")
            
            let chipEl = $("<div>")
              .addClass("chip")
              .data("key", data)
              .text(data)
            chipEl.append(removeIcon)
            $(_keyword_list).append(chipEl)
        }
        
        const init = function (keywords) {
            $.each(keywords, function (k, chip) {
                buildChip(chip)
            })
        }
        
        init(keywords)
    }
    
    const _provider_keyword = document.getElementById("provider_keyword")
    
    const init = function (settings) {
        
    }
    
    $(document).ready(function () {
        let keywords = "key1, key2, key3"
        $(_provider_keyword).BuildKeyword(keywords)
    })
//*/
</script>
