<?php
    $page_data = [];
    $types = array();
    if (isset($data)) {
        $page_data = $data;
    }

    if (isset($page_data["types"])) {
        $types = json_encode($page_data["types"], 1);
    }
    //echo "<pre>" . var_export($page_data["providers"], 1) . "</pre>";

?>
<section id="provider_index" class="section">
    
    <div class="row">

        <div class="col-12 col-lg-8 mb-1">
            <?php include_once(__DIR__ . "/tables/provider_index_table.phtml"); ?>
        </div>
    
    </div>

</section>
<script type="text/javascript">
    $(function () {
        Types.init(<?php echo $types;?>)
        Provider.index(<?php echo json_encode($page_data, 1);?>)
    })
</script>
