<?php
    $page_data = [];
    if (isset($data)) {
        $page_data = $data;
    }
?>
<section id="provider_index">
    
    <div class="row">

        <div class="col-12 col-lg-9 col-xl-10 mb-1 order-2 order-lg-1" style="border:solid 1px black;">
            Col 1
        </div>
        
        <div class="col-12 col-lg-3 col-xl-2 mb-1 order-1 order-lg-2" style="border:solid 1px black;">
            <div class="list-group">
                <a class="list-group-item list-group-item-action active" href="javascript:void(0)">
                    <i class="icon wb-dashboard" aria-hidden="true"></i>
                    Overview
                </a>
                <a class="list-group-item" href="javascript:void(0)"><i class="icon wb-pluse" aria-hidden="true"></i>Item 1</a>
                <a class="list-group-item" href="javascript:void(0)"><i class="icon wb-heart" aria-hidden="true"></i>Item 2</a>
                <a class="list-group-item" href="javascript:void(0)"><i class="icon wb-folder" aria-hidden="true"></i>Item 3</a>
            </div>
        </div>
    
    </div>
</section>
<script type="text/javascript">

</script>
