<div class="modal fade" id="modalNewProvider" tabindex="-1" role="dialog" aria-labelledby="modalNewProviderLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">×</span>
				</button>
				
				<h4 class="modal-title debug" id="modalNewProviderLabel">New Provider</h4>
			</div>
			
			<div class="modal-body">
				<form id="form_provider_add" novalidate="novalidate">
				
				</form>
			</div>
			
			<div class="modal-footer w-100 d-block p-1">
				<div class="row">
					
					<div class="col-12 col-sm-6 text-left">
						<button class="btn btn-outline-secondary btn-sm" id="modal_button_clear_add_provider">Clear</button>
					</div>
					
					<div class="col-12 col-sm-6 text-right">
						<button class="btn btn-outline-primary btn-sm" id="modal_button_cancel_add_provider">Cancel</button>
						<button class="btn btn-primary btn-sm" id="modal_button_submit_add_provider">Save</button>
					</div>
				
				</div>
			</div>
		
		</div>
	</div>
</div>
