<?php
    $user_id = 4;
    if (isset($_SESSION["user_id"])) {
        $user_id = (int)$_SESSION["user_id"];
    }

    if (isset($page_data, $page_data["types"])) {
        if (!defined("TYPES")) {
            define("TYPES", json_encode($page_data["types"], 1));
        }
    }

?>
<body class="trips-skin">
<?php include_once(__DIR__ . "/body/pre_loader.phtml"); ?>
<?php include_once(__DIR__ . "/body/header.phtml"); ?>
<input type="hidden" id="user_id" name="user_id" value="<?php echo $user_id; ?>"/>
<?php include_once(__DIR__ . "/body/alert_box.phtml"); ?>
<?php include_once(__DIR__ . "/body/main.phtml"); ?>
<?php include_once(__DIR__ . "/body/footer.phtml"); ?>
<?php include_once(__DIR__ . "/body/scripts.phtml"); ?>
<script type="text/javascript">
    $(function () {
        Logger.init()
    })
</script>
</body>
