<?php
	$date = new DateTime();
?>
<script type="text/javascript" src="/public/vendor/moment/moment.min.js"></script>
<script type="text/javascript" src="/public/vendor/autocomplete/autocomplete.js"></script>
<script type="text/javascript" src="/public/vendor/DataTables/datatables.min.js"></script>
<script type="text/javascript" src="/public/vendor/validation/jquery.validate.min.js"></script>
<script type="text/javascript" src="/public/vendor/tinymce/tinymce.js"></script>
<script type="text/javascript" src="/public/vendor/select2/select2.full.min.js"></script>

<script type="text/javascript" src="/public/vendor/pickadate/v3.6.2/picker.js"></script>
<script type="text/javascript" src="/public/vendor/pickadate/v3.6.2/picker.date.js"></script>
<script type="text/javascript" src="/public/vendor/pickadate/v3.6.2/picker.time.js"></script>

<!--
<script type="text/javascript" src="/public/vendor/pickadate/v3.6.4/picker.js"></script>
<script type="text/javascript" src="/public/vendor/pickadate/v3.6.4/picker.date.js"></script>
<script type="text/javascript" src="/public/vendor/pickadate/v3.6.4/picker.time.js"></script>
-->
<script type="text/javascript" src="/public/vendor/pluralize/v8.0.0/pluralize.min.js"></script>
<script type="text/javascript" src="/public/vendor/jquery-tabledit/v1.2.3/jquery.tabledit.min.js"></script>
<script type="text/javascript" src="/public/vendor/logger/Logger.js"></script>
<script type="text/javascript" src="/public/vendor/list/v2.3.1/list.js"></script>
<script type="text/javascript" src="/public/vendor/dropify/js/dropify.js"></script>
<script type="text/javascript" src="/public/vendor/colorpicker/bootstrap-colorpicker.min.js"></script>
<script type="text/javascript" src="/public/vendor/validation/additional-methods.min.js"></script>
<script type="text/javascript" src="/public/vendor/prism/v1.25.0/prism.js"></script>
<!--
<script type="text/javascript" src="/public/vendor/pickr/v1.8.2/pickr.min.js"></script>
-->
<script type="text/javascript" src="/public/vendor/actual/v1.0.19/jquery.actual.min.js"></script>
<script type="text/javascript" src="/public/vendor/datepicker/v1.9.0/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="/public/vendor/maxlength/v1.10.0/bootstrap-maxlength.min.js"></script>
<script type="text/javascript" src="/public/vendor/context-menu/v2.0.0/jquery.contextMenu.min.js"></script>
<script type="text/javascript" src="/public/vendor/year-calendar/v.1.1.1/js-year-calendar.min.js"></script>
<!--
<script type="text/javascript" src="/public/vendor/bootstrap-year-calendar/v1.1.0/bootstrap-year-calendar.js"></script>

<script type="text/javascript" src="/public/vendor/bootstrap/bootstrap-collapse.js"></script>
<script type="text/javascript" src="/public/vendor/bootstrap/bootstrap-transition.js"></script>

<script type="text/javascript" src="/public/vendor/weather/v1.0.0/js/weather.min.js"></script>
-->

<script type="text/javascript" src="/public/vendor/jstree/v3.3.12/jstree.min.js"></script>
<script type="text/javascript" src="/public/js/popper.min.js"></script>
<script type="text/javascript" src="/public/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/public/js/mdb.min.js"></script>
<script type="text/javascript" src="/public/js/site.js?v=<?php
	echo $date->getTimestamp(); ?>"></script>
<script type="text/javascript" src="/public/js/test.js"></script>
<script type="text/javascript" src="/public/js/agenda.js"></script>
<script type="text/javascript" src="/public/js/product_location.js"></script>
