<?php
    $date = new DateTime();
?>
<script type="text/javascript" src="/public/vendor/moment/moment.min.js"></script>
<script type="text/javascript" src="/public/vendor/autocomplete/autocomplete.js"></script>
<script type="text/javascript" src="/public/vendor/select2/select2.full.min.js"></script>
<script type="text/javascript" src="/public/vendor/logger/Logger.js"></script>
<script type="text/javascript" src="/public/vendor/dropify/js/dropify.min.js"></script>
<script type="text/javascript" src="/public/vendor/colorpicker/bootstrap-colorpicker.min.js"></script>
<script type="text/javascript" src="/public/vendor/validation/jquery.validate.min.js"></script>
<script type="text/javascript" src="/public/vendor/validation/additional-methods.min.js"></script>
<script type="text/javascript" src="/public/vendor/DataTables/datatables.min.js"></script>
<script type="text/javascript" src="/public/vendor/tinymce/tinymce.js"></script>
<script type="text/javascript" src="/public/js/popper.min.js"></script>
<script type="text/javascript" src="/public/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/public/js/mdb.min.js"></script>
<script type="text/javascript" src="/public/js/site.js"></script>
