<?php
    $date = new DateTime();
?>
<script type="text/javascript" src="/public/vendor/moment/moment.min.js"></script>
<script type="text/javascript" src="/public/vendor/autocomplete/autocomplete.js"></script>
<script type="text/javascript" src="/public/vendor/colorpicker/bootstrap-colorpicker.min.js"></script>
<script type="text/javascript" src="/public/vendor/validation/jquery.validate.min.js"></script>
<script type="text/javascript" src="/public/vendor/validation/additional-methods.min.js"></script>
<script type="text/javascript" src="/public/js/popper.min.js"></script>
<script type="text/javascript" src="/public/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/public/js/mdb.min.js"></script>
<?php
    include $_SERVER["DOCUMENT_ROOT"] . "/public/js/modules/index.php";
?>
<!--
<script type="text/javascript" src="/public/js/site.min.js"></script>
-->
