<script type="text/javascript">
    let showElements
    $(function () {
        $(".debug_demo")
          .on("click", function () {
              showElements = true
              if (!$(this).attr("data-shown")) {
                  $(this).attr("data-shown", "true")
                  showElements = true
              }
              
              if ($(this).attr("data-shown") === "false") {
                  $(this).attr("data-shown", "true")
                  showElements = true
              } else {
                  showElements = false
                  $(this).attr("data-shown", "false")
              }
              
              let els = document.getElementsByClassName("dev-element")
              
              for (var i = 0; i < els.length; i++) {
                  
                  var element = els[i]
                  let tagName = element.tagName
                  
                  if (tagName === "input") {
                      
                      if (showElements === false) {
                          element.hidden = false
                          element.type = "text"
                      } else {
                          element.type = "hidden"
                          element.hidden = true
                      }
                  } else if (tagName === "label") {
                      Console.log("showElements", showElements)
                      if (showElements === false) {
                          $(element).removeClass("d-none")
                      } else {
                          $(element).addClass("d-none")
                      }
                  }
              }
          })
    })
    
    $(function () {
        $("#image_gallery").load("/public/mdb-addons/mdb-lightbox-ui.html")
    })
    
    //weatherUpdate("paris")
    
    $(document).ready(function () {
        //Logger.init()
    })
</script>

<script type="text/javascript">
    let isShift
    let seperator = "-"
    const IsNumeric = function (input, keyCode) {
        if (!isNaN(parseInt(keyCode))) {
            keyCode = parseInt(keyCode)
        }
        if (keyCode === 16) {
            isShift = true
        }
        
        if ((keyCode >= 48 && keyCode <= 57) || (keyCode >= 96 && keyCode <= 105) || (keyCode === 8) || (keyCode === 46)) {
            if (keyCode !== 16) {
                if ((input.value.length === 4 || input.value.length === 7) && keyCode !== 8) {
                    input.value += seperator
                }
                return true
            }
        }
        return false
    }
    
    const ValidateDateFormat = function (input, keyCode) {
        var dateString = input.value
        
        if (keyCode === 16) {
            isShift = false
        }
        var regex = /(((19|20)\d\d)\-(0[1-9]|1[0-2])\-((0|1)[0-9]|2[0-9]|3[0-1]))$/
        if (regex.test(dateString) || dateString.length === 0) {
            $(input).unSetError()
        } else {
            $(input).setError("Invalid Date. Only YYYY-MM-DD format allowed.")
        }
    }
    
    $(document).ready(function () {
        (function ($) {
            $.fn.unSetError = function () {
                let errorElm = this.parents("div.form-element").find("div.error")
                if (this.hasClass("time-format")) {
                    //this.parent().find("input").removeClass("is-invalid");
                    //this.parent().find("span.caret").removeClass("is-invalid");
                    //errorElm = this.parent("div.input-group").parent().find("div.error")
                }
                
                if (this.hasClass("date-format")) {
                    //this.parent().find("input").removeClass("is-invalid");
                    //this.parent().find("span.caret").removeClass("is-invalid");
                    //errorElm = this.parent("div.input-group").parent().find("div.error")
                }
                
                errorElm.html("&nbsp;").hide()
                return this
            }
            
            $.fn.setError = function (msg) {
                let errorElm = this.parents("div.form-element").find("div.error")
                
                if (this.hasClass("time-format")) {
                    errorElm = this.parent("div.input-group").parent().find("div.error")
                }
                
                if (this.hasClass("date-format")) {
                    //errorElm = this.parents("div.form-element").find("div.error")
                }
                
                errorElm.html(msg).show()
                return this
            }
            
        })(jQuery)
        
    })
    
    window.addEventListener("load", function () {
        const inputs = document.getElementsByTagName("input")
        for (let i = 0; i < inputs.length; i++) {
            if (inputs[i].type === "text") {
                if (inputs[i].classList.contains("date-format")) {
                    inputs[i].setAttribute("maxlength", "10")
                    inputs[i].onkeydown = function (event) {
                        return IsNumeric(this, event.keyCode)
                    }
                    inputs[i].onkeyup = function (event) {
                        ValidateDateFormat(this, event.keyCode)
                    }
                }
            }
        }
        //*/
    }, false)

</script>
