<fieldset id="modal_product_transport_fields" data-categoryid="5" class="fieldset-dark">
	<legend class="">
		<h6>Transport Fields</h6>
	</legend>
	
	<div class="row">
		
		<!-- City -->
		<div class="col-12 col-md-8">
			<div class="form-element">
				<label for="modal_product_city_transports">City:</label>
				<input type="text" id="modal_product_city_transports" name="modal_product_city_transports" class="form-control"/>
				<div id="modal_product_city_transports-error" class="error w-100 text-center"></div>
			</div>
		</div>
		<!-- /City -->
	
	</div>

</fieldset>
