<!-- Register Page -->
<section id="login" class="container my-5 px-0">
    <!-- Card -->
    <div class="card bg-white rounded-5 shadow-5-strong">

        <!-- Card Body -->
        <div class="card-body">

            <!-- Card Heading -->
            <div class="row">
                <div class="col-8 col-sm-8 col-md-8 col-lg-9 mb-1">
                    <h5 class="card-title">
                        <span>Login</span>
                    </h5>
                    <h6>Please fill in your credentials to log in</h6>
                </div>
                <div class="col-4 col-sm-4 col-md-4 col-lg-3 text-right">
                    <img src="/public/img/logos/small_logo.png" class="img-fluid" style="height:4.5rem" alt="small_logo">
                </div>
            </div>
            <hr class="ml-3 mr-3 mt-1 mb-3 color-dark">
            <!-- /Card Heading -->

        </div>
        <!-- Card Body -->

    </div>

    <form id="register_new_form" name="register_new_form" class="" novalidate>

        <!-- Panel -->
        <section class="panel z-depth-0 w-100 mb-0">

            <!-- Panel Heading -->
            <header class="panel-heading">
                <div class="row">
                    <div class="col-8">
                        <h4 class="panel-title">Register</h4>
                    </div>
                </div>
            </header>
            <!-- /Panel Heading -->

            <!-- Panel Body -->
            <div class="panel-body px-0 w-100">
                <div class="row">
                    <div class="col-12 col-lg-6 mb-1">

                    </div>
                </div>
            </div>
            <!-- /Panel Body -->

            <!-- Panel Footer -->
            <div class="panel-footer pb-0 text-right">
                <button type="button" id="button_submit_form_new_register" name="button_submit_form_new_register" class="btn btn-primary btn-sm">Save</button>
            </div>
            <!-- /Panel Footer -->

        </section>
        <!-- /Panel -->

    </form>
    <!-- /Edit Company Form -->

</section>
