<!-- Edit Company Form -->
<form id="register_new_form" name="register_new_form" class="" style="" novalidate>

    <!-- Panel -->
    <section class="panel z-depth-0 w-100 mb-0" style="">

        <!-- Panel Heading -->
        <header class="panel-heading" style="">
            <div class="row">
                <div class="col-8">
                    <h4 class="panel-title">Register</h4>
                </div>
            </div>
        </header>
        <!-- /Panel Heading -->

        <!-- Panel Body -->
        <div class="panel-body px-0 w-100" style="">
            <div class="row">
                <div class="col-12 col-lg-6 mb-1" style="">

                </div>
            </div>
        </div>
        <!-- /Panel Body -->

        <!-- Panel Footer -->
        <div class="panel-footer pb-0 text-right">
            <button type="button" id="button_submit_form_new_register" name="button_submit_form_new_register" class="btn btn-primary btn-sm">Save</button>
        </div>
        <!-- /Panel Footer -->

    </section>
    <!-- /Panel -->

</form>
<!-- /Edit Company Form -->
