<?php
    /*
    *
    * -------------------------------------------------------
    * CLASSNAME:        Package
    * GENERATION DATE:  27.10.2021
    * CLASS FILE:       C:\wamp64\www\mockups/generated_classes/Package.php
    * FOR MYSQL TABLE:  package
    * FOR MYSQL DB:     travelsoft
    * -------------------------------------------------------
    * CODE GENERATED BY:
    * MY PHP-MYSQL-CLASS GENERATOR
    * from: >> www.voegeli.li >> (download for free!)
    * -------------------------------------------------------
    *
    */

    namespace Framework\App\Controllers;

    use Framework\Core\Controller;
    use Framework\Core\View;
    use Framework\Logger\Log;

// **********************
// CLASS DECLARATION
// **********************

    class Package extends Controller
    {

// **********************
// ATTRIBUTE DECLARATION
// **********************

        protected static $id;

        protected static $name;
        protected static $day_span;
        protected static $city_id;
        protected static $min_pax;
        protected static $max_pax;
        protected static $description_long;
        protected static $description_short;
        protected static $available_start;
        protected static $available_end;
        protected static $cost;
        protected static $price;
        protected static $margin;
        protected static $enabled;
        protected static $date_created;
        protected static $created_by;
        protected static $date_modified;
        protected static $modified_by;
        protected static $note;

        /**
         * constructor methods
         */
        function __construct()
        {

            parent::__construct();

        }

        /**
         * get id
         */
        function getid()
        {
            return self::$id;
        }

        /**
         * get name
         */
        function getname()
        {
            return self::$name;
        }

        function getday_span()
        {
            return self::$day_span;
        }

        function getcity_id()
        {
            return self::$city_id;
        }

        function getmin_pax()
        {
            return self::$min_pax;
        }

        function getmax_pax()
        {
            return self::$max_pax;
        }

        function getdescription_long()
        {
            return self::$description_long;
        }

        function getdescription_short()
        {
            return self::$description_short;
        }

        function getavailable_start()
        {
            return self::$available_start;
        }

        function getavailable_end()
        {
            return self::$available_end;
        }

        function getcost()
        {
            return self::$cost;
        }

        function getprice()
        {
            return self::$price;
        }

        function getmargin()
        {
            return self::$margin;
        }

        function getenabled()
        {
            return self::$enabled;
        }

        function getdate_created()
        {
            return self::$date_created;
        }

        function getcreated_by()
        {
            return self::$created_by;
        }

        function getdate_modified()
        {
            return self::$date_modified;
        }

        function getmodified_by()
        {
            return self::$modified_by;
        }

        function getnote()
        {
            return self::$note;
        }

// **********************
// SETTER METHODS
// **********************

        public function setid($val)
        {
            self::$id = $val;
        }

        public function setname($val)
        {
            self::$name = $val;
        }

        public function setday_span($val)
        {
            self::$day_span = $val;
        }

        public function setcity_id($val)
        {
            self::$city_id = $val;
        }

        public function setmin_pax($val)
        {
            self::$min_pax = $val;
        }

        public function setmax_pax($val)
        {
            self::$max_pax = $val;
        }

        public function setdescription_long($val)
        {
            self::$description_long = $val;
        }

        public function setdescription_short($val)
        {
            self::$description_short = $val;
        }

        public function setavailable_start($val)
        {
            self::$available_start = $val;
        }

        public function setavailable_end($val)
        {
            self::$available_end = $val;
        }

        public function setcost($val)
        {
            self::$cost = $val;
        }

        public function setprice($val)
        {
            self::$price = $val;
        }

        public function setmargin($val)
        {
            self::$margin = $val;
        }

        public function setenabled($val)
        {
            self::$enabled = $val;
        }

        public function setdate_created($val)
        {
            self::$date_created = $val;
        }

        public function setcreated_by($val)
        {
            self::$created_by = $val;
        }

        public function setdate_modified($val)
        {
            self::$date_modified = $val;
        }

        public function setmodified_by($val)
        {
            self::$modified_by = $val;
        }

        public function setnote($val)
        {
            self::$note = $val;
        }

        /**
         * @param int $package_id
         */
        public static function select(int $package_id)
        {
            $package = PackageModel::getByPackageId((int)$package_id);

            self::$id = $package["id"];

            self::$name = $package["name"];

            self::$day_span = $package["day_span"];

            self::$city_id = $package["city_id"];

            self::$min_pax = $package["min_pax"];

            self::$max_pax = $package["max_pax"];

            self::$description_long = $package["description_long"];

            self::$description_short = $package["description_short"];

            self::$available_start = $package["available_start"];

            self::$available_end = $package["available_end"];

            self::$cost = $package["cost"];

            self::$price = $package["price"];

            self::$margin = $package["margin"];

            self::$enabled = $package["enabled"];

            self::$date_created = $package["date_created"];

            self::$created_by = $package["created_by"];

            self::$date_modified = $package["date_modified"];

            self::$modified_by = $package["modified_by"];

            self::$note = $package["note"];

        }

        public static function delete($id)
        {

        }

        public static function insert()
        {

        }

        public static function update(int $package_id)
        {

        }

    }
