<div class="row gx-1">
	<div class="col-12 p-1">
		
		<div class="card card-body">
			<h5 class="card-title font-weight-bold">
				<span>Itineraries</span>
				<a href="javascript:void(0);" id="itinerary_index_table_panel_link" class="panel_link" aria-hidden="true">Edit</a>
			</h5>
			
			<table id="itinerary_index_table" class="table table-hover dataTable table-striped w-full dtr-inline"></table>
		
		</div>
	</div>
</div>
