<?php
	
	$swatches = [];
	$swatchObjects = [];
	$season_dropdown = "
    <a id='product_edit_season_id' class='btn btn-primary dropdown-toggle m-0 season_toggle waves-effect waves-light' type='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
	    <span id='product_edit_season_id_name_display'>Color Scheme Select</span>
    </a>
    <div class='dropdown-menu season_toggle_menu'>
            <h5 class='popover-header card-title mb-1'>

                Color Schemes
            
                <a href='javascript:void(0);' class='popup-window-button-close fas fa-times' aria-hidden='true' ></a>
            </h5>
        <div class='row mx-1'>
    ";
	$color_scheme = json_encode((isset($page_data, $page_data["types"], $page_data["types"]["color_scheme"])) ? $page_data["types"]["color_scheme"] : [], 1);
	if (isset($page_data["types"]["color_scheme"])) {
		$count = 0;
		
		for ($n = 0; $n < count($page_data["types"]["color_scheme"]); $n++) {
			$backgroundColor = $page_data["types"]["color_scheme"][$n]["background_color"];
			$name = $page_data["types"]["color_scheme"][$n]["name"];
			$id = $page_data["types"]["color_scheme"][$n]["id"];
			$textColor = $page_data["types"]["color_scheme"][$n]["text_color"];
			$borderColor = $page_data["types"]["color_scheme"][$n]["border_color"];
			$option = $n + 1;
			if ($count % 4 == 0 && $count > 0) {
				$season_dropdown .= "</div><div class='row mx-1'>";
			}
			
			$season_dropdown .= "
            <div class='col-3 col-sm-3 p-1'>
                <a id='$id'
                    class='dropdown-item season_toggle_item m-1'
                    data-schemeName = '$name'
                    data-backgroundColor = '$backgroundColor'
                    data-textColor = '$textColor'
                    data-borderColor = '$borderColor'
                    data-colorSchemeId = '$id'
                    href='javascript:void(0)'
                    style='background-color:$backgroundColor; color: $textColor; /*box-sizing: border-box; box-shadow: inset 0px 0px 0px 1px $borderColor;*/outline: 1px solid $borderColor; outline-offset: -1px;margin-bottom:2px;'
                >
                    $name
                </a>
                </div>
            ";
			$swatches[] = $page_data["types"]["color_scheme"][$n]["background_color"];
			$swatchObjects[] = "
                <div class='col-3 text-center'>
                    <div id='color_scheme_$id' class='m-1 p-1 color_scheme_block' style='background:$backgroundColor;color:$textColor;border:solid 1px $borderColor;cursor:pointer;' onclick='ColorSwatches.edit(this)'>
                       <span class=''>$name</span>
                       <span class='color_scheme_block_edit'>
                       <i class='fas fa-edit'></i>
                       </span>
                    </div>
                </div>
            ";
			$count++;
		}
		$season_dropdown .= "</div>";
	}
	
	$season_dropdown .= "</div>";
?>

<section id="product_edit_season_section">
    
    <div class="row">
        <div class="col-12">
            <div class="form-element">
                <label for="product_edit_season_form_season_name_filter" class="d-none">Season Search:</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="fas fa-search" aria-hidden="true"></i>
                        </span>
                    </div>
                    <input type="search" id="product_edit_season_form_season_name_filter" name="product_edit_season_form_season_name_filter" class="form-control" placeholder="Search Seasons"/>
                </div>
                <div id="product_edit_season_form_season_name_filter-error" class="error w-100 text-center"></div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-12">
			<?php include_once(VIEWS_PATH . "/seasons/tables/product_edit_season_table.phtml"); ?>
        </div>
    </div>
    
    <div class="card card-body mb-2" id="edit_product_season">
        <h5 class="card-title">
            <span>Season</span>
        </h5>
        <h6 class="card-subtitle mb-2 text-muted" id="display_product_season_name">Details</h6>
        <hr class="ml-3 mr-3 mt-1 mb-3 color-dark">
        
        <div class="row mb-2">
            
            <!-- Season Id -->
            <div class="col-12 col-md-6 col-lg-2 col-xl-2">
                <div class="form-element">
                    <label for="product_edit_season_form_season_id">Id:</label>
                    <input type="text" id="product_edit_season_form_season_id" name="product_edit_season_form_season_id" class="form-control" readonly="readonly"/>
                    <div id="product_edit_season_form_season_id-error" class="error w-100 text-center"></div>
                </div>
            </div>
            <!-- /Season Id -->
            
            <!-- Season Name -->
            <div class="col-12 col-md-6 col-lg-3 col-xl-3">
                <div class="form-element">
                    <label for="product_edit_season_form_season_name">Name:</label>
                    <input type="text" id="product_edit_season_form_season_name" name="product_edit_season_form_season_name" class="form-control" readonly="readonly"/>
                    <div id="product_edit_season_form_season_name-error" class="error w-100 text-center"></div>
                </div>
            </div>
            <!-- /Season Name -->
            
            <!-- Season Color Scheme ID -->
            <div class="col-12 col-md-6 col-lg-4 col-xl-4">
                
                <div class="form-element">
                    <label for="product_edit_season_form_season_color_scheme_id">Color Scheme:</label>
                    <input type="hidden" id="product_edit_season_form_season_color_scheme_id" name="product_edit_season_form_season_color_scheme_id" class="form-control dev-element" readonly="readonly"/>
                    <div class="m-0 p-0 w-100">
						<?php echo $season_dropdown; ?>
                    </div>
                    <div id="product_edit_season_form_season_color_scheme_id-error" class="error w-100 text-center"></div>
                
                </div>
            </div>
            <!-- /Season Color Scheme ID -->
            
            <!-- Season Enabled -->
            <div class="col-12 col-md-6 col-lg-2 col-xl-2 d-flex align-items-end justify-content-end pb-2">
                <div class="form-element">
                    <div class="custom-control custom-switch">
                        <input id="product_edit_season_form_season_enabled" name="product_edit_season_form_season_enabled" type="checkbox" value="1" class="custom-control-input" readonly="readonly">
                        <label for="product_edit_season_form_season_enabled" class="custom-control-label p-0">Enabled</label>
                    </div>
                    <div id="product_edit_season_form_season_enabled-error" class="error w-100 text-center"></div>
                </div>
            </div>
            <!-- /Season Enabled -->
            
            <!-- Edit Season Link -->
            <div class="col-12 col-md-6 col-lg-2 col-xl-1 d-flex align-items-end justify-content-end pb-3">
                <a href="javascript:void(0);" id="product_edit_season_form_edit_season_link" class="">Edit</a>
            </div>
            <!-- /Edit Season Link -->
        
        </div>
        
        <div class="row" id="edit_season">
            <!--
            <div class="col">
                <button type="button" id="edit_season_cancel_button" class="btn btn-danger btn-sm" disabled="disabled">
                    <i class="fas fa-edit mx-2"></i>
                    <span class="">Cancel</span>
                </button>
                <button type="button" id="edit_season_update_button" class="btn btn-outline-info btn-sm" disabled="disabled">
                    <i class="fas fa-edit mx-2"></i>
                    <span class="">Update</span>
                </button>
            </div>
            -->
        </div>
        
        <hr class="ml-3 mr-3 mt-1 mb-3 color-dark">
        
        <div id="season_disabled_dow" class=""></div>
        
        <div class="row">
            <div class="col-6 text-left w-100 mb-2">
                <a href="javascript:void(0);" id="button_remove_season_from_product" class="btn btn-danger btn-sm waves-effect waves-light">Remove</a>
            </div>
            <div class="col-6 text-right w-100 mb-2">
                <a href="javascript:void(0);" id="button_clear_form_edit_season" class="btn btn-flat primary-text text-center p-1 mx-0 mb-0 waves-effect waves-light">clear</a>
                <a href="javascript:void(0);" id="button_submit_form_edit_season" class="btn btn-primary btn-sm waves-effect waves-light">Update</a>
            </div>
        </div>
    
    </div>

</section>

<script type="text/javascript">
    let settings = {
        swatches: <?php echo $color_scheme;?>,
        els: [
            "#form_edit_scheme_background_color",
            "#form_edit_scheme_text_color",
            "#form_edit_scheme_border_color",
        ],
    }
    $(function () {
        ColorScheme.init(settings)
    })
</script>
