<section>
    <div class="row">
        <div class="col-12">
            <div class="form-element">
                <label for="product_edit_variant_form_variant_name_filter" class="d-none">Variant Search:</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="fas fa-search" aria-hidden="true"></i>
                        </span>
                    </div>
                    <input type="search" id="product_edit_variant_form_variant_name_filter" name="product_edit_variant_form_variant_name_filter" class="form-control" placeholder="Search Variants"/>
                </div>
                <div id="product_edit_variant_form_variant_name_filter-error" class="error w-100 text-center"></div>
            </div>
        </div>
    </div>
    
    <?php include_once(VIEWS_PATH . "/variants/tables/product_edit_variant_table.phtml"); ?>
    
    <div class="card mb-2">
        <div class="card-body">
            <form id="product_edit_variant_form" name="product_edit_variant_form" novalidate>
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-4">
                        <div class="form-element">
                            <label for="product_edit_variant_form_variant_id">Id:</label>
                            <input type="text" id="product_edit_variant_form_variant_id" name="product_edit_variant_form_variant_id" class="form-control"/>
                            <div id="product_edit_variant_form_variant_id-error" class="error w-100 text-center"></div>
                        </div>
                    </div>
                    
                    <div class="col-12 col-md-6 col-lg-4">
                        <div class="form-element">
                            <label for="product_edit_variant_form_variant_name">Name:</label>
                            <input type="text" id="product_edit_variant_form_variant_name" name="product_edit_variant_form_variant_name" class="form-control"/>
                            <div id="product_edit_variant_form_variant_name-error" class="error w-100 text-center"></div>
                        </div>
                    </div>
                
                </div>
            </form>
        </div>
    </div>

</section>
