<?php
	if (!isset($page_data)) {
		$page_data = [];
	}
	
	$currency = [];
	if (isset($page_data["types"]["currency"])) {
		$currency = $page_data["types"]["currency"];
	}
	
	$pricing_strategies = [];
	if (isset($page_data["types"]["pricing_strategy_types"])) {
		$pricing_strategies = $page_data["types"]["pricing_strategy_types"];
	}
	
	$categories = [];
	if (isset($page_data["types"]["category"])) {
		$categories = $page_data["types"]["category"];
	}
	
	$rating_types = [];
	if (isset($page_data["types"]["rating_types"])) {
		$rating_types = $page_data["types"]["rating_types"];
	}
	
	$airport_types = [];
	if (isset($page_data["types"]["airport_types"])) {
		$airport_types = $page_data["types"]["airport_types"];
	}
?>

<div data-categoryid="2" class="row">
	<div class="col-12 px-0">
		<div class="card card-body m-1 p-1 border-1 border-light">
			<h5 class="card-title">
				<span>Airport Fields</span>
			</h5>
			<h6 class="card-subtitle mb-2 text-muted">Additional Product Fields</h6>
			<hr class="ml-3 mr-3 mt-1 mb-3 color-dark"/>
			
			<div class="row">
				
				<div class="col-12">
					<div class="form-element">
						<label for="modal_product_depart_from_airport">Departing From Airport:</label>
						<input type="search" id="modal_product_depart_from_airport" name="modal_product_depart_from_airport" class="form-control"/>
						<div id="modal_product_depart_from_airport-error" class="error w-100 text-center"></div>
					</div>
				</div>
			
			</div>
			
			<div class="card card-body grey lighten-4 mb-2" id="modal_product_depart_from_airport_add_block">
				<div class="row">
					
					<div class="col-6">
						<div class="form-element">
							<label for="modal_product_depart_from_new_airport_id">Id:</label>
							<input type="text" id="modal_product_depart_from_new_airport_id" name="modal_product_depart_from_new_airport_id" class="form-control" readonly="readonly"/>
							<div id="modal_product_depart_from_new_airport_id-error" class="error w-100 text-center"></div>
						</div>
					</div>
					
					<!-- IATA Code -->
					<div class="col-6">
						<div class="form-element">
							<label for="modal_product_depart_from_airport_iata_code">IATA Code:</label>
							<input type="text" id="modal_product_depart_from_airport_iata_code" name="modal_product_depart_from_airport_iata_code" class="form-control"/>
							<div id="modal_product_depart_from_airport_iata_code-error" class="error w-100 text-center"></div>
						</div>
					</div>
				
				</div>
				
				<div class="row">
					
					<div class="col-6">
						<div class="form-element">
							<label for="modal_product_depart_from_airport_types_id">Airport Type:</label>
							<select id="modal_product_depart_from_airport_types_id" name="modal_product_depart_from_airport_types_id" class="form-control">
								<?php
									$options = "<option  value='' disabled selected>-- Airport Type --</option>";
									foreach ($airport_types AS $k => $value) {
										$name = $value["name"];
										$val = $value["id"];
										$options .= "<option value='$val'>$name</option>";
									}
									echo $options;
								?>
							</select>
							<div id="modal_product_depart_from_airport_types_id-error" class="error w-100 text-center"></div>
						</div>
					</div>
				
				</div>
				
				<div class="row">
					
					<div class="col-12">
						<div class="form-element">
							<label for="modal_product_depart_from_airport_city">City/Province/Country:</label>
							<input type="search" id="modal_product_depart_from_airport_city" name="modal_product_depart_from_airport_city" class="form-control"/>
							<div id="modal_product_depart_from_airport_city-error" class="error w-100 text-center"></div>
						</div>
					</div>
				
				</div>
				
				<div class="row">
					
					<div class="col-3">
						<label for="modal_product_depart_from_airport_city_id" class="dev-element d-none">City Id:</label>
						<input type="hidden" id="modal_product_depart_from_airport_city_id" class="form-control dev-element" value="" readonly="readonly"/>
					</div>
					
					<div class="col-3">
						<label for="modal_product_depart_from_airport_province_id" class="dev-element d-none">Province Id:</label>
						<input type="hidden" id="modal_product_depart_from_airport_province_id" class="form-control dev-element" value="" readonly="readonly"/>
					</div>
					
					<div class="col-3">
						<label for="modal_product_depart_from_airport_country_id" class="dev-element d-none">Country Id:</label>
						<input type="hidden" id="modal_product_depart_from_airport_country_id" class="form-control dev-element" value="" readonly="readonly"/>
					</div>
				
				</div>
				
				<div class="row">
					
					<div class="col-6 text-left">
						<button type="button" id="modal_product_depart_from_airport_cancel_button" class="btn btn-outline-primary btn-sm white waves-effect waves-light">Cancel</button>
					</div>
					
					<div class="col-6 text-right">
						<button type="button" id="modal_product_depart_from_airport_submit_button" class="btn btn-primary btn-sm waves-effect waves-light">Save</button>
					</div>
				
				</div>
			</div>
			
			<div class="row">
				<div data-categoryid="2" class="col-12 col-md-6">
					<div id="modal_product_depart_from_date" data-label="Departing Date" data-placeholder="Select Departing Date"></div>
				</div>
				
				<div data-categoryid="2" class="col-12 col-md-6">
					<div id="modal_product_depart_from_time" data-label="Departing Time" data-placeholder="Select Departing Time"></div>
				</div>
			</div>
			
			<hr class="ml-3 mr-3 mt-1 mb-3 color-dark"/>
			
			<div class="row">
				<div class="col-12">
					<div class="form-element">
						<label for="modal_product_arrive_to_airport">Arriving To Airport:</label>
						<input type="search" id="modal_product_arrive_to_airport" name="modal_product_arrive_to_airport" class="form-control"/>
						<div id="modal_product_arrive_to_airport-error" class="error w-100 text-center"></div>
					</div>
				</div>
			</div>
			
			<div class="card card-body grey lighten-4 mb-2" id="modal_product_arrive_to_airport_add_block">
				<div class="row">
					
					<div class="col-6">
						<div class="form-element">
							<label for="modal_product_arrive_to_new_airport_id">Id:</label>
							<input type="text" id="modal_product_arrive_to_new_airport_id" name="modal_product_arrive_to_new_airport_id" class="form-control" readonly="readonly"/>
							<div id="modal_product_arrive_to_new_airport_id-error" class="error w-100 text-center"></div>
						</div>
					</div>
					
					<!-- IATA Code -->
					<div class="col-6">
						<div class="form-element">
							<label for="modal_product_arrive_to_airport_iata_code">IATA Code:</label>
							<input type="text" id="modal_product_arrive_to_airport_iata_code" name="modal_product_arrive_to_airport_iata_code" class="form-control"/>
							<div id="modal_product_arrive_to_airport_iata_code-error" class="error w-100 text-center"></div>
						</div>
					</div>
				
				</div>
				
				<div class="row">
					
					<div class="col-6">
						<div class="form-element">
							<label for="modal_product_arrive_to_airport_types_id">Airport Type:</label>
							<select id="modal_product_arrive_to_airport_types_id" name="modal_product_arrive_to_airport_types_id" class="form-control">
								<?php
									$options = "<option  value='' disabled selected>-- Airport Type --</option>";
									foreach ($airport_types AS $k => $value) {
										$name = $value["name"];
										$val = $value["id"];
										$options .= "<option value='$val'>$name</option>";
									}
									echo $options;
								?>
							</select>
							<div id="modal_product_arrive_to_airport_types_id-error" class="error w-100 text-center"></div>
						</div>
					</div>
				
				</div>
				
				<div class="row">
					
					<div class="col-12">
						<div class="form-element">
							<label for="modal_product_arrive_to_airport_city">City/Province/Country:</label>
							<input type="search" id="modal_product_arrive_to_airport_city" name="modal_product_arrive_to_airport_city" class="form-control"/>
							<div id="modal_product_arrive_to_airport_city-error" class="error w-100 text-center"></div>
						</div>
					</div>
				
				</div>
				
				<div class="row">
					
					<div class="col-3">
						<label for="modal_product_arrive_to_airport_city_id" class="dev-element d-none">City Id:</label>
						<input type="hidden" id="modal_product_arrive_to_airport_city_id" class="form-control dev-element" value="" readonly="readonly"/>
					</div>
					
					<div class="col-3">
						<label for="modal_product_arrive_to_airport_province_id" class="dev-element d-none">Province Id:</label>
						<input type="hidden" id="modal_product_arrive_to_airport_province_id" class="form-control dev-element" value="" readonly="readonly"/>
					</div>
					
					<div class="col-3">
						<label for="modal_product_arrive_to_airport_country_id" class="dev-element d-none">Country Id:</label>
						<input type="hidden" id="modal_product_arrive_to_airport_country_id" class="form-control dev-element" value="" readonly="readonly"/>
					</div>
				
				</div>
				
				<div class="row">
					
					<div class="col-6 text-left">
						<button type="button" id="modal_product_arrive_to_airport_cancel_button" class="btn btn-outline-primary btn-sm white waves-effect waves-light">Cancel</button>
					</div>
					
					<div class="col-6 text-right">
						<button type="button" id="modal_product_arrive_to_airport_submit_button" class="btn btn-primary btn-sm waves-effect waves-light">Save</button>
					</div>
				
				</div>
			</div>
			
			<div class="row">
				<div class="col-12 col-md-6">
					<div id="modal_product_arrive_to_date" data-label="Arriving Date" data-placeholder="Select Arriving Date"></div>
				</div>
				
				<div class="col-12 col-md-6">
					<div id="modal_product_arrive_to_time" data-label="Arriving Time" data-placeholder="Select Arriving Time"></div>
				</div>
			</div>
			
			<div class="row">
				
				<div class="col-12 col-md-6">
					<label for="modal_product_depart_from_airport_id" class="dev-element d-none">Departing From Airport Id:</label>
					<input type="hidden" id="modal_product_depart_from_airport_id" name="modal_product_depart_from_airport_id" class="form-control dev-element" value="" readonly="readonly">
				</div>
				
				<div class="col-12 col-md-6">
					<label for="modal_product_arrive_to_airport_id" class="dev-element d-none">Arriving Airport Id:</label>
					<input type="hidden" id="modal_product_arrive_to_airport_id" name="modal_product_arrive_to_airport_id" class="form-control dev-element" value="" readonly="readonly">
				</div>
			
			</div>
		
		</div>
	</div>
</div>
