<?php
    if (!isset($page_data)) {
        $page_data = [];
    }
?>
<!--
<section class="panel z-depth-0 mb-0 w-100">
    <header class="panel-heading">
        <div class="row">
            
            <div class="col-8">
                <h4 class="panel-title">Providers</h4>
            </div>
            
            <div class="col-4 d-flex align-items-center justify-content-end">
                <div class="panel-actions p-0 m-0">
                    
                    <a class="panel-action fas fa-filter" data-toggle="collapse" href="#provider_index_table_filters" aria-expanded="false" aria-controls="provider_index_table_filters"></a>
                    <a class="panel-action fas fa-plus" data-toggle="panel-button" aria-hidden="true" href="/providers/new" id="button_add_provider_page_table"></a>
                
                </div>
            </div>
        
        </div>
    </header>
    
    <div class="panel-body">
        
        <div class="collapse" id="provider_index_table_filters">
            <div class="card card-body mb-2">
                <div class="row">
                    
                    <div class="col-12 col-lg-4 mb-1">
                        <div class="form-element">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    <table id="table_provider_index" class="table w-100 table-striped" style=""></table>
    
    </div>

</section>
-->
<!-- Table with panel -->
<div class="card card-cascade narrower mb-2">
    
    <!--Card image-->
    <div class="view view-cascade view-table gradient-card-header blue-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
        
        <div>
            <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                <i class="fas fa-th-large mt-0"></i>
            </button>
            <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                <i class="fas fa-columns mt-0"></i>
            </button>
        </div>
        
        <a href="" class="white-text mx-3">Providers</a>
        
        <div>
            <a href="/providers/new" class="btn btn-outline-white btn-sm px-2">
                <i class="wir wi-plus"></i>
            </a>
            <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2" disabled>
                <i class="far fa-trash-alt"></i>
            </button>
            <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2" disabled>
                <i class="wir wi-info-circle"></i>
            </button>
        </div>
    
    </div>
    <!--/Card image-->
    
    <div class="px-4">
        
        <div class="table-wrapper">
            <!--Table-->
            <table class="table table-hover w-100 mb-0" id="table_provider_index"></table>
            <!--Table-->
        </div>
    
    </div>

</div>
<!-- Table with panel -->
