<?php
    if (!isset($page_data)) {
        $page_data = [];
    }
?>
<section class="panel z-depth-0 mb-0 w-100">
    <header class="panel-heading">
        
        <div class="row">
            <div class="col-8">
                <h4 class="panel-title">Providers</h4>
            </div>
            <div class="col-4 d-flex align-items-center justify-content-end">
                <div class="panel-actions p-0 m-0">
                    <a class="panel-action fas fa-filter" data-toggle="collapse" href="#provider_index_table_filters" aria-expanded="false" aria-controls="provider_index_table_filters"></a>
                    <a class="panel-action fas fa-plus" data-toggle="panel-button" aria-hidden="true" href="javascript:void(0)" id="button_add_provider_page_table"></a>
                </div>
            </div>
        </div>
    
    </header>
    
    <div class="panel-body">
        <div class="row">
            <div class="col-12">
                <div class="collapse" id="provider_index_table_filters">
                    <div class="card card-body mb-2">
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="form-element">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <table id="table_provider_index" class="table w-100 table-striped"></table>
    </div>

</section>
