<?php
    if (!isset($page_data)) {
        $page_data = [];
    }
?>

<!-- Table with panel -->
<div class="card card-cascade narrower mb-2">
    
    <!--Card image-->
    <div class="view view-cascade view-table gradient-card-header blue-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
        
        <div>
            <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                <i class="fas fa-th-large mt-0"></i>
            </button>
            <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                <i class="fas fa-columns mt-0"></i>
            </button>
        </div>
        
        <a href="" class="white-text mx-3">Providers</a>
        
        <div>
            <a href="/providers/new" class="btn btn-outline-white btn-sm px-2">
                <i class="wir wi-plus"></i>
            </a>
            <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2" disabled>
                <i class="far fa-trash-alt"></i>
            </button>
            <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2" disabled>
                <i class="wir wi-info-circle"></i>
            </button>
        </div>
    
    </div>
    <!--/Card image-->
    
    <div class="px-4">
        
        <div class="table-wrapper">
            <!--Table-->
            <table class="table table-hover w-100 mb-0" id="table_provider_index"></table>
            <!--Table-->
        </div>
    
    </div>

</div>
<!-- Table with panel -->
