<?php
	if (!isset($page_data)) {
		$page_data = [];
	}
	
	$currency = [];
	if (isset($page_data["types"]["currency"])) {
		$currency = $page_data["types"]["currency"];
	}
	
	$pricing_strategies = [];
	if (isset($page_data["types"]["pricing_strategy_types"])) {
		$pricing_strategies = $page_data["types"]["pricing_strategy_types"];
	}
	
	$categories = [];
	if (isset($page_data["types"]["category"])) {
		$categories = $page_data["types"]["category"];
	}
	
	$rating_types = [];
	if (isset($page_data["types"]["rating_types"])) {
		$rating_types = $page_data["types"]["rating_types"];
	}
	
	$airport_types = [];
	if (isset($page_data["types"]["airport_types"])) {
		$airport_types = $page_data["types"]["airport_types"];
	}
?>

<div class="modal fade" id="modal_new_product" tabindex="-1" role="dialog" aria-labelledby="modal_new_product" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">×</span>
				</button>
				
				<h4 class="modal-title debug" id="modal_addressLabel">New Product</h4>
			</div>
			
			<div class="modal-body">
				<form id="form_product_add" novalidate="novalidate">
					
					<!-- CATEGORY DETAILS -->
					<div class="row">
						<div class="col-6 p-1">
							<div class="form-element">
								<label for="modal_product_category_id">Category:</label>
								<select id="modal_product_category_id" name="modal_product_category_id" class="form-control">
									<?php
										$options = "<option  value='' disabled selected>-- Category --</option>";
										foreach ($categories AS $k => $value) {
											$name = $value["name"];
											$val = $value["id"];
											if ((int)$val !== 0 && (int)$val !== 9 && (int)$val !== 8) {
												$options .= "<option value='$val'>$name</option>";
											}
											
										}
										echo $options;
									?>
								</select>
								<div id="modal_product_category_id-error" class="error w-100 text-center"></div>
							</div>
						</div>
						
						<div class="col-6 p-1">
							<div class="form-element">
								<label for="modal_product_sku">Sku:</label>
								<input type="text" id="modal_product_sku" name="modal_product_sku" class="form-control"/>
								<div id="modal_product_sku-error" class="error w-100 text-center"></div>
							</div>
						</div>
					</div>
					
					<!-- NAME DETAILS -->
					<div class="row">
						<div class="col-12 p-1">
							<div class="form-element">
								<label for="modal_product_name">Name:</label>
								<input type="text" id="modal_product_name" name="modal_product_name" class="form-control"/>
								<div id="modal_product_name-error" class="error w-100 text-center"></div>
							</div>
						</div>
					</div>
					
					<!-- PROVIDER VENDOR DETAILS -->
					<div class="row">
						
						<!-- PROVIDER DETAILS -->
						<div class="col-6 p-1">
							<div class="form-element">
								<label for="modal_product_provider_name">Provider:</label>
								<input type="search" id="modal_product_provider_name" name="modal_product_provider_name" class="form-control"/>
								<div id="modal_product_provider_name-error" class="error w-100 text-center"></div>
								
								<label for="modal_product_provider_id" class="dev-element d-none">Provider Id:</label>
								<input type="hidden" id="modal_product_provider_id" name="modal_product_provider_id" class="form-control dev-element" placeholder="" readonly="readonly"/>
								
								<label for="modal_product_provider_company_id" class="dev-element d-none">Provider Company Id:</label>
								<input type="hidden" id="modal_product_provider_company_id" name="modal_product_provider_company_id" class="form-control dev-element" placeholder="" readonly="readonly"/>
								
								<label for="modal_product_provider_location_id" class="dev-element d-none">Provider Location Id:</label>
								<input type="hidden" id="modal_product_provider_location_id" name="modal_product_provider_location_id" class="dev-element form-control" placeholder="" readonly="readonly"/>
								
								<label for="modal_product_location_id" class="dev-element d-none">Location Id:</label>
								<input type="hidden" id="modal_product_location_id" name="modal_product_location_id" class="form-control dev-element" placeholder="" readonly="readonly"/>
							
							</div>
						</div>
						
						<!-- VENDOR DETAILS -->
						<div class="col-6 p-1">
							<div class="form-element">
								<div class="form-element">
									<label for="modal_product_vendor_name">Vendor:</label>
									<input type="search" id="modal_product_vendor_name" name="modal_product_vendor_name" class="form-control"/>
									<div id="modal_product_vendor_name-error" class="error w-100 text-center"></div>
									
									<label for="modal_product_vendor_id" class="dev-element d-none">Vendor Id:</label>
									<input type="hidden" id="modal_product_vendor_id" name="modal_product_vendor_id" class="form-control dev-element" placeholder="" readonly="readonly"/>
									<label for="modal_product_vendor_company_id" class="dev-element d-none">Vendor Company Id:</label>
									<input type="hidden" id="modal_product_vendor_company_id" name="modal_vendor_provider_company_id" class="form-control dev-element" placeholder="" readonly="readonly"/>
								
								</div>
							</div>
						</div>
					
					</div>
					
					<!-- PROVIDER IS VENDOR DETAILS -->
					<div class="row">
						
						<div class="col-12 p-1">
							<div class="custom-control custom-checkbox custom-control-inline">
								<input type="checkbox" class="custom-control-input" id="modal_product_provider_vendor_match" name="modal_product_provider_vendor_match">
								<label class="custom-control-label" for="modal_product_provider_vendor_match">Provider is also Vendor</label>
							</div>
						</div>
					
					</div>
					
					<!-- Hotel -->
					<?php include_once(VIEWS_PATH . "/hotels/forms/product_new_hotel_form.phtml"); ?>
					<!-- /Hotel -->
					
					<!-- Airport -->
					<?php include_once(VIEWS_PATH . "/airports/forms/product_new_airport_form.phtml"); ?>
					<!-- /Airport -->
					
					<!-- Station -->
					<?php include_once(VIEWS_PATH . "/stations/forms/product_new_station_form.phtml"); ?>
					<!-- /Station -->
					
					<!-- Car -->
					<?php include_once(VIEWS_PATH . "/cars/forms/product_new_cars_form.phtml"); ?>
					<!-- /Car -->
					
					<!-- Transport -->
					<?php include_once(VIEWS_PATH . "/transports/forms/product_new_transports_form.phtml"); ?>
					<!-- /Transport -->
					
					<!-- Tours -->
					<?php include_once(VIEWS_PATH . "/tours/forms/product_new_tours_form.phtml"); ?>
					<!-- /Tours -->
					
					<!-- Rating Id, Currency Id, Pricing Strategy Id -->
					<div class="row">
						
						<!-- Rating Id -->
						<div class="col-12 col-md-4 p-1">
							<div class="form-element">
								<label for="modal_product_rating_types_id">Rating:</label>
								<select id="modal_product_rating_types_id" name="modal_product_rating_types_id" class="form-control">
									<?php
										$options = "<option  value='' disabled selected>-- Rating --</option>";
										foreach ($rating_types AS $k => $value) {
											$name = $value["name"];
											$val = $value["id"];
											$options .= "<option value='$val'>$name</option>";
										}
										echo $options;
									?>
								</select>
								<div id="modal_product_rating_types_id-error" class="error w-100 text-center"></div>
							</div>
						</div>
						<!-- /Rating Id -->
						
						<!-- Currency Id -->
						<div class="col-12 col-md-4 p-1">
							<div class="form-element">
								<label for="modal_product_currency_id">Currency:</label>
								<select id="modal_product_currency_id" name="modal_product_currency_id" class="form-control">
									<?php
										$options = "<option  value='' disabled selected>-- Currency --</option>";
										foreach ($currency AS $k => $value) {
											$name = $value["name"];
											$val = $value["id"];
											$options .= "<option value='$val'>$name</option>";
										}
										echo $options;
									?>
								</select>
								<div id="modal_product_currency_id-error" class="error w-100 text-center"></div>
							</div>
						</div>
						<!-- /Currency Id -->
						
						<!-- Pricing Strategy Id -->
						<div class="col-12 col-md-4 p-1">
							<div class="form-element">
								<label for="modal_product_pricing_strategies_types_id">Pricing Strategy:</label>
								<select id="modal_product_pricing_strategies_types_id" name="modal_product_pricing_strategies_types_id" class="form-control">
									<?php
										$options = "<option  value='' disabled selected>-- Pricing Strategy --</option>";
										foreach ($pricing_strategies AS $k => $value) {
											$name = $value["name"];
											$val = $value["id"];
											$options .= "<option value='$val'>$name</option>";
										}
										echo $options;
									?>
								</select>
								<div id="modal_product_pricing_strategies_types_id-error" class="error w-100 text-center"></div>
							</div>
						</div>
						<!-- /Pricing Strategy Id -->
					
					</div>
					<!-- /Rating Id, Currency Id, Pricing Strategy Id -->
					
					<!-- HIDDEN VALUES -->
					<div class="row">
						
						<div class="col-3 col-md-3">
							<label for="modal_product_country_id" class="dev-element d-none">Country Id:</label>
							<input type="hidden" id="modal_product_country_id" class="form-control dev-element" value="" readonly="readonly"/>
						</div>
						<div class="col-3 col-md-3">
							<label for="modal_product_province_id" class="dev-element d-none">Province Id:</label>
							<input type="hidden" id="modal_product_province_id" class="form-control dev-element" value="" readonly="readonly"/>
						</div>
						<div class="col-3 col-md-3">
							<label for="modal_product_city_id" class="dev-element d-none">City Id:</label>
							<input type="hidden" id="modal_product_city_id" class="form-control dev-element" value="" readonly="readonly"/>
						</div>
					
					</div>
					<!-- HIDDEN VALUES -->
				</form>
			</div>
			
			<div class="modal-footer w-100 d-block p-1">
				<div class="row">
					
					<div class="col-12 col-sm-6 text-left">
						<button class="btn btn-outline-secondary btn-sm" id="modal_button_clear_add_product">Clear</button>
					</div>
					
					<div class="col-12 col-sm-6 text-right">
						<button class="btn btn-outline-primary btn-sm" id="modal_button_cancel_add_product">Cancel</button>
						<button class="btn btn-primary btn-sm" id="modal_button_submit_add_product">Save</button>
					</div>
				
				</div>
			</div>
		
		</div>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function () {
		const $rating = $("#rating")
		const $rating_types_id = $("#rating_types_id")
		if ($rating) {
			$rating.mdbRate()
		}
		
		$stars = $rating.children()
		$stars.on("mouseover", function () {
			let index = (!isNaN($(this).attr("data-index"))) ? parseInt($(this).attr("data-index")) : 0
			$rating_types_id.val((index) + 1)
		})
		
		const buildSKU = function (stringValue) {
			console.log("buildSKU(stringValue)", stringValue)
			let myArray = []
			let categorySection = null
			let productSection = ""
			let providerSection = null
			let vendorSection = null
			
			if ((isNaN(parseInt($("#modal_product_category_id").val())))) {
				return
			}
			let category_id = (!isNaN(parseInt($("#modal_product_category_id").val()))) ? parseInt($("#modal_product_category_id").val()) : null
			let category = Types.category.get(category_id)
			if (category) {
				categorySection = category.attribute_id
			}
			
			let codeValue = ""
			if (stringValue) {
				codeValue = stringValue.toUpperCase().trim()
				myArray = codeValue.split(" ")
				//console.log("myArray", myArray)
			}
			
			if (myArray.length === 0) {
				/**
				 * no words
				 */
				
			} else if (myArray.length === 1) {
				/**
				 * one words
				 */
				
			} else if (myArray.length === 2) {
				/**
				 * two words
				 */
				
			} else if (myArray.length === 3) {
				for (let n = 0; n < myArray.length; n++) {
					productSection += myArray[n].charAt(0)
				}
			} else {
			
			}
			//console.log("sku", categorySection + "-" + productSection)
			if (categorySection !== "" && productSection !== "" && providerSection !== "" && vendorSection !== "") {
				//console.log("sku", categorySection + "-" + productSection)
			}
			
			return codeValue
		}
		
	})
</script>
