<!-- New Package Modal -->
<div class="modal fade" id="package_add_modal" tabindex="-1" role="dialog" aria-labelledby="package_add_modal" aria-hidden="true">
	
	<div class="modal-dialog modal-lg" role="document">
		
		<div class="modal-content">
			
			<!-- Modal Header -->
			<div class="modal-header">
				
				<!-- Modal Header Close Button -->
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">×</span>
				</button>
				<!-- /Modal Header Close Button -->
				
				<!-- Modal Header Heading -->
				<h4 class="modal-title debug" id="modal_addressLabel">New Package</h4>
				<!-- /Modal Header Heading -->
			
			</div>
			<!-- /Modal Header -->
			
			<!-- Modal Body -->
			<div class="modal-body">
				
				<!-- Modal Body Form -->
				<form id="package_add_modal_form" novalidate="novalidate">
					
					<?php include_once(VIEWS_PATH . "/packages/forms/package_edit_form.phtml"); ?>
				
				</form>
				<!-- ./Modal Body Form -->
			
			</div>
			<!-- /Modal Body -->
		
		</div>
	
	</div>

</div>
<!-- /New Package Modal -->

