<div id="seasonCalendarModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="seasonCalendarModalLabel">
    
    <div class="modal-dialog modal-fullscreen" role="document">
        <div class="calendar-loader" id="calendar_loader">
            <div class="d-flex justify-content-center flex-center">
                <div class="spinner-border" style="width: 3rem; height: 3rem;" role="status">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
        </div>
        
        <div class="modal-content">
            
            <div class="modal-header" id="modalHeader">
                <h4 class="modal-title" id="gridModalLabel">Product Calendar</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            
            <div class="modal-body" id="modalBody">
                
                <div class="container-fluid">
                    
                    <div class="row">
                        
                        <div class="flex-fill col-3 p-1">
                            
                            <!-- Season Filter -->
                            <div class="card card-body mb-2">
                                
                                <div class="form-element">
                                    <label for="calendar_filter_season_id">Seasons:</label>
                                    <select class="form-control" id="calendar_filter_season_id" name="calendar_filter_season_id"></select>
                                    <div id="calendar_filter_season_id-error" class="error w-100 text-center"></div>
                                </div>
                                
                                <div class="row">
                                    
                                    <div class="col-6 text-left">
                                        <button type="button" id="calendar_filter_season_id_assign" name="calendar_filter_season_id_assign" class="btn btn-secondary btn-sm">Assign</button>
                                    </div>
                                    
                                    <div class="col-6 text-right">
                                        <button type="button" id="calendar_filter_season_id_clear" name="calendar_filter_season_id_clear" class="btn btn-primary btn-sm">Clear</button>
                                    </div>
                                
                                </div>
                            
                            </div>
                            <!-- /Season Filter -->
                            
                            <!-- Unit Filter -->
                            <div class="card card-body mb-2">
                                
                                <div class="form-element">
                                    <label for="calendar_filter_unit_id">Units:</label>
                                    <select class="form-control" id="calendar_filter_unit_id" name="calendar_filter_unit_id"></select>
                                    <div id="calendar_filter_unit_id-error" class="error w-100 text-center"></div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-6 text-left">
                                        <button type="button" id="calendar_filter_unit_id_assign" name="calendar_filter_unit_id_assign" class="btn btn-secondary btn-sm">Assign</button>
                                    </div>
                                    <div class="col-6 text-right">
                                        <button type="button" id="calendar_filter_unit_id_clear" name="calendar_filter_unit_id_clear" class="btn btn-primary btn-sm">Clear</button>
                                    </div>
                                </div>
                            
                            </div>
                            <!-- /Unit Filter -->
                            
                            <!-- Profile Filter -->
                            <div class="card card-body mb-2">
                                <div class="form-element">
                                    <label for="calendar_filter_profile_id">Inventory Profiles:</label>
                                    <select class="form-control" id="calendar_filter_profile_id" name="calendar_filter_profile_id"></select>
                                    <div id="calendar_filter_profile_id-error" class="error w-100 text-center"></div>
                                </div>
                                <div class="row">
                                    <div class="col-6 text-left">
                                        <button type="button" id="calendar_filter_profile_id_assign" name="calendar_filter_profile_id_assign" class="btn btn-secondary btn-sm">Assign</button>
                                    </div>
                                    <div class="col-6 text-right">
                                        <button type="button" id="calendar_filter_profile_id_clear" name="calendar_filter_profile_id_clear" class="btn btn-primary btn-sm">Clear</button>
                                    </div>
                                </div>
                            </div>
                            <!-- /Profile Filter -->
                        
                        </div>
                        
                        <div class="flex-fill col-9 p-1">
                            <div class="card card-body mb-2 p-1">
                                <div class="d-flex align-items-center justify-content-between">
                                    
                                    <a type="button" class="btn btn-primary" id="calendar_display_prev_year">
                                        <i class="fas fa-angle-left"></i>
                                    </a>
                                    
                                    <h3 class="h3-responsive mb-0" id="calendar_display_year">
                                        2021
                                    </h3>
                                    
                                    <a type="button" class="btn btn-primary" id="calendar_display_next_year">
                                        <i class="fas fa-angle-right"></i>
                                    </a>
                                
                                </div>
                            </div>
                            
                            <div id="calendar"></div>
                        
                        </div>
                    
                    </div>
                
                </div>
            
            </div>
            
            <div class="modal-footer" id="modalFooter">
                <button type="button" class="btn btn-default waves-effect waves-light" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary waves-effect waves-light">Save changes</button>
            </div>
        
        </div>
    </div>

</div>
