<?php
	if (!isset($page_data)) {
		$page_data = [];
	}
	
	$currency = [];
	if (isset($page_data["types"]["currency"])) {
		$currency = $page_data["types"]["currency"];
	}
	
	$pricing_strategies = [];
	if (isset($page_data["types"]["pricing_strategy_types"])) {
		$pricing_strategies = $page_data["types"]["pricing_strategy_types"];
	}
	
	$categories = [];
	if (isset($page_data["types"]["category"])) {
		$categories = $page_data["types"]["category"];
	}
	
	$rating_types = [];
	if (isset($page_data["types"]["rating_types"])) {
		$rating_types = $page_data["types"]["rating_types"];
	}
	
	$airport_types = [];
	if (isset($page_data["types"]["airport_types"])) {
		$airport_types = $page_data["types"]["airport_types"];
	}
?>

<div data-categoryid="1" class="row">
	<div class="col-12 px-0">
		<div class="card card-body m-1 p-1 border-1 border-light">
			<h5 class="card-title">
				<span>Hotel Fields</span>
			</h5>
			<h6 class="card-subtitle mb-2 text-muted">Additional Product Fields</h6>
			<hr class="ml-3 mr-3 mt-1 mb-3 color-dark"/>
			
			<div class="row">
				
				<div class="col-12 col-md-12">
					<div class="form-element">
						<label for="modal_product_street_1">Street 1:</label>
						<input type="text" id="modal_product_street_1" name="modal_product_street_1" class="form-control"/>
						<div id="modal_product_street_1-error" class="error w-100 text-center"></div>
					</div>
				</div>
				
				<div class="col-12 col-md-12">
					<div class="form-element">
						<label for="modal_product_street_2">Street 2:</label>
						<input type="text" id="modal_product_street_2" name="modal_product_street_2" class="form-control"/>
						<div id="modal_product_street_2-error" class="error w-100 text-center"></div>
					</div>
				</div>
			
			</div>
			
			<div class="row">
				
				<div class="col-12 col-md-8">
					<div class="form-element">
						<label for="modal_product_city">City:</label>
						<input type="text" id="modal_product_city" name="modal_product_city" class="form-control"/>
						<div id="modal_product_city-error" class="error w-100 text-center"></div>
					</div>
				</div>
				
				<div class="col-12 col-md-4">
					<div class="form-element">
						<label for="modal_product_postal_code">Postal:</label>
						<input type="text" id="modal_product_postal_code" name="modal_product_postal_code" class="form-control"/>
						<div id="modal_product_postal_code-error" class="error w-100 text-center"></div>
					</div>
				</div>
			
			</div>
		</div>
	</div>
</div>
