<fieldset id="modal_product_hotel_fields" data-categoryid="1" class="fieldset-dark my-2">
	<legend class="mb-2">
		<h6 class="">Hotel Fields</h6>
	</legend>
	
	<!-- Street 1 -->
	<div class="row">
		
		<!-- Street 1 -->
		<div class="col-12 col-md-12">
			<div id="modal_product_street_1-wrap" class="form-element">
				<label id="modal_product_street_1-label" for="modal_product_street_1">Street 1:</label>
				<input type="text" id="modal_product_street_1" name="modal_product_street_1" class="form-control"/>
				<div id="modal_product_street_1-error" class="error w-100 text-center"></div>
			</div>
		</div>
		<!-- /Street 1 -->
	
	</div>
	<!-- /Street 1 -->
	
	<!-- Street 2 -->
	<div class="row">
		
		<!-- Street 2 -->
		<div class="col-12 col-md-12">
			<div id="modal_product_street_2-wrap" class="form-element">
				<label id="modal_product_street_2-label" for="modal_product_street_2">Street 2:</label>
				<input type="text" id="modal_product_street_2" name="modal_product_street_2" class="form-control"/>
				<div id="modal_product_street_2-error" class="error w-100 text-center"></div>
			</div>
		</div>
		<!-- /Street 2 -->
	
	</div>
	<!-- /Street 2 -->
	
	<!-- City, Province, Country, Postal Code -->
	<div class="row">
		
		<!-- City -->
		<div class="col-12 col-md-8">
			<div id="modal_product_city-wrap" class="form-element">
				<label id="modal_product_city-label" for="modal_product_city">City:</label>
				<input type="search" id="modal_product_city" name="modal_product_city" class="form-control"/>
				<div id="modal_product_city-error" class="error w-100 text-center"></div>
			</div>
		</div>
		<!-- /City -->
		
		<!-- Postal Code -->
		<div class="col-12 col-md-4">
			<div id="modal_product_postal_code-wrap" class="form-element">
				<label id="modal_product_postal_code-label" for="modal_product_postal_code">Postal Code:</label>
				<input type="text" id="modal_product_postal_code" name="modal_product_postal_code" class="form-control"/>
				<div id="modal_product_postal_code-error" class="error w-100 text-center"></div>
			</div>
		</div>
		<!-- /Postal Code -->
	
	</div>
	<!-- /City, Province, Country, Postal Code -->

</fieldset>
