<?php
    if (!isset($page_data)) {
        $page_data = [];
    }
    
    $settings = json_encode($page_data, 1);
    $init = "Product.init($settings)";
    
    $currencies = [];
    $pricing_strategies = [];
    if (isset($page_data["types"]["pricing_strategies"])) {
        $pricing_strategies = $page_data["types"]["pricing_strategies"];
    }
    
    if (isset($page_data["types"]["currency"])) {
        $currencies = $page_data["types"]["currency"];
    }
?>
<!-- /Product Edit Page -->
<section id="product_edit_page" class="section">
    <?php
        include_once(VIEWS_PATH . "/products/forms/product_edit_form.phtml"); ?>
</section>
<!-- /Product Edit Page -->
<script type="text/javascript">
    $(function () {
        Types.init(<?php echo TYPES;?>)
        <?php echo $init;?>
    })
</script>
