<?php
	if (!isset($page_data)) {
		$page_data = [];
	}
	
	$settings = json_encode($page_data["products"], 1);
	$init = "Product.init($settings);";
	if (!defined("COUNTRIES")) {
		define("COUNTRIES", $page_data["types"]["countries"]);
	}
	$currency = [];
	if (isset($page_data["types"]["currency"])) {
		$currency = $page_data["types"]["currency"];
	}
	$airport_types = [];
	if (isset($page_data["types"]["airport_types"])) {
		$airport_types = $page_data["types"]["airport_types"];
	}
?>

<!-- Product Index Page -->
<section id="product_index_page" class="section">
	
	<div class="row gx-1">
		<div class="col-12 p-1">
			<?php include_once(VIEWS_PATH . "/products/forms/product_search.phtml"); ?>
		</div>
	</div>
	
	<div class="row gx-1">
		<div class="col-12 p-1">
			<div class="card card-body">
				<h5 class="card-title font-weight-bold">
					<span>Products</span>
					<a href="javascript:void(0);" id="product_panel_link_product" class="panel_link" aria-hidden="true">Edit</a>
				</h5>
				
				<table id="product_index_table" class="table table-hover dataTable table-striped w-full dtr-inline"></table>
			
			</div>
		</div>
	</div>
	
	<?php /*?>
	<!-- Test Elements -->
	<div id="testElements">
		<div class="row gx-1">
			<?php displayJsonOnPage($airport_types, "Airport Types"); ?>
			<?php //displayJsonOnPage($profiles, "Profiles"); ?>
			<?php //displayJsonOnPage($matrices, "Matrices"); ?>
			<?php //displayJsonOnPage($pricings, "Pricings"); ?>
			<?php //displayJsonOnPage($vendor, "Vendor"); ?>
			<?php //displayJsonOnPage($product, "Product"); ?>
			<?php //displayJsonOnPage($location, "Location"); ?>
		</div>
	</div>
	<!-- /Test Elements -->
	<?php //*/ ?>
</section>
<!-- /Product Index Page -->

<!-- New Product Modal -->
<?php include_once(VIEWS_PATH . "/products/modals/new_product_modal.phtml"); ?>
<!-- /New Product Modal -->

<script type="text/javascript">
	$(function () {
		Types.init(<?php echo TYPES;?>)
		<?php echo $init;?>
	})
</script>
