<?php
    if (!isset($page_data)) {
        $page_data = [];
    }
    
    $settings = json_encode($page_data["products"], 1);
    $init = "Product.init($settings);";
    if (!defined("COUNTRIES")) {
        define("COUNTRIES", $page_data["types"]["countries"]);
    }
    $currency = [];
    if (isset($page_data["types"]["currency"])) {
        $currency = $page_data["types"]["currency"];
    }

?>

<!-- Product Index Page -->
<section id="product_index_page" class="section">
    
    <div class="row gx-1">
        <div class="col-12 p-1">
            <?php include_once(VIEWS_PATH . "/products/forms/product_search.phtml"); ?>
        </div>
    </div>
    
    <div class="row gx-1">
        <div class="col-12 p-1">
            <div class="card card-body">
                <header class="panel-heading">
                    <div class="panel-actions"></div>
                    <h3 class="panel-title">Basic</h3>
                </header>
                <div class="panel-body mx-4 my-4">
                    <table id="product_index_table" class="table table-hover dataTable table-striped w-full dtr-inline">
                        <!--
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>SKU</th>
                            <th>Provider</th>
                            <th>Vendor</th>
                            <th>Location</th>
                            <th>Category</th>
                        </tr>
                        </thead>

                        <tbody>
                        <?php
                            foreach ($page_data["products"] AS $product) {
                                $id = $product["id"];
                                $name = $product["name"];
                                $sku = $product["sku"];
                                $provider = $product["provider"]["name"];
                                $vendor = $product["vendor"]["name"];
                                $location = $product["location"]["display_medium"];
                                $category = $product["category"]["name"];
                                /*
                                echo "
                                    <tr>
                                        <td>$id</td>
                                        <td>$name</td>
                                        <td>$sku</td>
                                        <td>$provider</td>
                                        <td>$vendor</td>
                                        <td>$location</td>
                                        <td>$category</td>
                                    </tr>
                                ";
                                //*/
                            }
                        ?>
                        </tbody>
                        -->
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Product Index Page -->

<!-- New Product Modal -->
<?php include_once(VIEWS_PATH . "/products/modals/new_product_modal.phtml"); ?>
<!-- /New Product Modal -->

<script type="text/javascript">
    $(function () {
        Types.init(<?php echo TYPES;?>)
        <?php echo $init;?>
    })
</script>
