<?php
    $page_data = [];
    if (isset($data)) {
        $page_data = $data;
    }
?>
<section id="view_provider_index">
    <section class="mb-5">

        <div class="row gx-xl-5">

            <div class="col-xl-3 col-md-6 mb-4 mb-xl-0">
                <!-- Card -->
                <a class=" d-flex align-items-center p-4 bg-glass shadow-4-strong rounded-6 text-reset ripple" href="#" data-ripple-color="hsl(0, 0%, 75%)">
                    <div class="p-3 bg-theme rounded-4">
                        <i class="fas fa-users fa-lg text-dark fa-fw"></i>
                    </div>

                    <div class="mx-4">
                        <p class="text-muted mb-2">Users</p>
                        <p class="mb-0">
                            <span class="h5 me-2">14 567 </span>
                            <small class="text-success text-sm"><i class="fas fa-arrow-up fa-sm me-1"></i>13,48%</small>
                        </p>
                    </div>
                </a>
                <!-- Card -->
            </div>

            <div class="col-xl-3 col-md-6 mb-4 mb-xl-0">
                <!-- Card -->
                <a class="
                  d-flex
                  align-items-center
                  p-4
                  bg-glass
                  shadow-4-strong
                  rounded-6
                  text-reset
                  ripple
                  " href="#" data-ripple-color="hsl(0, 0%, 75%)">
                    <div class="p-3 bg-theme rounded-4">
                        <i class="fas fa-file-alt fa-lg text-white fa-fw"></i>
                    </div>

                    <div class="mx-4">
                        <p class="text-muted mb-2">Page views</p>
                        <p class="mb-0">
                            <span class="h5 me-2">51 354</span>
                            <small class="text-success text-sm"><i class="fas fa-arrow-up fa-sm me-1"></i>23,58%</small>
                        </p>
                    </div>
                </a>
                <!-- Card -->
            </div>

            <div class="col-xl-3 col-md-6 mb-4 mb-xl-0">
                <!-- Card -->
                <a class="d-flex align-items-center p-4 bg-glass shadow-4-strong rounded-6 text-reset ripple ripple-surface" href="#" data-ripple-color="hsl(0, 0%, 75%)" style="min-width: 336px;">
                    <div class="p-3 bg-theme rounded-4">
                        <i class="fas fa-clock fa-lg text-white fa-fw"></i>
                    </div>

                    <div class="mx-4">
                        <p class="text-muted mb-2">Average time</p>
                        <p class="mb-0">
                            <span class="h5 me-2">00:04:20</span>
                            <small class="text-danger text-sm"><i class="fas fa-arrow-down fa-sm me-1"></i>23,58%</small>
                        </p>
                    </div>
                </a>
                <!-- Card -->
            </div>

            <div class="col-xl-3 col-md-6 mb-4 mb-xl-0">
                <!-- Card -->
                <a class="
                  d-flex
                  align-items-center
                  p-4
                  bg-glass
                  shadow-4-strong
                  rounded-6
                  text-reset
                  ripple
                  " href="#" data-ripple-color="hsl(0, 0%, 75%)">
                    <div class="p-3 bg-theme rounded-4">
                        <i class="fas fa-sign-out-alt fa-lg text-white fa-fw"></i>
                    </div>

                    <div class="mx-4">
                        <p class="text-muted mb-2">Bounce rate</p>
                        <p class="mb-0">
                            <span class="h5 me-2">32.35% </span>
                            <small class="text-success text-sm"><i class="fas fa-arrow-down fa-sm me-1"></i>23,58%</small>
                        </p>
                    </div>
                </a>
                <!-- Card -->
            </div>
        </div>
    </section>

</section>
