<section id="dashboard_index" class="section">
	
	<div id="productSearch" class="product-search"></div>

</section>

<script type="text/javascript">
	
	function listCallBack (_this) {
		console.group("listCallBack")
		// ----
		
		let el, parentEl, method, id = null
		
		if (_this) {
			el = _this
			parentEl = $(_this).parents("li.list-group-item")[0]
			
			if (parentEl.dataset) {
				id = (parentEl.dataset.id && !isNaN(parseInt(parentEl.dataset.id))) ? parseInt(parentEl.dataset.id) : null
			}
			
			if (_this.dataset) {
				method = (_this.dataset.method) ? _this.dataset.method : null
			}
			
		}
		
		//*
		console.log("id", id)
		console.log("parentEl", parentEl)
		console.log("method", method)
		//*/
		
		// ----
		console.groupEnd()
	}
	
	$(function () {
		//console.log(" *** TEST *** testString.toUCWords()", "dave's test string iS aWeSoMe".toUCWords())
		//console.log(" *** TEST *** testString.toCamelCase()", "this is dAve's test camel case".toCamelCase())
		//console.log(" *** TEST *** testString.toSnakeCase()", "this is a test string".toSnakeCase())
		
		console.group("Types")
		Types.init(<?php echo TYPES;?>)
		console.groupEnd()
		
		let categories = (Types.category) ? Types.category : new Map()
		
		let productSearch = $(".product-search").productSearch({
			categories: categories,
		})
		
	})

</script>

<script type="text/javascript">
	
	// ----
	
	let testData = [
		{
			address: "<p class='m-0 p-0 text-uppercase text-truncate'>65 wind whisper ct</p><p class='m-0 p-0 text-uppercase text-truncate'>77380 Houston Texas</p><p class='m-0 p-0 text-uppercase text-truncate'>United States</p>",
			id: 1,
			name: "Test Hotel 1",
			rating_id: 4,
			sku: "TH00000000001",
			image: "/public/thumbs/cover_placeholder.jpg",
			units: [
				{
					"id": 197,
					"category_id": 1,
					"min_pax": 1,
					"max_pax": 3,
					"min_nights": 1,
					"max_nights": 7,
					"api_id": null,
					"name": "Single room",
					"room_code": "UN-00000000197-SIRO",
					"blurb": null,
					"cover_image": "/public/img/unit_cover_placeholder.jpg",
					"meeting_point": null,
					"time_notes": null,
					"start_time": null,
					"end_time": null,
					"description_short": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla ante eu nulla condimentum ullamcorper. Curabitur euismod, erat id facilisis accumsan, lacus nisl molestie risus, ut dapibus tellus justo id arcu.",
					"description_long": "<div class=\"card-block \">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla ante eu nulla condimentum ullamcorper. Curabitur euismod, erat id facilisis accumsan, lacus nisl molestie risus, ut dapibus tellus justo id arcu.</div>",
					"dates": [
						{
							"date": "2022-12-25",
							"dow": "2022-12-25",
							"dowShort": "Sun",
							"dowLong": "Sunday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-26",
							"dow": "2022-12-26",
							"dowShort": "Mon",
							"dowLong": "Monday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-27",
							"dow": "2022-12-27",
							"dowShort": "Tue",
							"dowLong": "Tuesday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-28",
							"dow": "2022-12-28",
							"dowShort": "Wed",
							"dowLong": "Wednesday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-29",
							"dow": "2022-12-29",
							"dowShort": "Thu",
							"dowLong": "Thursday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
					],
				},
				{
					"id": 199,
					"category_id": 1,
					"min_pax": 1,
					"max_pax": 4,
					"min_nights": 1,
					"max_nights": 7,
					"api_id": null,
					"name": "Single Room Classic With Double Bed",
					"room_code": "UN-00000000199-SRCW",
					"blurb": null,
					"cover_image": "/public/img/unit_cover_placeholder.jpg",
					"meeting_point": null,
					"time_notes": null,
					"start_time": null,
					"end_time": null,
					"description_short": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla ante eu nulla condimentum ullamcorper. Curabitur euismod, erat id facilisis accumsan, lacus nisl molestie risus, ut dapibus tellus justo id arcu.",
					"description_long": "<div class=\"card-block \">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla ante eu nulla condimentum ullamcorper. Curabitur euismod, erat id facilisis accumsan, lacus nisl molestie risus, ut dapibus tellus justo id arcu.</div>",
					"dates": [
						{
							"date": "2022-12-25",
							"dow": "2022-12-25",
							"dowShort": "Sun",
							"dowLong": "Sunday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-26",
							"dow": "2022-12-26",
							"dowShort": "Mon",
							"dowLong": "Monday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-27",
							"dow": "2022-12-27",
							"dowShort": "Tue",
							"dowLong": "Tuesday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-28",
							"dow": "2022-12-28",
							"dowShort": "Wed",
							"dowLong": "Wednesday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-29",
							"dow": "2022-12-29",
							"dowShort": "Thu",
							"dowLong": "Thursday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
					],
				},
				{
					"id": 204,
					"category_id": 1,
					"min_pax": 1,
					"max_pax": 4,
					"min_nights": 1,
					"max_nights": 7,
					"api_id": null,
					"name": "Suite",
					"room_code": "UN-00000000204-SUIT",
					"blurb": null,
					"cover_image": "/public/img/unit_cover_placeholder.jpg",
					"meeting_point": null,
					"time_notes": null,
					"start_time": null,
					"end_time": null,
					"description_short": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla ante eu nulla condimentum ullamcorper. Curabitur euismod, erat id facilisis accumsan, lacus nisl molestie risus, ut dapibus tellus justo id arcu.",
					"description_long": "<div class=\"card-block \">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla ante eu nulla condimentum ullamcorper. Curabitur euismod, erat id facilisis accumsan, lacus nisl molestie risus, ut dapibus tellus justo id arcu.</div>",
					"dates": [
						{
							"date": "2022-12-25",
							"dow": "2022-12-25",
							"dowShort": "Sun",
							"dowLong": "Sunday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-26",
							"dow": "2022-12-26",
							"dowShort": "Mon",
							"dowLong": "Monday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-27",
							"dow": "2022-12-27",
							"dowShort": "Tue",
							"dowLong": "Tuesday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-28",
							"dow": "2022-12-28",
							"dowShort": "Wed",
							"dowLong": "Wednesday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-29",
							"dow": "2022-12-29",
							"dowShort": "Thu",
							"dowLong": "Thursday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
					],
				},
			],
		}, {
			address: "<p class='m-0 p-0 text-uppercase text-truncate'>65 wind whisper ct</p><p class='m-0 p-0 text-uppercase text-truncate'>77380 Houston Texas</p><p class='m-0 p-0 text-uppercase text-truncate'>United States</p>",
			id: 2,
			name: "Test Hotel 2",
			rating_id: 5,
			sku: "TH00000000002",
			image: "/public/thumbs/cover_placeholder.jpg",
			units: [
				{
					"id": 197,
					"category_id": 1,
					"min_pax": 1,
					"max_pax": 3,
					"min_nights": 1,
					"max_nights": 7,
					"api_id": null,
					"name": "Single room",
					"room_code": "UN-00000000197-SIRO",
					"blurb": null,
					"cover_image": "/public/img/unit_cover_placeholder.jpg",
					"meeting_point": null,
					"time_notes": null,
					"start_time": null,
					"end_time": null,
					"description_short": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla ante eu nulla condimentum ullamcorper. Curabitur euismod, erat id facilisis accumsan, lacus nisl molestie risus, ut dapibus tellus justo id arcu.",
					"description_long": "<div class=\"card-block \">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla ante eu nulla condimentum ullamcorper. Curabitur euismod, erat id facilisis accumsan, lacus nisl molestie risus, ut dapibus tellus justo id arcu.</div>",
					"dates": [
						{
							"date": "2022-12-25",
							"dow": "2022-12-25",
							"dowShort": "Sun",
							"dowLong": "Sunday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-26",
							"dow": "2022-12-26",
							"dowShort": "Mon",
							"dowLong": "Monday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-27",
							"dow": "2022-12-27",
							"dowShort": "Tue",
							"dowLong": "Tuesday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-28",
							"dow": "2022-12-28",
							"dowShort": "Wed",
							"dowLong": "Wednesday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-29",
							"dow": "2022-12-29",
							"dowShort": "Thu",
							"dowLong": "Thursday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
					],
				},
				{
					"id": 199,
					"category_id": 1,
					"min_pax": 1,
					"max_pax": 4,
					"min_nights": 1,
					"max_nights": 7,
					"api_id": null,
					"name": "Single Room Classic With Double Bed",
					"room_code": "UN-00000000199-SRCW",
					"blurb": null,
					"cover_image": "/public/img/unit_cover_placeholder.jpg",
					"meeting_point": null,
					"time_notes": null,
					"start_time": null,
					"end_time": null,
					"description_short": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla ante eu nulla condimentum ullamcorper. Curabitur euismod, erat id facilisis accumsan, lacus nisl molestie risus, ut dapibus tellus justo id arcu.",
					"description_long": "<div class=\"card-block \">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla ante eu nulla condimentum ullamcorper. Curabitur euismod, erat id facilisis accumsan, lacus nisl molestie risus, ut dapibus tellus justo id arcu.</div>",
					"dates": [
						{
							"date": "2022-12-25",
							"dow": "2022-12-25",
							"dowShort": "Sun",
							"dowLong": "Sunday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-26",
							"dow": "2022-12-26",
							"dowShort": "Mon",
							"dowLong": "Monday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-27",
							"dow": "2022-12-27",
							"dowShort": "Tue",
							"dowLong": "Tuesday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-28",
							"dow": "2022-12-28",
							"dowShort": "Wed",
							"dowLong": "Wednesday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-29",
							"dow": "2022-12-29",
							"dowShort": "Thu",
							"dowLong": "Thursday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
					],
				},
				{
					"id": 204,
					"category_id": 1,
					"min_pax": 1,
					"max_pax": 4,
					"min_nights": 1,
					"max_nights": 7,
					"api_id": null,
					"name": "Suite",
					"room_code": "UN-00000000204-SUIT",
					"blurb": null,
					"cover_image": "/public/img/unit_cover_placeholder.jpg",
					"meeting_point": null,
					"time_notes": null,
					"start_time": null,
					"end_time": null,
					"description_short": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla ante eu nulla condimentum ullamcorper. Curabitur euismod, erat id facilisis accumsan, lacus nisl molestie risus, ut dapibus tellus justo id arcu.",
					"description_long": "<div class=\"card-block \">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla ante eu nulla condimentum ullamcorper. Curabitur euismod, erat id facilisis accumsan, lacus nisl molestie risus, ut dapibus tellus justo id arcu.</div>",
					"dates": [
						{
							"date": "2022-12-25",
							"dow": "2022-12-25",
							"dowShort": "Sun",
							"dowLong": "Sunday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-26",
							"dow": "2022-12-26",
							"dowShort": "Mon",
							"dowLong": "Monday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-27",
							"dow": "2022-12-27",
							"dowShort": "Tue",
							"dowLong": "Tuesday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-28",
							"dow": "2022-12-28",
							"dowShort": "Wed",
							"dowLong": "Wednesday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
						{
							"date": "2022-12-29",
							"dow": "2022-12-29",
							"dowShort": "Thu",
							"dowLong": "Thursday",
							"available": "Available",
							"cost": 100,
							"margin": 10,
							"price": 110,
						},
					],
				},
			],
		},
	]
</script>
