<section>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    
                    <div style="max-width:160px;max-height:160px;height:160px;width:160px;background: red">
                        &nbsp;
                    </div>
                
                </div>
                
                <div class="col-6">
                    <p class="card-text">Personalize your account with a photo. Your profile photo will appear on apps and devices that use your Microsoft account.</p>
                    <a href="javascript:void(0);" class="btn btn-outline-primary btn-sm">Add a photo</a>
                </div>
                
                <div class="col">
                </div>
            </div>
            
            <div class="row mt-2">
                <div class="col">
                    <p class="form-label">Full Name:</p>
                </div>
                <div class="col-6">
                    <span class="form-edit">David Wingfield</span>
                </div>
                <div class="col">
                    <a href="javascript:void(0);" class="card-link"><span class="button-label">Edit name</span></a>
                </div>
            </div>
        </div>
    </div>
</section>
