<!-- Styles -->
<style>
  main {
    min-height: calc(100vh - 51px);
    min-height: -webkit-calc(100vh - 51px);
    }
</style>
<!-- /Styles -->

<!-- Forgot Password Form -->
<section id="forgot_password" class="container my-5 px-0">
    <div class="card rgba-blue-grey-slight">
        <div class="card-body">

            <!-- Card Heading -->
            <div class="row">
                <div class="col-8 col-sm-8 col-md-8 col-lg-9 mb-1">
                    <h5 class="card-title">
                        <span>Forgot Password</span>
                    </h5>
                    <h6>Enter in your email and we will email your new password.</h6>
                </div>
                <div class="col-4 col-sm-4 col-md-4 col-lg-3 text-right">
                    <img src="/public/img/logos/small_logo.png" class="img-fluid" style="height:4.5rem" alt="small_logo">
                </div>
            </div>
            <hr class="ml-3 mr-3 mt-1 mb-3 color-dark">
            <!-- /Card Heading -->
            
            <form id="forgot_password_form" class="text-center px-5" novalidate>
                
                <!-- Email -->
                <div class="row text-left">
                    <div class="col-12 col-md-3">
                        <label for="forgot_password_form_email">Email:<sup class="text-danger">*</sup></label>
                    </div>
                    
                    <div class="col-12 col-md-9">
                        <div class="form-element">
                            <input type="email" id="forgot_password_form_email" name="forgot_password_form_email" class="form-control" placeholder="E-mail"/>
                            <div id="forgot_password_form_email-error" class="error w-100 text-center">&nbsp;</div>
                        </div>
                    </div>
                
                </div>
                <!-- /Email -->
                
                <div class="text-right">
                    <!-- Cancel Button -->
                    <a href="/" class="btn btn-flat primary-text text-center p-1 mx-0 mb-0 waves-effect waves-light">cancel</a>
                    <!-- Cancel Button -->
                    
                    <!-- Submit button -->
                    <a href="javascript:void(0);" id="forgot_password_form_submit_button" name="forgot_password_form_submit_button" class="btn btn-info btn-sm waves-effect waves-light">
                        Update
                    </a>
                    <!-- /Submit button -->
                </div>
            
            </form>
        </div>
    </div>
</section>
<!-- /Forgot Password Form -->
<script type="text/javascript">

</script>
