<?php
    $page_data = [];
    if (isset($data)) {
        $page_data = $data;
    }
?>
<style>
  div.view {

    }

  #intro {
    background-image: url('/public/img/backgrounds/img40.jpg');
    min-height: 100vh;
    height: 100vh;
    width: 100vw;
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center center;
    z-index: 0;
    }

  /* Height for devices larger than 576px */
  @media (min-width: 992px) {
    #intro {
      margin-top: -58.59px;
      }
    }

</style>
<div id="intro" class="view jarallax" data-jarallax='{"speed": 0.2}'>
    <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

        <section id="login">

            <div class="flex-center flex-column">

                <div class="card card-body">

                    <div class="row">

                        <div class="col-8 col-sm-8 col-md-8 col-lg-9 mb-1">
                            <h2>Login</h2>
                            <p>Please fill in your credentials to log in</p>
                        </div>

                        <div class="col-4 col-sm-4 col-md-4 col-lg-3">
                            <img src="/public/img/logos/small_logo.png" alt="small_logo">
                        </div>

                    </div>

                    <form id="form_login" novalidate>

                        <div class="form-element">
                            <label for="email">Email:<sup>*</sup></label>
                            <input type="email" name="email" id="email" class="form-control" value="tommaso@trips2italy.com" required autocomplete="false"><!--  test@example.com test_ops@trips2italy.com -->
                            <div class="error w-100 text-center" id="email-error">&nbsp;</div>
                        </div>

                        <div class="form-element">
                            <label for="password">Password:<sup>*</sup></label>
                            <input type="password" id="password" name="password" class="form-control" value="6ZaxN2Vzm9NUJT2y" required autocomplete="false"> <!-- 6ZaxN2Vzm9NUJT2y -->
                            <div class="error w-100 text-center" id="password-error">&nbsp;</div>
                        </div>

                        <div class="row">

                            <div class="col-12 text-right">
                                <button type="button" class="btn btn-outline-primary btn-rounded btn-sm waves-effect" id="button_login_register">Register</button>
                                <button type="button" class="btn btn-primary btn-rounded btn-sm waves-effect" id="button_login_submit">Login</button>
                            </div>

                        </div>

                    </form>

                </div>

            </div>

        </section>

    </div>

</div>
<script type="text/javascript">
    window.onload = function () {

    }
</script>

