<?php
    $page_data = [];
    if (isset($data)) {
        $page_data = $data;
    }
?>
<!-- Styles -->
<style>
  body {
    background: #eeeeee;
    }

  main {
    min-height: calc(100vh - 51px);
    min-height: -webkit-calc(100vh - 51px);
    }
</style>
<!-- /Styles -->

<!-- Login Page -->
<section id="login" class="container p-5 my-md-5">

    <!-- Card -->
    <div class="card bg-white rounded-5 shadow-5-strong">
        
        <!-- Card Body -->
        <div class="card-body">
            
            <!-- Card Heading -->
            <div class="row">
                <div class="col-8 col-sm-8 col-md-8 col-lg-9 mb-1">
                    <h5 class="card-title">
                        <span>Login</span>
                    </h5>
                    <h6>Please fill in your credentials to log in.</h6>
                </div>
                <div class="col-4 col-sm-4 col-md-4 col-lg-3 text-right">
                    <img src="/public/img/logos/small_logo.png" class="img-fluid" style="height:4.5rem" alt="small_logo">
                </div>
            </div>
            <hr class="ml-3 mr-3 mt-1 mb-3 color-dark">
            <!-- /Card Heading -->
            
            <!-- Login Form -->
            <form id="form_login" novalidate>
                
                <!-- Email -->
                <div class="form-element">
                    <label for="email">Email:<sup class="field-required">*</sup></label>
                    <input type="email" name="email" id="email" class="form-control" value="tommaso@trips2italy.com" required autocomplete="false"><!--  test@example.com test_ops@trips2italy.com -->
                    <div class="error w-100 text-center" id="email-error">&nbsp;</div>
                </div>
                <!-- /Email -->
                
                <!-- Password -->
                <div class="form-element">
                    <label for="password">Password:<sup class="field-required">*</sup></label>
                    <input type="password" id="password" name="password" class="form-control" value="6ZaxN2Vzm9NUJT2y" required autocomplete="false"> <!-- 6ZaxN2Vzm9NUJT2y -->
                    <div class="error w-100 text-center" id="password-error">&nbsp;</div>
                </div>
                <!-- /Password -->
                
                <div class="form-group clearfix" style=" margin-top:.5rem">
                    <div class="form-check form-check-inline float-left">
                        <input type="checkbox" id="materialInline1" name="remember" class="form-check-input">
                        <label for="materialInline1" class="form-check-label">Remember me</label>
                    </div>
                    
                    <a class="float-right" href="forgot_password">Forgot password?</a>
                
                </div>
                
                <div class="form-group clearfix">
                    <button type="button" class="btn btn-primary btn-block waves-effect" id="button_login_submit">Login</button>
                </div>
            
            </form>
            <!-- /Login Form -->
            
            <!-- Register -->
            <div class="text-center">
                <p>Still no account? Please go to <a href="register">Sign up</a></p>
            </div>
            <!-- /Register -->
        
        </div>
        <!-- /Card Body -->
    
    </div>
    <!-- /Card -->

</section>
<!-- /Login Page -->

<script type="text/javascript">
    window.onload = function () {
        
    }
</script>

