<?php
    $page_title = "Trips2Italy";
    $page_description = "";
    $page_keywords = "Test1, Test2, Test3";
    $page_author = "David Wingfield";
    // ----
    if (defined("PAGE_TITLE")) {
        $page_title = "Trips2Italy - " . PAGE_TITLE;
    }

    if (defined("PAGE_KEYWORDS")) {
        $page_keywords = PAGE_KEYWORDS;
    }

    if (defined("PAGE_DESCRIPTION")) {
        $page_description = PAGE_DESCRIPTION;
    }

    if (defined("PAGE_AUTHOR")) {
        $page_author = PAGE_AUTHOR;
    }

?>
<meta charset="UTF-8">
<meta name="description" content="<?php echo $page_description; ?>">
<meta name="keywords" content="<?php echo $page_keywords; ?>">
<meta name="author" content="<?php echo $page_author; ?>">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<meta name="revisit-after" content="3 month">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/assets/img/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

<title><?php echo $page_title; ?></title>

