<style>
  body.dark {
    background-color: hsl(218, 41%, 15%);
    background-image: radial-gradient(
        650px circle at 0% 0%,
        hsl(218, 41%, 35%) 15%,
        hsl(218, 41%, 30%) 35%,
        hsl(218, 41%, 20%) 75%,
        hsl(218, 41%, 19%) 80%,
        transparent 100%
    ),
    radial-gradient(
        1250px circle at 100% 100%,
        hsl(218, 41%, 45%) 15%,
        hsl(218, 41%, 30%) 35%,
        hsl(218, 41%, 20%) 75%,
        hsl(218, 41%, 19%) 80%,
        transparent 100%
    );
    height: 100vh;
    padding-left: 70px;
    overflow-x: hidden;
    }
  
  
  .bg-glass {
    background: hsla(0, 0%, 0%, .15);
    backdrop-filter: blur(30px);
    }

  .bg-theme {
    background-color: hsla(60, 7%, 97%, 1);
    }

  .rounded {
    border-radius: .25rem !important
    }

  .rounded-0 {
    border-radius: 0 !important
    }

  .rounded-1 {
    border-radius: .2rem !important
    }

  .rounded-2 {
    border-radius: .25rem !important
    }

  .rounded-3 {
    border-radius: .3rem !important
    }

  .rounded-circle {
    border-radius: 50% !important
    }

  .rounded-pill {
    border-radius: 50rem !important
    }

  .rounded-4 {
    border-radius: .375rem !important
    }

  .rounded-5 {
    border-radius: .5rem !important
    }

  .rounded-6 {
    border-radius: .75rem !important
    }

  .rounded-7 {
    border-radius: 1rem !important
    }

  .rounded-8 {
    border-radius: 1.25rem !important
    }

  .rounded-9 {
    border-radius: 1.5rem !important
    }


  .ripple-surface {
    position: relative;
    overflow: hidden;
    display: inline-block;
    vertical-align: bottom;
    }

  .text-sm {
    font-size: .85rem;
    }
</style>
