<?php
    $date = new DateTime();
?>
<script type="text/javascript" src="/public/js/jquery-3.4.1.min.js"></script>

<link rel="stylesheet" href="/public/font/fontawesome/v5.15.3/css/all.css"/>
<link rel="stylesheet" href="/public/css/bootstrap.css"/>
<link rel="stylesheet" href="/public/vendor/autocomplete/autocomplete.css"/>
<link rel="stylesheet" href="/public/vendor/colorpicker/bootstrap-colorpicker.min.css"/>
<link rel="stylesheet" href="/public/vendor/select2/select2.css"/>
<link rel="stylesheet" href="/public/vendor/fancybox/jquery.fancybox.css"/>
<link rel="stylesheet" href="/public/vendor/fullcalendar/fullcalendar.min.css"/>
<link rel="stylesheet" href="/public/css/style.css?v=<?php echo $date->format("U"); ?>">
