<?php
	$date = new DateTime();
?>
<!-- -->

<!-- -->
<script type="text/javascript" src="/public/js/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="/public/vendor/moment/v.2.29.1/moment.min.js"></script>
<script type="text/javascript" src="/public/vendor/fullcalendar/v3.10.5/fullcalendar.js"></script>
<script type="text/javascript" src="https://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=7.0"></script>

<!-- -->

<!-- -->
<link rel="stylesheet" href="/public/vendor/pickr/v1.8.2/themes/classic.min.css"/>
<link rel="stylesheet" href="/public/vendor/pickr/v1.8.2/themes/nano.min.css"/>
<link rel="stylesheet" href="/public/vendor/pickr/v1.8.2/themes/monolith.min.css"/>

<link rel="stylesheet" href="/public/vendor/prism/v1.25.0/prism.css"/>
<!-- -->

<!-- -->
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css" integrity="sha512-KXkS7cFeWpYwcoXxyfOumLyRGXMp7BTMTjwrgjMg0+hls4thG2JGzRgQtRfnAuKTn2KWTDZX4UdPg+xTs8k80Q==" crossorigin="anonymous" referrerpolicy="no-referrer"/>-->
<link rel="stylesheet" href="/public/vendor/fullcalendar/style.css"/>
<link rel="stylesheet" type="text/css" href="https://unpkg.com/js-year-calendar@latest/dist/js-year-calendar.min.css"/>
<!-- -->

<!-- -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/public/font/fontawesome/v5.15.3/css/all.css"/>
<link rel="stylesheet" href="/public/css/bootstrap.css"/>
<!-- -->

<!-- -->
<link rel="stylesheet" href="/public/vendor/datepicker/v1.9.0/css/bootstrap-datepicker.css"/>
<link rel="stylesheet" href="/public/vendor/autocomplete/autocomplete.css"/>
<link rel="stylesheet" href="/public/vendor/dropify/css/dropify.min.css"/>
<link rel="stylesheet" href="/public/vendor/colorpicker/bootstrap-colorpicker.min.css"/>
<link rel="stylesheet" href="/public/vendor/select2/select2.css"/>
<link rel="stylesheet" href="/public/vendor/fancybox/jquery.fancybox.css"/>
<link rel="stylesheet" href="/public/vendor/context-menu/v2.0.0/jquery.contextMenu.min.css"/>
<!-- -->

<!-- -->
<link rel="stylesheet" href="/public/css/style.css?v=<?php
	echo $date->format("U"); ?>">
<link rel="stylesheet" href="/public/css/variant.css?v=<?php
	echo $date->format("U"); ?>">
<!-- -->

