<style>
  body.dark {
    background-color: hsl(218, 41%, 15%);
    background-image: radial-gradient(
        650px circle at 0% 0%,
        hsl(218, 41%, 35%) 15%,
        hsl(218, 41%, 30%) 35%,
        hsl(218, 41%, 20%) 75%,
        hsl(218, 41%, 19%) 80%,
        transparent 100%
    ),
    radial-gradient(
        1250px circle at 100% 100%,
        hsl(218, 41%, 45%) 15%,
        hsl(218, 41%, 30%) 35%,
        hsl(218, 41%, 20%) 75%,
        hsl(218, 41%, 19%) 80%,
        transparent 100%
    );
    height: 100vh;
    padding-left: 70px;
    overflow-x: hidden;
    }
  
  
  .bg-glass {
    background: hsla(0, 0%, 0%, .15);
    backdrop-filter: blur(30px);
    }
  
  .bg-theme {
    background-color: hsla(60, 7%, 97%, 1);
    }
  
  .rounded {
    border-radius: .25rem !important
    }
  
  .rounded-0 {
    border-radius: 0 !important
    }
  
  .rounded-1 {
    border-radius: .2rem !important
    }
  
  .rounded-2 {
    border-radius: .25rem !important
    }
  
  .rounded-3 {
    border-radius: .3rem !important
    }
  
  .rounded-circle {
    border-radius: 50% !important
    }
  
  .rounded-pill {
    border-radius: 50rem !important
    }
  
  .rounded-4 {
    border-radius: .375rem !important
    }
  
  .rounded-5 {
    border-radius: .5rem !important
    }
  
  .rounded-6 {
    border-radius: .75rem !important
    }
  
  .rounded-7 {
    border-radius: 1rem !important
    }
  
  .rounded-8 {
    border-radius: 1.25rem !important
    }
  
  .rounded-9 {
    border-radius: 1.5rem !important
    }
  
  
  .ripple-surface {
    position: relative;
    overflow: hidden;
    display: inline-block;
    vertical-align: bottom;
    }
  
  .text-sm {
    font-size: .85rem;
    }
  
  
  .page-header-actions {
    position: absolute;
    top: 1rem;
    right: 2rem;
    margin: auto;
    transform: translateY(-1rem);
    }
  
  
  .card-block {
    position: relative;
    -webkit-box-flex: 1;
    -webkit-flex: 1 1 auto;
    -ms-flex: 1 1 auto;
    flex: 1 1 auto;
    padding: 1.429rem
    }
  
  .font-weight-unset {
    font-weight: unset !important
    }
  
  .font-weight-100 {
    font-weight: 100 !important
    }
  
  .font-weight-200 {
    font-weight: 200 !important
    }
  
  .font-weight-300 {
    font-weight: 300 !important
    }
  
  .font-weight-400 {
    font-weight: 400 !important
    }
  
  .font-weight-500 {
    font-weight: 500 !important
    }
  
  .font-weight-600 {
    font-weight: 600 !important
    }
  
  .font-weight-700 {
    font-weight: 700 !important
    }
  
  .font-weight-800 {
    font-weight: 800 !important
    }
  
  .font-weight-900 {
    font-weight: 900 !important
    }
  
  .font-weight-light {
    font-weight: 100 !important
    }
  
  .font-weight-normal {
    font-weight: 300 !important
    }
  
  .font-weight-medium {
    font-weight: 400 !important
    }
  
  .font-weight-bold {
    font-weight: 500 !important
    }
  
  .font-size-0 {
    font-size: 0 !important
    }
  
  .font-size-10 {
    font-size: 10px !important
    }
  
  .font-size-12 {
    font-size: 12px !important
    }
  
  .font-size-14 {
    font-size: 14px !important
    }
  
  .font-size-16 {
    font-size: 16px !important
    }
  
  .font-size-18 {
    font-size: 18px !important
    }
  
  .font-size-20 {
    font-size: 20px !important
    }
  
  .font-size-24 {
    font-size: 24px !important
    }
  
  .font-size-26 {
    font-size: 26px !important
    }
  
  .font-size-30 {
    font-size: 30px !important
    }
  
  .font-size-40 {
    font-size: 40px !important
    }
  
  .font-size-50 {
    font-size: 50px !important
    }
  
  .font-size-60 {
    font-size: 60px !important
    }
  
  .font-size-70 {
    font-size: 70px !important
    }
  
  .font-size-80 {
    font-size: 80px !important
    }
  
  .media .media {
    padding-bottom: 0;
    border-bottom: none
    }
  
  .media-body {
    overflow: auto
    }
  
  .media-meta {
    margin-bottom: 3px;
    font-size: .858rem;
    color: #a3afb7
    }
  
  .media-list {
    padding-left: 0;
    list-style: none
    }
  
  .media-list > .media {
    margin-top: 15px
    }
  
  .media-list > .media:first-child {
    margin-top: 0
    }
  
  @media (min-width: 768px) {
    .media-body {
      overflow: hidden
      }
    
    .media .media {
      margin-left: 0
      }
    }
  
  @media (max-width: 479px) {
    .media {
      -webkit-box-orient: vertical;
      -webkit-box-direction: normal;
      -webkit-flex-direction: column;
      -ms-flex-direction: column;
      flex-direction: column
      }
    
    .media > div:first-child {
      margin-bottom: 5px
      }
    
    .media .media {
      padding-left: 15px
      }
    }
  
  .avatar {
    position: relative;
    display: inline-block;
    width: 40px;
    white-space: nowrap;
    vertical-align: bottom;
    border-radius: 1000px
    }
  
  .avatar i {
    position: absolute;
    right: 0;
    bottom: 0;
    width: 10px;
    height: 10px;
    border: 2px solid #fff;
    border-radius: 100%
    }
  
  .avatar img {
    width: 100%;
    max-width: 100%;
    height: auto;
    border: 0 none;
    border-radius: 1000px
    }
  
  .avatar-online i {
    background-color: #11c26d
    }
  
  .avatar-off i {
    background-color: #526069
    }
  
  .avatar-busy i {
    background-color: #eb6709
    }
  
  .avatar-away i {
    background-color: #ff4c52
    }
  
  .avatar-100 {
    width: 100px
    }
  
  .avatar-100 i {
    width: 20px;
    height: 20px
    }
  
  .avatar-lg {
    width: 50px
    }
  
  .avatar-lg i {
    width: 12px;
    height: 12px
    }
  
  .avatar-sm {
    width: 30px
    }
  
  .avatar-sm i {
    width: 8px;
    height: 8px
    }
  
  .avatar-xs {
    width: 20px
    }
  
  .avatar-xs i {
    width: 7px;
    height: 7px
    }
  
  .status {
    display: block;
    width: 10px;
    height: 10px;
    border: 2px solid #fff;
    border-radius: 100%
    }
  
  .status-online {
    background-color: #11c26d
    }
  
  .status-off {
    background-color: #526069
    }
  
  .status-busy {
    background-color: #eb6709
    }
  
  .status-away {
    background-color: #ff4c52
    }
  
  .status-lg {
    width: 14px;
    height: 14px
    }
  
  .status-md {
    width: 10px;
    height: 10px
    }
  
  .status-sm {
    width: 8px;
    height: 8px
    }
  
  .status-xs {
    width: 7px;
    height: 7px
    }
  
  .project-title:hover a.btn-edit {
    display: inline-block;
    }
  
  .card .card-body h1, .card .card-body h2, .card .card-body h3, .card .card-body h4, .card .card-body h5, .card .card-body h6 {
    font-weight: 400
    }
  
  .card .card-body .card-title a {
    transition: .2s ease-in-out
    }
  
  .card .card-body .card-title a:hover {
    transition: .2s ease-in-out
    }
  
  .h1 .icon:first-child,
  .h2 .icon:first-child,
  .h3 .icon:first-child,
  .h4 .icon:first-child,
  .h5 .icon:first-child,
  .h6 .icon:first-child,
  h1 .icon:first-child,
  h2 .icon:first-child,
  h3 .icon:first-child,
  h4 .icon:first-child,
  h5 .icon:first-child,
  h6 .icon:first-child {
    margin-right: 0.5em;
    }
  
  h4.project-title .btn-edit {
    display: none;
    padding: 0;
    margin-left: 5px;
    }
  
  .btn-pure.btn-default {
    color: #a3afb7;
    }
  
  .btn-default:not([disabled]):not(.disabled).active.focus, .btn-default:not([disabled]):not(.disabled).active.hover, .btn-default:not([disabled]):not(.disabled).active:focus, .btn-default:not([disabled]):not(.disabled).active:hover, .btn-default:not([disabled]):not(.disabled):active.focus, .btn-default:not([disabled]):not(.disabled):active.hover, .btn-default:not([disabled]):not(.disabled):active:focus, .btn-default:not([disabled]):not(.disabled):active:hover, .open > .btn-default.dropdown-toggle.focus, .open > .btn-default.dropdown-toggle.hover, .open > .btn-default.dropdown-toggle:focus, .open > .btn-default.dropdown-toggle:hover, .show > .btn-default.dropdown-toggle.focus, .show > .btn-default.dropdown-toggle.hover, .show > .btn-default.dropdown-toggle:focus, .show > .btn-default.dropdown-toggle:hover {
    background-color: #ccd5db;
    border-color: #ccd5db
    }
  
  .page-project .btn-pure.btn-edit:focus, .page-project .btn-pure.btn-edit:hover {
    color: #11c26d;
    }
  
  .form-label {
    -webkit-font-smoothing: antialiased;
    font-size: 14px;
    font-weight: 400;
    color: rgb(96, 94, 92);
    margin-bottom: 0;
    }
  
  span.form-edit {
    font-size: 14px;
    font-weight: 600;
    color: rgb(50, 49, 48);
    }
  
  .button-label {
    text-align: center;
    cursor: pointer;
    padding: 0px 4px;
    border-radius: 2px;
    height: 40px;
    color: rgb(0, 111, 201);
    margin: 0px 4px;
    font-size: 14px;
    }
  
  div.panel > div.panel-heading {
    border-top-left-radius: 0.214rem;
    border-top-right-radius: 0.214rem;
    position: relative;
    padding: 0;
    border-bottom: 1px solid transparent;
    }
  
  div.panel > div.panel-body {
    padding: 0 30px 30px;
    position: relative;
    min-height: auto;
    }
  
  div.panel > div.panel-heading > h3.panel-title {
    display: block;
    padding: 20px 30px;
    margin-top: 0;
    margin-bottom: 0;
    font-size: 18px;
    color: #37474f;
    }
  
  div.panel > div.panel-heading > ul.panel-actions {
    position: absolute;
    top: 50%;
    right: 30px;
    list-style: none;
    z-index: 1;
    margin: auto;
    -webkit-transform: translate(0, -50%);
    -ms-transform: translate(0, -50%);
    -o-transform: translate(0, -50%);
    transform: translate(0, -50%);
    }
  
  div.panel > div.panel-heading > ul.panel-actions.panel-actions-keep > li > a {
    color: #3e8ef7;
    text-decoration: none;
    background-color: transparent;
    -webkit-text-decoration-skip: objects;
    }
  
  label.inline-label {
    -webkit-font-smoothing: antialiased;
    font-size: 14px;
    font-weight: 400;
    color: rgb(96, 94, 92);
    display: inline;
    }
  
  span.inline-value {
    -webkit-font-smoothing: antialiased;
    font-size: 14px;
    font-weight: 600;
    color: rgb(50, 49, 48);
    display: inline;
    }
  
  span.inline-description {
    -webkit-font-smoothing: antialiased;
    font-size: 14px;
    font-weight: 400;
    color: rgb(96, 94, 92);
    display: inline;
    }
  
  
  .card .action-element {
    position: absolute;
    right: 0;
    font-size: .85rem;
    font-weight: 500;
    vertical-align: bottom;
    margin-bottom: 0.75rem;
    line-height: 1.2;
    }
  
  .card .card-body h6 i {
    font-size: 14px;
    height: 100%;
    width: fit-content;
    vertical-align: middle;
    text-align: center;
    line-height: 1;
    }
  
  .card .card-body h5.card-title span {
    font-weight: 400;
    }
  
  .card .card-body h6 span {
    font-size: 14px;
    height: 100%;
    line-height: 1.2;
    vertical-align: middle;
    text-align: center;
    font-weight: 300;
    }
  
  
  .oneStar {
    color: #44370f;
    }
  
  .twoStars {
    color: #96781e;
    }
  
  .threeStars {
    
    color: #e2b52e;
    }
  
  .fourStars {
    color: #f1ba12;
    }
  
  .fiveStars {
    color: #f3cb06;
    }
  
  #rating.empty-stars > i {
    margin-left: 1rem;
    margin-bottom: .5rem
    }
  
  .modal {
    position: fixed;
    top: 0;
    left: 0;
    z-index: 1050;
    display: none;
    width: 100vw;
    height: 100vh;
    overflow: hidden;
    outline: 0;
    }
  
  .bootstrap-maxlength.badge {
    margin-top: .5rem
    }
  
  
  .page-project .card-block {
    padding: 25px;
    border-top: 1px solid #e4eaec
    }
  
  .page-project .card-block:first-child {
    border-top: none;
    }
  
  .page-project .card .card-block + .card-block {
    padding: 25px;
    }
  
  .page-project .btn-pure.btn-trash:focus, .page-project .btn-pure.btn-trash:hover {
    color: #ff4c52;
    }
  
  .page-project .btn-pure.btn-edit:focus, .page-project .btn-pure.btn-edit:hover {
    color: #11c26d;
    }
  
  .page-project .ui-helper-hidden-accessible {
    display: none
    }
  
  div.excerpt {
    margin-top: 3rem;
    padding-left: 1rem;
    padding-right: 1rem;
    }
  
  span.badge {
    display: inline-block;
    padding: .25em 0.4em;
    font-size: 12px;
    font-weight: 700;
    line-height: 1.3;
    text-align: center;
    white-space: nowrap;
    vertical-align: baseline;
    border-radius: 0.125rem;
    transition: color .15s ease-in-out, background-color .15s ease-in-out, border-color .15s ease-in-out, box-shadow .15s ease-in-out;
    
    }
  
  
  #toast-container > div.md-toast.md-toast-success {
    font-weight: 400;
    color: #0a070d !important;
    background-color: #8cd8b1 !important;
    border-color: #016733 !important;
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAD3SURBVEhL7ZOxCsIwGIRTF0EQZx0d9BGcdXH1UV2Lg7MPIOigo85SEJz07k9aiIY0fy1OfnDkT5reNWli/vyUXrc/gDbQHppyLJMnLUBzNDk0kwFjLtCilYCAecm544rGRMxJ8dUKasyP0LxxQIr5/VFcZYsweQLxz/ME8MUoqebsZDRHu4VGHAA7aIkJN9v10ZgTBpzQjm23IhiiNSfcosKWHjTInaHQxJxwBUO03CK5eW/ISmypNydyihJCiNqcVMe0JiRErTnx7oEiJMmcfFy0hJBkcxK8yZEQlXkUhkAH6OnEmsEqgisocYZr2zOrVr78j48xLydnabp09vnmAAAAAElFTkSuQmCC) !important;
    }
  
  #toast-container > div.md-toast.md-toast-success > button.md-toast-close-button {
    color: #0a070d !important;
    }
  
  #toast-container > div.md-toast.md-toast-success > div.md-toast-title {
    color: #013C22 !important;
    font-weight: 500
    }
  
  #toast-container > div.md-toast.md-toast-warning {
    font-weight: 400;
    color: #0a070d !important;
    background-color: #ebbf7a !important;
    border-color: #442a00 !important;
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAHxSURBVEhLtZQ7LARRGIWHjRCVhgKNRhQSOq1SVBJqFVEvDY1sKOgoFCQKtahXqaUSicSjUKGgQCSyXuE7M2fXjB3W80vO3jvnf9y7dx7Bf1PlsSL1tZlWhsnoKpi/u38+9fz30DyDdtGLpXnG4U+p9liJEdSNzizNR1FFKh4RO21gOEaNaEgebKBL1M5RXYfOT2GBBR/Lli15W/YWbP0MGnSgB/SEumzL77KnWIft70NxHmmny7ZKyHMsb+t7UNjvBldI559AnmPK6bf9NSioQYcuztobRuvWsL0sUo5ya+R9iVjhQbGQccWeFB6ZYkg5pY28p+w9IFHHMR1dBRM8ho+e33gU4dyxcc1h2rUJ0l60WaRnP0+D+A0sW0CQs8mgPNWoNkFiAXagR1FvrXY2IS9G6gJG/0I1I+5R4v0/WET6xiyxs8PQeUOfiCLnHkPIPWJYQqpVj3JYeRDpZl0g/d0EeNVowEq7dw1IteoxaDsCow6dODhmOwF+znEpZzuBah1Xrzp5xZ3oDNvQHlqVkUKPRxGfx1GteqhX9HSxUjO69cq9oZkCsT7nSX22y1APpF7Ka5axZkOf4E8hp1by5Yeol3uuVfFTwFPRDNpXwh/QifSyFrTANpOPzvS37GiBFiZTqCm0/o4LNBdN/40geAVspYnJSOxEwAAAAABJRU5ErkJggg==) !important;
    }
  
  #toast-container > div.md-toast.md-toast-warning > button.md-toast-close-button {
    color: #0a070d !important;
    }
  
  #toast-container > div.md-toast.md-toast-warning > div.md-toast-title {
    color: #442a00 !important;
    font-weight: 500
    }
  
  #toast-container > div.md-toast.md-toast-error {
    color: #0a070d !important;
    font-weight: 400;
    background-color: #ff7d73 !important;
    border-color: #7b0900 !important;
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAIgSURBVEhLtZbPKwVRFMevJ72oZynFn8CGlYUFC7HxHxBL8g/YWWFP2SmUP4GyYCGsKOEfECU7kZL8+H5mzn3dMXfGU963Pt075557zryZe868FveLOqq1bg0jol90YZMexbU4fH17fkgsBSpMoMDDGhbFmGjFFtGHOBArSnScWH4ol0CBaxrWxLTw68/iXNwnV871iAHRmVw59yV2xIIS4RsXj0Ncii/jVEyKNnOpC5ut4eP92csjzUsLNXPA8U3Mi0beUYv5sscn4SlkJeOWOeA4buaGxR7bS4wtM6eSYdgWYN7MGcl+EvicmDkj9tr6p+CQuEqykp4WdCY20mlOVRtROA/FXmLwaJOYFWXipXAU0apOAScipvB0RE+K7V1Nr9wYsfkFo4JzzqZ9UaQXG1HxUUxjsE7MERL0CXSuO3i3eUxh0DBZRhbjIr1y/STw5e+LqEhhgrJfgO5s7PIvuRH9JUFdJKBxIcq/TLtiyWBepl4bH0lAV0SDeuu5lhDoRtwazKOyGPQpdEWCQ0FXpLwnRJGozk0jW6lZEYNYxDzCQNZ9QQXSuKL9R/Yn84EnM2fUnvYl3/z2sPmXvGzjkJhLpzmFNRKtF90Ze4lBwa1gq0sZS5udbFUxI2aZm7ku9oh4s0MyNrddIy38+wcnd4dyIPu6mBJ+ncKi/H2FUjODIrzTbZH7ZBY+AiVqzkf/p+wnx/62XIkjBS752+LcNyPJsVnMbZ3GAAAAAElFTkSuQmCC) !important;
    }
  
  #toast-container > div.md-toast.md-toast-error > button.md-toast-close-button {
    color: #0a070d !important;
    }
  
  #toast-container > div.md-toast.md-toast-error > div.md-toast-title {
    color: #330300 !important;
    font-weight: 500
    }

</style>
