<style>
	td.fc-more-cell {
		
		}
	
	.modal-header .close {
		order: 2;
		padding: 0;
		margin: .3rem -1rem -1rem auto;
		cursor: pointer;
		background: 0 0;
		border: 0;
		-webkit-appearance: none;
		float: right;
		font-size: 1.5rem;
		font-weight: 500;
		line-height: 1;
		color: #37474f;
		text-shadow: none;
		opacity: .5;
		}
	
	#modalHeader {
		border-bottom: solid 1px #ddd;
		}
	
	.md-form.md-outline.form-sm input.cost {
		padding-left: 1.2rem !important;
		}
	
	.select2-container--default .select2-selection--single {
		background-color: #fff;
		border: 1px solid #ced4da;
		border-radius: 0.25rem;
		color: #495057;
		}
	
	section.card.card-body,
	form.card.card-body {
		border: 1px solid rgba(0, 0, 0, 0.125);
		border-radius: 0.125rem;
		box-shadow: none;
		}
	
	.form-control {
		background-color: #fff !important;
		}
	
	.page-content {
		padding: 1rem 1rem;
		height: 100%;
		min-height: 88vh;
		}
	
	.md-accordion .card:first-of-type, .md-accordion .card:not(:first-of-type):not(:last-of-type) {
		border-bottom: none;
		}
	
	.form-element label {
		font-weight: 400;
		}
	
	.md-form.md-outline.form-sm {
		margin-top: 0.5rem;
		margin-bottom: 0;
		}
	
	.md-form.md-outline.form-sm input {
		font-size: .9rem;
		padding-top: 0.5rem;
		padding-bottom: 0.4rem;
		}
	
	.md-form.md-outline.form-sm label.active {
		font-size: .95rem;
		}
	
	th.disabled, td.disabled, div.disabled {
		color: #757575;
		background-color: #e9ecef !important;
		opacity: 1;
		}
	
	.md-form.md-outline .form-control {
		padding: 0.65rem 0.75rem;
		}
	
	.md-form.md-outline.form-sm label {
		font-size: .95rem;
		transform: translateY(6px);
		
		}
	
	.btn.btn-sm.editRow {
		padding: 0.5rem .6rem !important;
		font-size: .64rem !important;
		}
	
	span.table-variant-title {
		font-weight: 500;
		}
	
	.spinner-border-sm {
		width: 0.95rem;
		height: 0.951rem;
		border-width: 0.3em;
		margin-right: .5rem;
		}
	
	.md-form .input-prefix.active {
		color: #ff884f;
		}
	
	table.table-sm > thead > tr > th {
		vertical-align: middle;
		text-align: center;
		font-weight: 500;
		padding: 0.25rem !important;
		}
	
	.md-form.input-with-pre-icon .input-prefix {
		left: 0.2rem;
		right: initial;
		font-size: .95rem;
		height: 0.95rem;
		width: 0.95rem;
		}
	
	.md-form.input-with-post-icon .input-prefix {
		right: 0.2rem;
		left: initial;
		font-size: .95rem;
		height: 0.95rem;
		width: 0.95rem;
		}
	
	.md-form.input-with-pre-icon label {
		left: 1.3rem;
		right: initial;
		}
	
	.btn.btn-sm.editRow i.far {
		font-weight: 400;
		font-size: inherit;
		-moz-osx-font-smoothing: grayscale;
		-webkit-font-smoothing: antialiased;
		display: inline-block;
		font-style: normal;
		font-variant: normal;
		text-rendering: auto;
		line-height: 1.25;
		}
	
	#product_edit_tabs .badge {
		position: absolute;
		margin-top: -4px;
		margin-left: -4px;
		padding: 0;
		font-size: 12px;
		height: 14px;
		width: 14px;
		font-weight: 500;
		line-height: 14px;
		vertical-align: middle;
		text-align: center;
		color: rgb(255, 255, 255) !important;
		background-color: #ff3547 !important;
		}
	
	span.badge.tab-badge {
		position: absolute;
		font-size: .6rem;
		margin-top: 0;
		margin-left: -0.3rem;
		padding: 0.2em 0.45em;
		height: 0.8rem;
		font-weight: 700;
		line-height: 1;
		text-align: center;
		white-space: nowrap;
		width: 0.8rem;
		}
	
	.form-control:disabled, .form-control[readonly] {
		background-color: #e9ecef !important;
		opacity: 1;
		}
	
	.btn.btn-md.btn-outline-danger {
		background-color: #fff !important;
		}
	
	#mdb-preloader {
		background-color: rgba(0, 0, 0, .70);
		}
	
	.double-nav a {
		font-size: 1rem;
		
		}
	
	.was-validated .custom-select:invalid, .custom-select.is-invalid, .form-control.is-invalid {
		background-position: right calc(01.2em + 0rem) center;
		}
	
	#userDropdown {
		padding: 0.5rem 1rem;
		cursor: pointer;
		}
	
	#userDropdown span {
		line-height: 1.7;
		vertical-align: middle;
		height: 100%;
		}
	
	#userDropdown i {
		width: 1rem;
		line-height: 1.7;
		vertical-align: middle;
		height: 100%;
		}
	
	#userDropdown::after {
		right: 0;
		top: 1.1rem;
		}
	
	.input-group-append button.btn-outline-warning {
		background: #fff !important;
		}
	
	.modal-fullscreen {
		width: 100vw;
		max-width: none;
		height: 100%;
		margin: 0
		}
	
	.modal-fullscreen .modal-content {
		height: 100%;
		border: 0;
		border-radius: 0
		}
	
	.modal-fullscreen .modal-header {
		border-radius: 0
		}
	
	.modal-fullscreen .modal-body {
		overflow-y: auto
		}
	
	.modal-fullscreen .modal-footer {
		border-radius: 0
		}
	
	@media (max-width: 575.98px) {
		.modal-fullscreen-sm-down {
			width: 100vw;
			max-width: none;
			height: 100%;
			margin: 0
			}
		
		.modal-fullscreen-sm-down .modal-content {
			height: 100%;
			border: 0;
			border-radius: 0
			}
		
		.modal-fullscreen-sm-down .modal-header {
			border-radius: 0
			}
		
		.modal-fullscreen-sm-down .modal-body {
			overflow-y: auto
			}
		
		.modal-fullscreen-sm-down .modal-footer {
			border-radius: 0
			}
		}
	
	@media (max-width: 767.98px) {
		.modal-fullscreen-md-down {
			width: 100vw;
			max-width: none;
			height: 100%;
			margin: 0
			}
		
		.modal-fullscreen-md-down .modal-content {
			height: 100%;
			border: 0;
			border-radius: 0
			}
		
		.modal-fullscreen-md-down .modal-header {
			border-radius: 0
			}
		
		.modal-fullscreen-md-down .modal-body {
			overflow-y: auto
			}
		
		.modal-fullscreen-md-down .modal-footer {
			border-radius: 0
			}
		}
	
	@media (max-width: 991.98px) {
		.modal-fullscreen-lg-down {
			width: 100vw;
			max-width: none;
			height: 100%;
			margin: 0
			}
		
		.modal-fullscreen-lg-down .modal-content {
			height: 100%;
			border: 0;
			border-radius: 0
			}
		
		.modal-fullscreen-lg-down .modal-header {
			border-radius: 0
			}
		
		.modal-fullscreen-lg-down .modal-body {
			overflow-y: auto
			}
		
		.modal-fullscreen-lg-down .modal-footer {
			border-radius: 0
			}
		}
	
	@media (max-width: 1199.98px) {
		.modal-fullscreen-xl-down {
			width: 100vw;
			max-width: none;
			height: 100%;
			margin: 0
			}
		
		.modal-fullscreen-xl-down .modal-content {
			height: 100%;
			border: 0;
			border-radius: 0
			}
		
		.modal-fullscreen-xl-down .modal-header {
			border-radius: 0
			}
		
		.modal-fullscreen-xl-down .modal-body {
			overflow-y: auto
			}
		
		.modal-fullscreen-xl-down .modal-footer {
			border-radius: 0
			}
		}
	
	@media (max-width: 1399.98px) {
		.modal-fullscreen-xxl-down {
			width: 100vw;
			max-width: none;
			height: 100%;
			margin: 0
			}
		
		.modal-fullscreen-xxl-down .modal-content {
			height: 100%;
			border: 0;
			border-radius: 0
			}
		
		.modal-fullscreen-xxl-down .modal-header {
			border-radius: 0
			}
		
		.modal-fullscreen-xxl-down .modal-body {
			overflow-y: auto
			}
		
		.modal-fullscreen-xxl-down .modal-footer {
			border-radius: 0
			}
		}
	
	
	body.dark {
		background-color: hsl(218, 41%, 15%);
		background-image: radial-gradient(
			650px circle at 0% 0%,
			hsl(218, 41%, 35%) 15%,
			hsl(218, 41%, 30%) 35%,
			hsl(218, 41%, 20%) 75%,
			hsl(218, 41%, 19%) 80%,
			transparent 100%
		),
		radial-gradient(
			1250px circle at 100% 100%,
			hsl(218, 41%, 45%) 15%,
			hsl(218, 41%, 30%) 35%,
			hsl(218, 41%, 20%) 75%,
			hsl(218, 41%, 19%) 80%,
			transparent 100%
		);
		height: 100vh;
		padding-left: 70px;
		overflow-x: hidden;
		}
	
	
	.bg-glass {
		background: hsla(0, 0%, 0%, .15);
		backdrop-filter: blur(30px);
		}
	
	.bg-theme {
		background-color: hsla(60, 7%, 97%, 1);
		}
	
	.rounded {
		border-radius: .25rem !important
		}
	
	.rounded-0 {
		border-radius: 0 !important
		}
	
	.rounded-1 {
		border-radius: .2rem !important
		}
	
	.rounded-2 {
		border-radius: .25rem !important
		}
	
	.rounded-3 {
		border-radius: .3rem !important
		}
	
	.rounded-circle {
		border-radius: 50% !important
		}
	
	.rounded-pill {
		border-radius: 50rem !important
		}
	
	.rounded-4 {
		border-radius: .375rem !important
		}
	
	.rounded-5 {
		border-radius: .5rem !important
		}
	
	.rounded-6 {
		border-radius: .75rem !important
		}
	
	.rounded-7 {
		border-radius: 1rem !important
		}
	
	.rounded-8 {
		border-radius: 1.25rem !important
		}
	
	.rounded-9 {
		border-radius: 1.5rem !important
		}
	
	
	.ripple-surface {
		position: relative;
		overflow: hidden;
		display: inline-block;
		vertical-align: bottom;
		}
	
	.text-sm {
		font-size: .85rem;
		}
	
	
	.page-header-actions {
		position: absolute;
		top: 1rem;
		right: 2rem;
		margin: auto;
		transform: translateY(-1rem);
		}
	
	
	.card-block {
		position: relative;
		-webkit-box-flex: 1;
		-webkit-flex: 1 1 auto;
		-ms-flex: 1 1 auto;
		flex: 1 1 auto;
		padding: 1.429rem
		}
	
	.font-weight-unset {
		font-weight: unset !important
		}
	
	.font-weight-100 {
		font-weight: 100 !important
		}
	
	.font-weight-200 {
		font-weight: 200 !important
		}
	
	.font-weight-300 {
		font-weight: 300 !important
		}
	
	.font-weight-400 {
		font-weight: 400 !important
		}
	
	.font-weight-500 {
		font-weight: 500 !important
		}
	
	.font-weight-600 {
		font-weight: 600 !important
		}
	
	.font-weight-700 {
		font-weight: 700 !important
		}
	
	.font-weight-800 {
		font-weight: 800 !important
		}
	
	.font-weight-900 {
		font-weight: 900 !important
		}
	
	.font-weight-light {
		font-weight: 100 !important
		}
	
	.font-weight-normal {
		font-weight: 300 !important
		}
	
	.font-weight-medium {
		font-weight: 400 !important
		}
	
	.font-weight-bold {
		font-weight: 500 !important
		}
	
	.font-size-0 {
		font-size: 0 !important
		}
	
	.font-size-10 {
		font-size: 10px !important
		}
	
	.font-size-12 {
		font-size: 12px !important
		}
	
	.font-size-14 {
		font-size: 14px !important
		}
	
	.font-size-16 {
		font-size: 16px !important
		}
	
	.font-size-18 {
		font-size: 18px !important
		}
	
	.font-size-20 {
		font-size: 20px !important
		}
	
	.font-size-24 {
		font-size: 24px !important
		}
	
	.font-size-26 {
		font-size: 26px !important
		}
	
	.font-size-30 {
		font-size: 30px !important
		}
	
	.font-size-40 {
		font-size: 40px !important
		}
	
	.font-size-50 {
		font-size: 50px !important
		}
	
	.font-size-60 {
		font-size: 60px !important
		}
	
	.font-size-70 {
		font-size: 70px !important
		}
	
	.font-size-80 {
		font-size: 80px !important
		}
	
	.media .media {
		padding-bottom: 0;
		border-bottom: none
		}
	
	.media-body {
		overflow: auto
		}
	
	.media-meta {
		margin-bottom: 3px;
		font-size: .858rem;
		color: #a3afb7
		}
	
	.media-list {
		padding-left: 0;
		list-style: none
		}
	
	.media-list > .media {
		margin-top: 15px
		}
	
	.media-list > .media:first-child {
		margin-top: 0
		}
	
	@media (min-width: 768px) {
		.media-body {
			overflow: hidden
			}
		
		.media .media {
			margin-left: 0
			}
		}
	
	@media (max-width: 479px) {
		.media {
			-webkit-box-orient: vertical;
			-webkit-box-direction: normal;
			-webkit-flex-direction: column;
			-ms-flex-direction: column;
			flex-direction: column
			}
		
		.media > div:first-child {
			margin-bottom: 5px
			}
		
		.media .media {
			padding-left: 15px
			}
		}
	
	.avatar {
		position: relative;
		display: inline-block;
		width: 40px;
		white-space: nowrap;
		vertical-align: bottom;
		border-radius: 1000px
		}
	
	.avatar i {
		position: absolute;
		right: 0;
		bottom: 0;
		width: 10px;
		height: 10px;
		border: 2px solid #fff;
		border-radius: 100%
		}
	
	.avatar img {
		width: 100%;
		max-width: 100%;
		height: auto;
		border: 0 none;
		border-radius: 1000px
		}
	
	.avatar-online i {
		background-color: #11c26d
		}
	
	.avatar-off i {
		background-color: #526069
		}
	
	.avatar-busy i {
		background-color: #eb6709
		}
	
	.avatar-away i {
		background-color: #ff4c52
		}
	
	.avatar-100 {
		width: 100px
		}
	
	.avatar-100 i {
		width: 20px;
		height: 20px
		}
	
	.avatar-lg {
		width: 50px
		}
	
	.avatar-lg i {
		width: 12px;
		height: 12px
		}
	
	.avatar-sm {
		width: 30px
		}
	
	.avatar-sm i {
		width: 8px;
		height: 8px
		}
	
	.avatar-xs {
		width: 20px
		}
	
	.avatar-xs i {
		width: 7px;
		height: 7px
		}
	
	.status {
		display: block;
		width: 10px;
		height: 10px;
		border: 2px solid #fff;
		border-radius: 100%
		}
	
	.status-online {
		background-color: #11c26d
		}
	
	.status-off {
		background-color: #526069
		}
	
	.status-busy {
		background-color: #eb6709
		}
	
	.status-away {
		background-color: #ff4c52
		}
	
	.status-lg {
		width: 14px;
		height: 14px
		}
	
	.status-md {
		width: 10px;
		height: 10px
		}
	
	.status-sm {
		width: 8px;
		height: 8px
		}
	
	.status-xs {
		width: 7px;
		height: 7px
		}
	
	.project-title:hover a.btn-edit {
		display: inline-block;
		}
	
	.card .card-body h1, .card .card-body h2, .card .card-body h3, .card .card-body h4, .card .card-body h5, .card .card-body h6 {
		font-weight: 400
		}
	
	
	.card .card-body .card-title a {
		transition: .2s ease-in-out
		}
	
	.card .card-body .card-title a:hover {
		transition: .2s ease-in-out
		}
	
	.h1 .icon:first-child,
	.h2 .icon:first-child,
	.h3 .icon:first-child,
	.h4 .icon:first-child,
	.h5 .icon:first-child,
	.h6 .icon:first-child,
	h1 .icon:first-child,
	h2 .icon:first-child,
	h3 .icon:first-child,
	h4 .icon:first-child,
	h5 .icon:first-child,
	h6 .icon:first-child {
		margin-right: 0.5em;
		}
	
	h4.project-title .btn-edit {
		display: none;
		padding: 0;
		margin-left: 5px;
		}
	
	.btn-pure.btn-default {
		color: #a3afb7;
		}
	
	.btn-default:not([disabled]):not(.disabled).active.focus, .btn-default:not([disabled]):not(.disabled).active.hover, .btn-default:not([disabled]):not(.disabled).active:focus, .btn-default:not([disabled]):not(.disabled).active:hover, .btn-default:not([disabled]):not(.disabled):active.focus, .btn-default:not([disabled]):not(.disabled):active.hover, .btn-default:not([disabled]):not(.disabled):active:focus, .btn-default:not([disabled]):not(.disabled):active:hover, .open > .btn-default.dropdown-toggle.focus, .open > .btn-default.dropdown-toggle.hover, .open > .btn-default.dropdown-toggle:focus, .open > .btn-default.dropdown-toggle:hover, .show > .btn-default.dropdown-toggle.focus, .show > .btn-default.dropdown-toggle.hover, .show > .btn-default.dropdown-toggle:focus, .show > .btn-default.dropdown-toggle:hover {
		background-color: #ccd5db;
		border-color: #ccd5db
		}
	
	.page-project .btn-pure.btn-edit:focus, .page-project .btn-pure.btn-edit:hover {
		color: #11c26d;
		}
	
	.form-label {
		-webkit-font-smoothing: antialiased;
		font-size: 14px;
		font-weight: 400;
		color: rgb(96, 94, 92);
		margin-bottom: 0;
		}
	
	span.form-edit {
		font-size: 14px;
		font-weight: 600;
		color: rgb(50, 49, 48);
		}
	
	.button-label {
		text-align: center;
		cursor: pointer;
		padding: 0px 4px;
		border-radius: 2px;
		height: 40px;
		color: rgb(0, 111, 201);
		margin: 0px 4px;
		font-size: 14px;
		}
	
	div.panel > div.panel-heading {
		border-top-left-radius: 0.214rem;
		border-top-right-radius: 0.214rem;
		position: relative;
		padding: 0;
		border-bottom: 1px solid transparent;
		}
	
	div.panel > div.panel-body {
		padding: 0 30px 30px;
		position: relative;
		min-height: auto;
		}
	
	div.panel > div.panel-heading > h3.panel-title {
		display: block;
		padding: 20px 30px;
		margin-top: 0;
		margin-bottom: 0;
		font-size: 18px;
		color: #37474f;
		}
	
	div.panel > div.panel-heading > ul.panel-actions {
		position: absolute;
		top: 50%;
		right: 30px;
		list-style: none;
		z-index: 1;
		margin: auto;
		-webkit-transform: translate(0, -50%);
		-ms-transform: translate(0, -50%);
		-o-transform: translate(0, -50%);
		transform: translate(0, -50%);
		}
	
	div.panel > div.panel-heading > ul.panel-actions.panel-actions-keep > li > a {
		color: #3e8ef7;
		text-decoration: none;
		background-color: transparent;
		-webkit-text-decoration-skip: objects;
		}
	
	label.inline-label {
		-webkit-font-smoothing: antialiased;
		font-size: 14px;
		font-weight: 400;
		color: rgb(96, 94, 92);
		display: inline;
		}
	
	span.inline-value {
		-webkit-font-smoothing: antialiased;
		font-size: 14px;
		font-weight: 600;
		color: rgb(50, 49, 48);
		display: inline;
		}
	
	span.inline-description {
		-webkit-font-smoothing: antialiased;
		font-size: 14px;
		font-weight: 400;
		color: rgb(96, 94, 92);
		display: inline;
		}
	
	
	.card .action-element {
		position: absolute;
		right: 0;
		font-size: .85rem;
		font-weight: 500;
		vertical-align: bottom;
		margin-bottom: 0.75rem;
		line-height: 1.2;
		}
	
	.card .card-body h6 i {
		font-size: 1rem;
		height: 1.2rem;
		width: 1rem;
		vertical-align: middle;
		text-align: center;
		line-height: 1;
		margin-right: 0.5rem;
		}
	
	.card .card-body h5.card-title span {
		font-weight: 400;
		}
	
	div.card div.card-body h6 span {
		font-size: 1rem;
		height: 1.2rem;
		line-height: 1.2rem;
		vertical-align: middle;
		text-align: center;
		font-weight: 300;
		}
	
	
	.oneStar {
		color: #44370f;
		}
	
	.twoStars {
		color: #96781e;
		}
	
	.threeStars {
		
		color: #e2b52e;
		}
	
	.fourStars {
		color: #f1ba12;
		}
	
	.fiveStars {
		color: #f3cb06;
		}
	
	#rating.empty-stars > i {
		margin-left: 1rem;
		margin-bottom: .5rem
		}
	
	.modal {
		position: fixed;
		top: 0;
		left: 0;
		z-index: 1050;
		display: none;
		width: 100vw;
		height: 100vh;
		overflow: hidden;
		outline: 0;
		}
	
	.bootstrap-maxlength.badge {
		margin-top: .5rem
		}
	
	
	.page-project .card-block {
		padding: 25px;
		border-top: 1px solid #e4eaec
		}
	
	.page-project .card-block:first-child {
		border-top: none;
		}
	
	.page-project .card .card-block + .card-block {
		padding: 25px;
		}
	
	.page-project .btn-pure.btn-trash:focus, .page-project .btn-pure.btn-trash:hover {
		color: #ff4c52;
		}
	
	.page-project .btn-pure.btn-edit:focus, .page-project .btn-pure.btn-edit:hover {
		color: #11c26d;
		}
	
	.page-project .ui-helper-hidden-accessible {
		display: none
		}
	
	div.excerpt {
		margin-top: 3rem;
		padding-left: 1rem;
		padding-right: 1rem;
		}
	
	span.badge {
		display: inline-block;
		padding: .25em 0.4em;
		font-size: 12px;
		font-weight: 700;
		line-height: 1.3;
		text-align: center;
		white-space: nowrap;
		vertical-align: baseline;
		border-radius: 0.125rem;
		transition: color .15s ease-in-out, background-color .15s ease-in-out, border-color .15s ease-in-out, box-shadow .15s ease-in-out;
		}
	
	#toast-container > div.md-toast.md-toast-info {
		color: #0a070d !important; /*#241DAA*/
		background-color: #d5d2fd !important;
		border-color: #2a21c6 !important;
		background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAFGSURBVDhPpZO9SgNREEY3KaIINoqtkELSWVj5AqIWSWXhQ1ily3vYWKZLYaMWCvEBtAloFywCtqKNIGgRPGczubjrIqgfHGZ2fu7evXe2lpW0tLDcwHRgB5rG0ASu4ezt/fUjj4QKC9DcxhzDOrzAGFQLVuARjljkwmBBNHdhCiPYhXqkzNUjZs6abqRmItCOxAD8hFz4mxKPPjeixlp3m9UMYh/gGbbn30jcxpE+2iJ+rxP1N7AKG27TA/Obe+UDqlLU9MCejjs4wTmANZJTbFLswqb87XMR98VPcKrjVY0rmi8xd3CbB74oar2hZjrpCvXDLoatlAs4JK3YVhJvGYT7TVHrbEx0nDCHxMlLougw3IIfstae4U/X6Bns6aMr4vs6UZ+u0ZjBykEqy1zUpEFKIvCnUf73z/Sb33kI5/MzminLPgEWGncWlHVkdQAAAABJRU5ErkJggg==) !important;
		}
	
	#toast-container > div.md-toast.md-toast-info > button.md-toast-close-button {
		color: #0a070d !important;
		}
	
	#toast-container > div.md-toast.md-toast-info > div.md-toast-title {
		color: #241DAA !important;
		font-weight: 500
		}
	
	#toast-container > div.md-toast.md-toast-success {
		font-weight: 400;
		color: #0a070d !important;
		background-color: #8cd8b1 !important;
		border-color: #016733 !important;
		background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAD3SURBVEhL7ZOxCsIwGIRTF0EQZx0d9BGcdXH1UV2Lg7MPIOigo85SEJz07k9aiIY0fy1OfnDkT5reNWli/vyUXrc/gDbQHppyLJMnLUBzNDk0kwFjLtCilYCAecm544rGRMxJ8dUKasyP0LxxQIr5/VFcZYsweQLxz/ME8MUoqebsZDRHu4VGHAA7aIkJN9v10ZgTBpzQjm23IhiiNSfcosKWHjTInaHQxJxwBUO03CK5eW/ISmypNydyihJCiNqcVMe0JiRErTnx7oEiJMmcfFy0hJBkcxK8yZEQlXkUhkAH6OnEmsEqgisocYZr2zOrVr78j48xLydnabp09vnmAAAAAElFTkSuQmCC) !important;
		}
	
	
	#toast-container > div.md-toast.md-toast-success > button.md-toast-close-button {
		color: #0a070d !important;
		}
	
	#toast-container > div.md-toast.md-toast-success > div.md-toast-title {
		color: #013C22 !important;
		font-weight: 500
		}
	
	#toast-container > div.md-toast.md-toast-warning {
		font-weight: 400;
		color: #0a070d !important;
		background-color: #ebbf7a !important;
		border-color: #442a00 !important;
		background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAHxSURBVEhLtZQ7LARRGIWHjRCVhgKNRhQSOq1SVBJqFVEvDY1sKOgoFCQKtahXqaUSicSjUKGgQCSyXuE7M2fXjB3W80vO3jvnf9y7dx7Bf1PlsSL1tZlWhsnoKpi/u38+9fz30DyDdtGLpXnG4U+p9liJEdSNzizNR1FFKh4RO21gOEaNaEgebKBL1M5RXYfOT2GBBR/Lli15W/YWbP0MGnSgB/SEumzL77KnWIft70NxHmmny7ZKyHMsb+t7UNjvBldI559AnmPK6bf9NSioQYcuztobRuvWsL0sUo5ya+R9iVjhQbGQccWeFB6ZYkg5pY28p+w9IFHHMR1dBRM8ho+e33gU4dyxcc1h2rUJ0l60WaRnP0+D+A0sW0CQs8mgPNWoNkFiAXagR1FvrXY2IS9G6gJG/0I1I+5R4v0/WET6xiyxs8PQeUOfiCLnHkPIPWJYQqpVj3JYeRDpZl0g/d0EeNVowEq7dw1IteoxaDsCow6dODhmOwF+znEpZzuBah1Xrzp5xZ3oDNvQHlqVkUKPRxGfx1GteqhX9HSxUjO69cq9oZkCsT7nSX22y1APpF7Ka5axZkOf4E8hp1by5Yeol3uuVfFTwFPRDNpXwh/QifSyFrTANpOPzvS37GiBFiZTqCm0/o4LNBdN/40geAVspYnJSOxEwAAAAABJRU5ErkJggg==) !important;
		}
	
	#toast-container > div.md-toast.md-toast-warning > button.md-toast-close-button {
		color: #0a070d !important;
		}
	
	#toast-container > div.md-toast.md-toast-warning > div.md-toast-title {
		color: #442a00 !important;
		font-weight: 500
		}
	
	#toast-container > div.md-toast.md-toast-error {
		color: #0a070d !important;
		font-weight: 400;
		background-color: #ff7d73 !important;
		border-color: #7b0900 !important;
		background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAIgSURBVEhLtZbPKwVRFMevJ72oZynFn8CGlYUFC7HxHxBL8g/YWWFP2SmUP4GyYCGsKOEfECU7kZL8+H5mzn3dMXfGU963Pt075557zryZe868FveLOqq1bg0jol90YZMexbU4fH17fkgsBSpMoMDDGhbFmGjFFtGHOBArSnScWH4ol0CBaxrWxLTw68/iXNwnV871iAHRmVw59yV2xIIS4RsXj0Ncii/jVEyKNnOpC5ut4eP92csjzUsLNXPA8U3Mi0beUYv5sscn4SlkJeOWOeA4buaGxR7bS4wtM6eSYdgWYN7MGcl+EvicmDkj9tr6p+CQuEqykp4WdCY20mlOVRtROA/FXmLwaJOYFWXipXAU0apOAScipvB0RE+K7V1Nr9wYsfkFo4JzzqZ9UaQXG1HxUUxjsE7MERL0CXSuO3i3eUxh0DBZRhbjIr1y/STw5e+LqEhhgrJfgO5s7PIvuRH9JUFdJKBxIcq/TLtiyWBepl4bH0lAV0SDeuu5lhDoRtwazKOyGPQpdEWCQ0FXpLwnRJGozk0jW6lZEYNYxDzCQNZ9QQXSuKL9R/Yn84EnM2fUnvYl3/z2sPmXvGzjkJhLpzmFNRKtF90Ze4lBwa1gq0sZS5udbFUxI2aZm7ku9oh4s0MyNrddIy38+wcnd4dyIPu6mBJ+ncKi/H2FUjODIrzTbZH7ZBY+AiVqzkf/p+wnx/62XIkjBS752+LcNyPJsVnMbZ3GAAAAAElFTkSuQmCC) !important;
		}
	
	#toast-container > div.md-toast.md-toast-error > button.md-toast-close-button {
		color: #0a070d !important;
		}
	
	#toast-container > div.md-toast.md-toast-error > div.md-toast-title {
		color: #330300 !important;
		font-weight: 500
		}
	
	#carousel-example-multi > div.controls-top > a:nth-child(1) > i {
		height: 47px;
		width: 47px;
		text-align: center;
		vertical-align: middle;
		margin-left: -3px;
		}
	
	#carousel-example-multi > div.controls-top > a:nth-child(2) > i {
		height: 47px;
		width: 47px;
		text-align: center;
		vertical-align: middle;
		margin-right: -3px;
		}
	
	#carousel-example-multi > ol > li {
		width: 1.25rem;
		max-width: 1.25rem;
		height: 1.25rem;
		margin-right: 3px;
		margin-left: 3px;
		text-indent: -999px;
		margin-bottom: -3.75rem;
		background-color: #ff884f;
		background-clip: padding-box;
		border-color: transparent;
		opacity: .5;
		transition: opacity .6s ease;
		}
	
	#carousel-example-multi > ol > li.active,
	#carousel-example-multi > ol > li:active {
		width: 1.56rem;
		max-width: 1.56rem;
		height: 1.56rem;
		background-color: #ff884f;
		border-radius: 50%;
		opacity: 1;
		}
	
	#carousel-example-multi > div.carousel-inner,
	#carousel-example-multi > div.carousel-inner > div.carousel-item {
		height: initial;
		max-height: initial;
		min-height: initial;
		}
	
	.panel_link {
		margin-right: 2rem;
		position: absolute;
		right: 0;
		font-size: 1rem;
		font-weight: 400;
		}
	
	div.card.card-body.panel-code {
		max-height: 500px;
		
		padding: 0;
		}
	
	
	div.panel-actions > a.panel-action.fas {
		display: inline-block;
		padding: 0 0;
		color: #a3afb7;
		text-decoration: none;
		cursor: pointer;
		background-color: transparent;
		margin: 0;
		font-size: 16px;
		height: 16px;
		width: 16px;
		}
	
	div.panel-footer, div.panel-body, div.panel-title {
		padding-right: 1.5rem;
		padding-left: 1.5rem;
		padding-bottom: 1.5rem;
		}
	
	div.panel-actions > a.panel-action.fas:hover {
		color: #526069;
		}
	
	.bd-highlight {
		background-color: #33b5e5;
		border: 2px solid #fff;
		color: #fff;
		}
	
	div.selected-day {
		background: #bce8f1;
		opacity: .3;
		}
	
	a.btn-floating.btn-lg > i {
		font-size: 1.6rem !important;
		line-height: 3.2rem !important;
		}
	
	pre[class*="language-"] {
		padding: 1em;
		margin: 0.5em 0;
		overflow: auto;
		border-radius: 0.3em;
		height: 100%;
		min-height: 300px;
		}
	
	.text-secondary {
		color: #e54a00 !important;
		}
	
	div.panel > div.panel-body.panel-code > div.code-toolbar {
		height: 100%;
		max-height: 400px
		}
	
	div.panel > div.panel-body.panel-code {
		height: 100%;
		max-height: 400px
		}
	
	
	div.panel.is-fullscreen > div.panel-body.panel-code > div.code-toolbar {
		max-height: 86vh;
		height: 100%;
		}
	
	div.panel.is-fullscreen > div.panel-body.panel-code {
		max-height: 86vh;
		height: 100%;
		}
	
	.fc td, .fc th {
		padding: 0 !important
		}
	
	form.search-form {
		min-height: initial !important;
		height: fit-content !important;
		}
	
	
	.md-pills .nav-link.active, .md-pills .nav-link.active:hover, .md-pills .nav-link.active:focus, .md-pills .nav-link.active:active {
		background: #ff884f !important;
		color: #0a070d !important;
		}
	
	
	div.code-toolbar {
		position: relative;
		}
	
	div.code-toolbar > .toolbar {
		position: absolute;
		z-index: 10;
		top: .3em;
		right: .2em;
		transition: opacity 0.3s ease-in-out;
		opacity: 0;
		}
	
	div.code-toolbar:hover > .toolbar {
		opacity: 1;
		}
	
	/* Separate line b/c rules are thrown out if selector is invalid.
	   IE11 and old Edge versions don't support :focus-within. */
	div.code-toolbar:focus-within > .toolbar {
		opacity: 1;
		}
	
	div.code-toolbar > .toolbar > .toolbar-item {
		display: inline-block;
		}
	
	div.code-toolbar > .toolbar > .toolbar-item > a {
		cursor: pointer;
		}
	
	div.code-toolbar > .toolbar > .toolbar-item > button {
		background: none;
		border: 0;
		color: inherit;
		font: inherit;
		line-height: normal;
		overflow: visible;
		padding: 0;
		-webkit-user-select: none; /* for button */
		-moz-user-select: none;
		-ms-user-select: none;
		}
	
	div.code-toolbar > .toolbar > .toolbar-item > a,
	div.code-toolbar > .toolbar > .toolbar-item > button,
	div.code-toolbar > .toolbar > .toolbar-item > span {
		color: #bbb;
		font-size: .8em;
		padding: 0 .5em;
		background: #f5f2f0;
		background: rgba(224, 224, 224, 0.2);
		box-shadow: 0 2px 0 0 rgba(0, 0, 0, 0.2);
		border-radius: .5em;
		}
	
	div.code-toolbar > .toolbar > .toolbar-item > a:hover,
	div.code-toolbar > .toolbar > .toolbar-item > a:focus,
	div.code-toolbar > .toolbar > .toolbar-item > button:hover,
	div.code-toolbar > .toolbar > .toolbar-item > button:focus,
	div.code-toolbar > .toolbar > .toolbar-item > span:hover,
	div.code-toolbar > .toolbar > .toolbar-item > span:focus {
		color: inherit;
		text-decoration: none;
		}
	
	.trips-skin .btn-primary:focus, .trips-skin .btn-primary:active, .trips-skin .btn-primary.active {
		background-color: #0b51c5 !important;
		}
	
	.popover-header {
		padding: 0.5rem 0.75rem;
		margin-bottom: 0;
		font-size: 1rem;
		background-color: #f7f7f7;
		border-bottom: 1px solid #ebebeb;
		border-top-left-radius: calc(0.3rem - 1px);
		border-top-right-radius: calc(0.3rem - 1px);
		line-height: 1.5;
		}
	
	.number-input input[type="number"] {
		-webkit-appearance: textfield;
		-moz-appearance: textfield;
		appearance: textfield;
		text-align: center;
		font-size: 1rem;
		color: #495057;
		}
	
	.number-input input[type=number]::-webkit-inner-spin-button,
	.number-input input[type=number]::-webkit-outer-spin-button {
		-webkit-appearance: none;
		}
	
	
	.popover {
		width: 451px;
		min-width: 451px;
		max-width: 451px;
		}
	
	.form-label-popover {
		height: 30px;
		width: 100%;
		line-height: 30px;
		vertical-align: middle;
		font-size: 1rem;
		font-weight: 500;
		padding-left: 1rem;
		}
	
	div.input-group > .form-element > .form-control {
		width: 100%;
		height: 30px;
		line-height: 30px;
		max-width: 100px;
		font-size: 1rem;
		}
	
	div.input-group > div.input-group-prepend > span.input-group-text,
	div.input-group > div.input-group-append > span.input-group-text {
		cursor: pointer;
		}
	
	div.input-group > div.input-group-prepend > span.input-group-text > i,
	div.input-group > div.input-group-append > span.input-group-text > i {
		font-size: 1rem;
		font-weight: 900;
		line-height: 1.1
		}
	
	.popup-window-button-close {
		font-weight: bold;
		float: right;
		padding: 8px 10px;
		cursor: pointer;
		text-decoration: none;
		color: #a3afb7;
		background-color: transparent;
		height: 100%;
		width: 14px;
		line-height: 1;
		margin-top: -3px;
		}
	
	.btn.btn-category-picker {
		margin: 0 0 0 0;
		background: #fff;
		padding: 0;
		font-size: inherit;
		border: 1px solid #e0e0e0;
		border-radius: 3px;
		box-shadow: 0 1px 2px rgba(0, 0, 0, .10);
		text-align: left;
		border-left: solid .4rem #8e00a8;
		width: inherit;
		min-width: 10rem
		}
	
	.btn.btn-city-picker {
		margin: 0 0 0 0;
		background: #fff;
		padding: 0;
		font-size: inherit;
		border: 1px solid #e0e0e0;
		border-radius: 3px;
		box-shadow: 0 1px 2px rgba(0, 0, 0, .10);
		text-align: left;
		border-left: solid .4rem #0040a8;
		width: inherit;
		min-width: 10rem
		}
	
	.btn.btn-check-out-picker {
		margin: 0 0 0 0;
		background: #fff;
		padding: 0;
		font-size: inherit;
		border: 1px solid #e0e0e0;
		border-radius: 3px;
		box-shadow: 0 1px 2px rgba(0, 0, 0, .10);
		text-align: left;
		border-left: solid .4rem #c00;
		width: inherit;
		min-width: 10rem
		}
	
	
	.btn.btn-guest-picker {
		margin: 0 0 0 0;
		background: #fff;
		padding: 0;
		font-size: inherit;
		border: 1px solid #e0e0e0;
		border-radius: 3px;
		box-shadow: 0 1px 2px rgba(0, 0, 0, .10);
		text-align: left;
		border-left: solid .4rem #757575;
		width: inherit;
		min-width: 10rem
		}
	
	.btn.btn-check-in-picker {
		margin: 0 0 0 0;
		background: #fff;
		padding: 0;
		font-size: inherit;
		border: 1px solid #e0e0e0;
		border-radius: 3px;
		box-shadow: 0 1px 2px rgba(0, 0, 0, .10);
		text-align: left;
		border-left: solid .4rem #00aa6c;
		width: inherit;
		min-width: 10rem
		}
	
	.btn.btn-name-picker {
		margin: 0 0 0 0;
		background: #fff;
		padding: 0;
		font-size: inherit;
		border: 1px solid #e0e0e0;
		border-radius: 3px;
		box-shadow: 0 1px 2px rgba(0, 0, 0, .10);
		text-align: left;
		border-left: solid .4rem #eda600;
		width: inherit;
		min-width: 10rem
		}
	
	
	.product-search-name input[type=text]:not(.browser-default) {
		position: relative;
		margin-top: 1.5rem;
		margin-bottom: 1.5rem;
		box-sizing: content-box;
		background-color: transparent;
		outline: none;
		box-shadow: none;
		transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
		border: 1px solid #e0e0e0;
		border-radius: 3px;
		border-left: solid .4rem #eda600;
		}
	
	.product-search-name label.active {
		transform: translateY(-14px) scale(0.8);
		font-size: 1rem;
		}
	
	.product-search-name label {
		max-width: 100%;
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
		position: absolute;
		top: 0;
		color: #333;
		cursor: text;
		transition: transform .2s ease-out, color .2s ease-out;
		transform-origin: 0% 100%;
		left: 36px;
		right: initial;
		
		font-size: .75em;
		line-height: normal;
		font-weight: 400 !important;
		text-transform: uppercase;
		margin: 0;
		transform: translateY(11px);
		
		
		}
	
	.input-with-pre-icon.product-search-name .input-prefix {
		margin: 0 2px 0 8px;
		font-size: 1.25em;
		color: #757575;
		height: auto;
		width: auto;
		left: 0.5rem;
		right: initial;
		}
	
	.datepicker td, .datepicker th {
		text-align: center;
		width: auto;
		height: auto;
		padding: 0 !important;
		}
	
	.input-with-pre-icon.product-search-name .input-prefix.active {
		color: #eda600
		}
	
	.product-search-name input:not([type]):focus:not([readonly]) + label,
	.product-search-name input[type=text]:not(.browser-default):focus:not([readonly]) + label,
	.product-search-name input[type=password]:not(.browser-default):focus:not([readonly]) + label,
	.product-search-name input[type=email]:not(.browser-default):focus:not([readonly]) + label,
	.product-search-name input[type=url]:not(.browser-default):focus:not([readonly]) + label,
	.product-search-name input[type=time]:not(.browser-default):focus:not([readonly]) + label,
	.product-search-name input[type=date]:not(.browser-default):focus:not([readonly]) + label,
	.product-search-name input[type=datetime]:not(.browser-default):focus:not([readonly]) + label,
	.product-search-name input[type=datetime-local]:not(.browser-default):focus:not([readonly]) + label,
	.product-search-name input[type=tel]:not(.browser-default):focus:not([readonly]) + label,
	.product-search-name input[type=number]:not(.browser-default):focus:not([readonly]) + label,
	.product-search-name input[type=search]:not(.browser-default):focus:not([readonly]) + label,
	.product-search-name input[type=phone]:not(.browser-default):focus:not([readonly]) + label,
	.product-search-name input[type=search-md]:focus:not([readonly]) + label,
	.product-search-name textarea.md-textarea:focus:not([readonly]) + label {
		color: #333
		}
	
	.product-search-name input:not([type]):focus:not([readonly]),
	.product-search-name input[type=text]:not(.browser-default):focus:not([readonly]),
	.product-search-name input[type=password]:not(.browser-default):focus:not([readonly]),
	.product-search-name input[type=email]:not(.browser-default):focus:not([readonly]),
	.product-search-name input[type=url]:not(.browser-default):focus:not([readonly]),
	.product-search-name input[type=time]:not(.browser-default):focus:not([readonly]),
	.product-search-name input[type=date]:not(.browser-default):focus:not([readonly]),
	.product-search-name input[type=datetime]:not(.browser-default):focus:not([readonly]),
	.product-search-name input[type=datetime-local]:not(.browser-default):focus:not([readonly]),
	.product-search-name input[type=tel]:not(.browser-default):focus:not([readonly]),
	.product-search-name input[type=number]:not(.browser-default):focus:not([readonly]),
	.product-search-name input[type=search]:not(.browser-default):focus:not([readonly]),
	.product-search-name input[type=phone]:not(.browser-default):focus:not([readonly]),
	.product-search-name input[type=search-md]:focus:not([readonly]),
	.product-search-name textarea.md-textarea:focus:not([readonly]) {
		border-top: 1px solid #eda600;
		border-bottom: 1px solid #eda600;
		border-right: 1px solid #eda600;
		border-left: solid .4rem #eda600;
		box-shadow: none;
		}
	
	
	.btn-category-picker.dropdown-toggle::after {
		display: inline-flex;
		margin-left: 0.255em;
		vertical-align: 0.255em;
		content: '';
		border-top: 0.3em solid;
		border-right: 0.3em solid transparent;
		border-bottom: 0;
		border-left: 0.3em solid transparent;
		position: absolute;
		right: 0.4rem;
		top: 1.4rem;
		
		}
	
	
	span.sm-button-span {
		-moz-osx-font-smoothing: grayscale;
		-webkit-font-smoothing: antialiased;
		padding-left: 1.1rem !important;
		padding-right: 1.1rem !important;
		display: inline-block;
		font-style: normal;
		font-variant: normal;
		text-rendering: auto;
		line-height: 1.2rem;
		font-size: .75rem;
		height: 1rem;
		width: auto;
		text-align: center;
		vertical-align: middle;
		}
	
	.btn-small {
		font-size: .75rem;
		border: solid 2px transparent;
		margin-top: 0;
		margin-bottom: 0;
		margin-left: .25rem;
		margin-right: .25rem;
		}
	
	.btn.btn-primary.btn-small,
	.btn.btn-secondary.btn-small,
	.btn.btn-success.btn-small,
	.btn.btn-warning.btn-small,
	.btn.btn-info.btn-small,
	.btn.btn-danger.btn-small,
	.btn.btn-default.btn-small {
		padding: 1rem !important;
		
		}
	
	.btn.btn-outline-primary.btn-small,
	.btn.btn-outline-info.btn-small,
	.btn.btn-outline-secondary.btn-small,
	.btn.btn-outline-success.btn-small,
	.btn.btn-outline-warning.btn-small,
	.btn.btn-outline-default.btn-small,
	.btn.btn-outline-danger.btn-small {
		padding: calc(.5rem - 2px) 1rem !important;
		
		}
	
	.btn-small > i {
		margin: 0
		}
	
	@media (min-width: 480px) {
		.btn.btn-primary.btn-small,
		.btn.btn-secondary.btn-small,
		.btn.btn-success.btn-small,
		.btn.btn-warning.btn-small,
		.btn.btn-info.btn-small,
		.btn.btn-danger.btn-small,
		.btn.btn-default.btn-small {
			padding: 1rem !important;
			}
		
		.btn.btn-outline-primary.btn-small,
		.btn.btn-outline-info.btn-small,
		.btn.btn-outline-secondary.btn-small,
		.btn.btn-outline-success.btn-small,
		.btn.btn-outline-warning.btn-small,
		.btn.btn-outline-default.btn-small,
		.btn.btn-outline-danger.btn-small {
			padding: 1rem !important;
			
			}
		}
	
	@media (min-width: 768px) {
		.btn.btn-primary.btn-small,
		.btn.btn-secondary.btn-small,
		.btn.btn-success.btn-small,
		.btn.btn-warning.btn-small,
		.btn.btn-info.btn-small,
		.btn.btn-danger.btn-small,
		.btn.btn-default.btn-small {
			padding: 1rem !important;
			}
		
		.btn.btn-outline-primary.btn-small,
		.btn.btn-outline-info.btn-small,
		.btn.btn-outline-secondary.btn-small,
		.btn.btn-outline-success.btn-small,
		.btn.btn-outline-warning.btn-small,
		.btn.btn-outline-default.btn-small,
		.btn.btn-outline-danger.btn-small {
			padding: 1rem !important;
			
			}
		}
	
	@media (min-width: 992px) {
		.btn.btn-primary.btn-small,
		.btn.btn-secondary.btn-small,
		.btn.btn-success.btn-small,
		.btn.btn-warning.btn-small,
		.btn.btn-info.btn-small,
		.btn.btn-danger.btn-small,
		.btn.btn-default.btn-small {
			padding: 0.5rem !important;
			}
		
		.btn.btn-outline-primary.btn-small,
		.btn.btn-outline-info.btn-small,
		.btn.btn-outline-secondary.btn-small,
		.btn.btn-outline-success.btn-small,
		.btn.btn-outline-warning.btn-small,
		.btn.btn-outline-default.btn-small,
		.btn.btn-outline-danger.btn-small {
			padding-top: 0.5rem !important;
			padding-bottom: 0.5rem !important;
			
			}
		}
	
	@media (min-width: 1200px) {
		.btn.btn-primary.btn-small,
		.btn.btn-secondary.btn-small,
		.btn.btn-success.btn-small,
		.btn.btn-warning.btn-small,
		.btn.btn-info.btn-small,
		.btn.btn-danger.btn-small,
		.btn.btn-default.btn-small {
			padding: 0.5rem !important;
			}
		
		.btn.btn-outline-primary.btn-small,
		.btn.btn-outline-info.btn-small,
		.btn.btn-outline-secondary.btn-small,
		.btn.btn-outline-success.btn-small,
		.btn.btn-outline-warning.btn-small,
		.btn.btn-outline-default.btn-small,
		.btn.btn-outline-danger.btn-small {
			padding-top: 0.5rem !important;
			padding-bottom: 0.5rem !important;
			
			}
		}
	
	.blue-highlight {
		background-image: none;
		background-repeat: initial;
		text-shadow: none;
		background-color: blue !important;
		}
	
	
	.col-pricing {
		margin: 0.15rem !important;
		border-radius: .25rem;
		width: 5rem;
		min-width: 5rem;
		max-width: 5rem;
		height: 5rem;
		min-height: 5rem;
		max-height: 5rem;
		padding: 0 !important;
		text-align: center;
		vertical-align: middle;
		line-height: 1.1rem;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		display: flex !important;
		flex-direction: column !important;
		align-items: flex-start !important;
		}
	
	.col-pricing .price {
		width: 100%;
		height: 3.5rem;
		max-height: 3.5rem;
		line-height: 3.5rem;
		vertical-align: middle;
		text-align: center;
		font-size: 1rem;
		font-weight: 500;
		color: #0A070D;
		background-color: #94c5f5
		}
	
	.col-pricing .date {
		width: 100%;
		height: 1.5rem;
		max-height: 1.5rem;
		line-height: 1.5rem;
		vertical-align: middle;
		text-align: center;
		font-size: .8rem;
		font-weight: 500;
		background-color: #ffb592;
		color: #0A070D;
		}
	
	.search-result {
		border-bottom: 1px solid #e0e0e0
		}
	
	.search-result:last-of-type {
		border-bottom: none
		}
	
	section.product-filter {
		padding: .5rem;
		}
	
	section.product-filter:last-of-type {
		border-bottom: none
		}
	
	.red-highlight {
		background-image: none;
		background-repeat: initial;
		text-shadow: none;
		background-color: red !important;
		}
	
	span.btn-city-picker-details,
	span.btn-name-picker-details,
	span.btn-guest-picker-details {
		display: inline-block;
		margin-top: 0.25rem;
		padding-top: 0;
		padding-right: 0.5rem;
		padding-bottom: 0;
		padding-left: 0.5rem;
		width: 8.7rem;
		vertical-align: middle;
		}
	
	span.btn-city-picker-details-title,
	span.btn-name-picker-details-title,
	span.btn-guest-picker-details-title {
		margin-bottom: 2px;
		font-size: .75em;
		line-height: normal;
		color: #333;
		white-space: nowrap;
		}
	
	span.btn-city-picker-details-info,
	span.btn-name-picker-details-info,
	span.btn-guest-picker-details-info {
		display: block;
		font-size: .8125em;
		line-height: 20px;
		}
	
	span.btn-city-picker-details-info-wrapper,
	span.btn-name-picker-details-info-wrapper,
	span.btn-guest-picker-details-info-wrapper {
		font-size: .8125em;
		line-height: 20px;
		white-space: nowrap;
		font-weight: 700;
		margin: 0;
		padding: 0;
		}
	
	i.btn-city-picker-icon,
	i.btn-name-picker-icon,
	i.btn-guest-picker-icon {
		margin-top: 0;
		margin-right: 0.25rem;
		margin-bottom: 0;
		margin-left: 0.25rem;
		font-size: 1rem;
		color: #757575;
		height: 1rem;
		width: 1rem;
		}
	
	span.btn-guest-picker-details-info-wrapper-rooms {
		
		}
	
	td[role=presentation] {
		padding: 0 !important;
		}
	
	
	div.datepicker.datepicker-dropdown {
		padding: 0;
		}
	
	div.datepicker-days > table > thead > tr:first-child {
		content: "ss"
		}
	
	.datepicker table {
		width: 451px;
		min-width: 451px;
		max-width: 451px;
		}
	
	.datepicker td, .datepicker th {
		text-align: center;
		width: auto;
		height: auto;
		padding-top: 2px !important;
		padding-left: 2px !important;
		padding-bottom: 2px !important;
		padding-right: 2px !important;
		}
	
	.cPZwQ, .GtzMn {
		margin: 0 15px;
		color: #000
		}
	
	.cPZwQ {
		padding: 15px 27px 10px;
		font-size: 15px;
		border: none;
		border-width: 0 0 1px;
		font-weight: 700
		}
	
	@media (min-width: 768px) {
		.cPZwQ {
			padding: 15px 0 10px
			}
		}
	
	@media (min-width: 768px) {
		.cPZwQ {
			text-align: center
			}
		
		.eMrph {
			width: 266px;
			box-sizing: content-box
			}
		}
	
	
	td div.date-container {
		font-weight: 700;
		height: 30px;
		width: 100%;
		text-align: center;
		vertical-align: middle;
		line-height: 30px;
		border-radius: 2px;
		background: #fff;
		padding-top: 0;
		padding-bottom: 0;
		}
	
	.datepicker table tr td.active.active div.date-container {
		background: #fff;
		color: #000;
		}
	
	.datepicker table tr td.active, .datepicker table tr td.active:hover, .datepicker table tr td.active.disabled, .datepicker table tr td.active.disabled:hover {
		background-color: #00aa6c !important;
		background-image: none;
		background-repeat: initial;
		text-shadow: none;
		}
	
	.card.map-card .living-coral-text {
		color: #fa7268;
		margin-bottom: 0.8rem;
		}
	
	.input-search-dark .input-search-icon {
		color: #76838f;
		}
	
	
	.input-search .input-search-icon {
		font-size: 16px;
		color: #a3afb7;
		text-align: center;
		pointer-events: none;
		position: absolute;
		top: 1.03rem;
		z-index: 1;
		-webkit-transform: translateY(-40%);
		-ms-transform: translateY(-40%);
		-o-transform: translateY(-40%);
		transform: translateY(-40%);
		height: 28px;
		width: 28px;
		vertical-align: middle;
		line-height: 1.8;
		margin-left: 0;
		left: 1.4rem;
		}
	
	.input-search .input-search-close {
		position: absolute;
		top: .73rem;
		right: 1.4rem;
		height: 28px;
		width: 28px;
		vertical-align: middle;
		line-height: 1.8;
		
		-webkit-transform: translateY(-26%);
		-ms-transform: translateY(-26%);
		-o-transform: translateY(-26%);
		transform: translateY(-26%);
		
		font-size: 16px;
		color: #a3afb7;
		text-align: center;
		
		z-index: 1.2;
		
		
		outline: none;
		border: none;
		background: transparent;
		}
	
	.input-search .form-control {
		border-radius: 200px;
		padding-left: 30px;
		padding-right: 30px;
		height: 28px;
		width: 100%;
		line-height: 1rem;
		font-size: 16px;
		padding-top: 7px;
		padding-bottom: 7px;
		margin: 0;
		}
	
	.input-search .input-search-close,
	.input-search .input-search-icon {
		border: none;
		}
	
	.input-search-close > i {
		font-size: 16px;
		height: 100%;
		width: 100%;
		line-height: 1.25;
		}
	
	input.dev-element[readonly='readonly'] {
		background: rgba(255, 0, 0, .4);
		color: #420000
		}
	
	td.selected-day {
		background: rgba(23, 162, 184, .20) !important;
		}
	
	td.fc-day-top.selected-day {
		background: rgba(23, 162, 184, .0) !important;
		}
	
	div.card.profile-card {
		font-size: .9rem;
		font-weight: 400;
		color: #747373;
		margin-bottom: 1rem;
		border: solid 1px transparent;
		background: #fff;
		}
	
	
	div.card.profile-card .card-body {
		font-size: .9rem;
		font-weight: 400;
		color: #747373;
		padding: 0.5rem;
		}
	
	
	div.card.profile-card.notavailable > div.card-body > h5.card-title,
	div.card.profile-card.notavailable > div.card-body > h5.card-title,
	div.card.profile-card.notavailable > div.card-body > h5.card-title,
	div.card.profile-card.notavailable > div.card-body > h5.card-title {
		color: #000000 !important;
		font-weight: 400 !important;
		}
	
	div.card.profile-card.notavailable > div.card-body > p.card-text,
	div.card.profile-card.freesale > div.card-body > p.card-text,
	div.card.profile-card.allotment > div.card-body > p.card-text,
	div.card.profile-card.onrequest > div.card-body > p.card-text {
		color: #000000 !important;
		opacity: 90% !important;
		font-weight: 300 !important;
		}
	
	div.card.profile-card.blackout > div.card-body > p.card-text {
		color: #eeeeee !important;
		font-weight: 300 !important;
		}
	
	div.card.profile-card.blackout > div.card-body > h5.card-title {
		color: #eeeeee !important;
		font-weight: 400 !important;
		}
	
	div.card.profile-card.freesale > div.card-body > table.table td {
		border-top-color: #357f8e !important;
		color: #000;
		padding: .5rem;
		}
	
	div.card.profile-card.allotment > div.card-body > table.table td {
		border-top-color: #2d895b !important;
		color: #000;
		padding: .5rem;
		}
	
	div.card.profile-card.onrequest > div.card-body > table.table td {
		border-top-color: #aa890f !important;
		color: #000;
		padding: .5rem;
		}
	
	div.card.profile-card.blackout > div.card-body > table.table td {
		border-top-color: #30353a !important;
		color: #FFF;
		padding: .5rem;
		}
	
	div.card.profile-card.notavailable > div.card-body > table.table td {
		border-top-color: #686868 !important;
		color: #000000;
		padding: .5rem;
		}
	
	
	.color_swatch_selector.active {
		background: #ff0000;
		}
	
	.color_swatch_selector:hover .color_scheme_block_edit,
	.color_swatch_selector.active:hover .color_scheme_block_edit {
		display: block;
		}
	
	.color_scheme_block_edit {
		position: absolute;
		height: 2.3rem;
		background: rgba(153, 153, 153, .78);
		top: 0.3rem;
		right: 1.4rem;
		width: 2rem;
		font-size: .8rem;
		line-height: 2.3rem;
		color: #4e4e4e;
		cursor: pointer;
		display: none;
		}
	
	.color_scheme_block.active {
		box-shadow: 0 0px 5px 0 rgba(255, 0, 0, .50)
		}
	
	.dropdown-toggle::after {
		display: inline-flex;
		margin-left: 0.255em;
		vertical-align: 0.255em;
		content: '';
		border-top: 0.3em solid;
		border-right: 0.3em solid transparent;
		border-bottom: 0;
		border-left: 0.3em solid transparent;
		position: absolute;
		right: 0.2rem;
		top: 0.95rem;
		}
	
	.trips-skin .btn-primary.dropdown-toggle.season_toggle,
	.trips-skin .btn-primary.dropdown-toggle.season_toggle:not([disabled]):not(.disabled):active {
		white-space: nowrap !important;
		padding: 9px 20px 9px 5px !important;
		width: 200px !important;
		max-width: 200px !important;
		font-size: .8rem !important;
		font-weight: 400 !important;
		border-radius: 0.25rem !important;
		background-color: #fff !important;
		color: #495057 !important;
		border: 1px solid #ced4da !important;
		box-shadow: none;
		}
	
	.trips-skin .btn-primary.dropdown-toggle.season_toggle.disabled {
		pointer-events: none;
		}
	
	a.season_toggle::after {
		display: inline-flex;
		margin-left: 0.255em;
		vertical-align: 0.255em;
		content: '';
		border-top: 0.4em solid;
		border-right: 0.4em solid transparent;
		border-bottom: 0;
		border-left: 0.4em solid transparent;
		position: absolute;
		right: 9px;
		top: 14px;
		}
	
	a.season_toggle span {
		display: inline-block;
		min-width: 10rem
		max-width: 150px;
		width: 150px;
		font-size: .85rem;
		font-weight: 400;
		-webkit-line-clamp: 1;
		-webkit-box-orient: vertical;
		overflow: hidden;
		text-overflow: clip;
		line-height: 1;
		vertical-align: middle;
		text-align: center;
		white-space: nowrap;
		}
	
	div.dropdown-menu.season_toggle_menu {
		width: 300px;
		min-width: 300px;
		padding-top: 0 !important;
		z-index: 9989;
		background-clip: padding-box;
		border: 1px solid rgba(0, 0, 0, 0.15);
		background-color: #fff;
		font-size: 1rem;
		color: #212529;
		box-shadow: 0 2px 5px 0 rgba(0, 0, 0, .16), 0 2px 10px 0 rgba(0, 0, 0, .12);
		
		}
	
	
	a.dropdown-item.season_toggle_item {
		width: 60px;
		height: 60px;
		font-size: 14px;
		padding: 7px;
		line-height: 46px;
		text-align: center;
		vertical-align: middle !important;
		}
	
	a.dropdown-item.season_toggle_item.active, a.dropdown-item.season_toggle_item:active {
		text-decoration: none;
		border: 1px solid red;
		box-shadow: 0px 0px 2px 1px red;
		box-sizing: border-box;
		opacity: 50%
		}
	
	.card.map-card .card-body {
		top: 37%;
		}
	
	pre[class*="language-"] {
		padding: 1em;
		margin: 0.5em 0;
		overflow: auto;
		border-radius: 0.3em;
		height: 100%;
		min-height: 380px;
		max-height: 380px;
		}
	
	div.panel-actions > a.panel-action.fas {
		display: inline-block;
		padding: 0 0;
		color: #a3afb7;
		text-decoration: none;
		cursor: pointer;
		background-color: transparent;
		margin: 0;
		font-size: 16px;
		height: 16px;
		width: 16px;
		margin-left: 0.5rem;
		}
	
	
	td.selected {
		background: rgba(0, 0, 255, .20)
		}
	
	.fc .fc-toolbar {
		padding-top: 0;
		padding-left: 0;
		padding-right: 0;
		}
	
	.fc-toolbar.fc-header-toolbar {
		margin-bottom: 0.5rem;
		}
	
	.modal-fullscreen {
		position: absolute;
		overflow: hidden;
		top: 0;
		left: 0;
		width: 100%;
		max-width: none;
		height: 100%;
		margin: 0;
		}
	
	#modalHeader {
		
		}
	
	#modalFooter {
		
		
		}
	
	#modalBody {
		overflow: hidden
		
		}
	
	#calendar {
		overflow: auto;
		height: 73vh;
		overflow-y: scroll;
		}
	
	.modal-fullscreen {
		position: absolute;
		overflow: hidden;
		top: 0;
		left: 0;
		width: 100%;
		max-width: none;
		height: 100%;
		margin: 0;
		}
	
	.calendar-loader {
		position: absolute;
		height: 100%;
		width: 100%;
		background: rgba(0, 0, 0, .5);
		z-index: 12;
		top: 0;
		color: #074f95;
		left: 0;
		}
	
	.form-element.element-sm {
		display: -ms-flexbox !important;
		display: flex !important;
		-ms-flex-pack: justify !important;
		justify-content: space-between !important;
		margin-bottom: 0
		}
	
	.form-element.element-sm input {
		background-clip: padding-box;
		font-weight: 400;
		width: 50% !important;
		height: calc(1.5em + 0.5rem + 2px);
		padding: 0.25rem 0.5rem;
		font-size: 0.875rem;
		line-height: 1.25;
		border-radius: 0.2rem;
		color: #495057;
		background-color: #fff;
		border: 1px solid #ced4da;
		transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
		}
	
	.matrix-season-name {
		font-size: .9rem;
		font-weight: 500;
		color: #0a070d;
		}
	
	.matrix-unit-name {
		font-size: .9rem;
		font-weight: 500;
		color: #0a070d;
		}
	
	.form-element.element-sm label {
		width: 50%;
		display: inline-block;
		font-size: .85rem;
		font-weight: 400;
		color: #0a070d;
		}
	
	
	.w-10 {
		width: 10% !important;
		}
	
	.w-20 {
		width: 20% !important;
		}
	
	.w-30 {
		width: 30% !important;
		}
	
	.w-40 {
		width: 40% !important;
		}
	
	.w-60 {
		width: 60% !important;
		}
	
	.w-70 {
		width: 70% !important;
		}
	
	.w-80 {
		width: 80% !important;
		}
	
	.w-90 {
		width: 90% !important;
		}
	
	
	td.disabled-dow {
		background: rgba(242, 242, 242, .9) !important;
		}
	
	
	.truncate-overflow {
		--max-lines: 3;
		max-height: calc(var(--lh) * var(--max-lines));
		
		overflow: hidden;
		text-overflow: ellipsis;
		}
	
	div.datepicker-days table td.disabled {
		background-color: initial !important;
		opacity: initial;
		}
	
	.form-element div.error {
		line-height: 1.2;
		margin-top: 0.5rem;
		}
	
	.modal-dialog .modal-content {
		max-height: 95vh;
		overflow-x: hidden;
		overflow-y: auto;
		}
	
	.btn-heading {
		height: 3rem;
		width: 3rem;
		max-width: 3rem !important;
		max-height: 3rem;
		min-width: 3rem;
		min-height: 3rem;
		padding: 0;
		margin: 0;
		line-height: 3rem;
		vertical-align: middle;
		align-content: center;
		border-radius: 0.5rem;
		font-size: 1rem;
		}
	
	.btn.btn-outline-primary.white {
		background-color: #ffffff !important;
		background: #ffffff !important;
		}
</style>
