<div class="row">
    <div class="col-sm-12 col-md-6 col-lg-6">
        
        <section class="card mb-2">
            <div class="card-body">
                <h5 class="card-title">Seasons</h5>
                <h6 class="card-subtitle mb-2 text-muted">Panel subtitle</h6>
                
                <div class="row">
                    
                    <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-2">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Season 1</h5>
                                <div class="d-flex justify-content-around">
                                    <a href="javascript:void(0);" class="btn btn-danger btn-sm waves-effect waves-light">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-2">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Season 2</h5>
                                <div class="d-flex justify-content-around">
                                    <a href="javascript:void(0);" class="btn btn-danger btn-sm waves-effect waves-light">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-2">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Season 3</h5>
                                <div class="d-flex justify-content-around">
                                    <a href="javascript:void(0);" class="btn btn-danger btn-sm waves-effect waves-light">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-2">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Season 4</h5>
                                <div class="d-flex justify-content-around">
                                    <a href="javascript:void(0);" class="btn btn-danger btn-sm waves-effect waves-light">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-2">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Season 5</h5>
                                <div class="d-flex justify-content-around">
                                    <a href="javascript:void(0);" class="btn btn-danger btn-sm waves-effect waves-light">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="text-right w-100">
                    <a href="javascript:void(0);" class="btn btn-primary btn-sm waves-effect waves-light">Add</a>
                </div>
            
            </div>
        </section>
        
        <section class="card mb-2">
            <div class="card-body">
                <h5 class="card-title">Units</h5>
                <h6 class="card-subtitle mb-2 text-muted">Panel subtitle</h6>
                <hr class="ml-3 mr-3 mt-2 mb-3 color-dark">
                <div class="row">
                    
                    <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-2">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Season 1</h5>
                                <div class="d-flex justify-content-around">
                                    <a href="javascript:void(0);" class="btn btn-danger btn-sm waves-effect waves-light">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-2">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Season 2</h5>
                                <div class="d-flex justify-content-around">
                                    <a href="javascript:void(0);" class="btn btn-danger btn-sm waves-effect waves-light">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-2">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Season 3</h5>
                                <div class="d-flex justify-content-around">
                                    <a href="javascript:void(0);" class="btn btn-danger btn-sm waves-effect waves-light">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-2">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Season 4</h5>
                                <div class="d-flex justify-content-around">
                                    <a href="javascript:void(0);" class="btn btn-danger btn-sm waves-effect waves-light">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-2">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Season 5</h5>
                                <div class="d-flex justify-content-around">
                                    <a href="javascript:void(0);" class="btn btn-danger btn-sm waves-effect waves-light">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="text-right w-100">
                    <a href="javascript:void(0);" class="btn btn-primary btn-sm waves-effect waves-light">Add</a>
                </div>
            
            </div>
        </section>
    
    </div>
    
    <div class="d-none d-md-block col-md-6 col-lg-6">
        
        <div class="row">
            <div class="col py-3 px-lg-5" id='calendar1'>
            
            </div>
            <div class="col-sm-6">
                <div id='calendar2'></div>
            </div>
        </div>
    
    </div>

</div>

<section>
    <div class="row mx-lg-n5">
        <div class="col py-3 px-lg-5">
            Custom column padding
        </div>
        <div class="col py-3 px-lg-5">
            Custom column padding
        </div>
        <div class="col py-3 px-lg-5">
            Custom column padding
        </div>
        <div class="col py-3 px-lg-5">
            Custom column padding
        </div>
    </div>
</section>

<section>
    <div class="card mb-2">
        <div class="card-body">
            <h5 class="card-title">Units</h5>
            <h6 class="card-subtitle mb-2 text-muted">Panel subtitle</h6>
            <p class="card-text">Some quick example text to build on the panel title and make up the bulk of the panel's content.</p>
            <a href="#!" class="card-link mr-3">Card link</a>
            <a href="#!" class="card-link ml-0">Another link</a>
        </div>
    </div>
</section>

<section>
    Variants
</section>

<section>
    Pricing
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card mb-2">
                    <div class="card-body">
                        <h5 class="card-title">Units</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Panel subtitle</h6>
                        <p class="card-text">Some quick example text to build on the panel title and make up the bulk of the panel's content.</p>
                        <a href="#!" class="card-link mr-3">Card link</a>
                        <a href="#!" class="card-link ml-0">Another link</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-2">
                    <div class="card-body">
                        <h5 class="card-title">Units</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Panel subtitle</h6>
                        <p class="card-text">Some quick example text to build on the panel title and make up the bulk of the panel's content.</p>
                        <a href="#!" class="card-link mr-3">Card link</a>
                        <a href="#!" class="card-link ml-0">Another link</a>
                    </div>
                </div>
            </div>
            <div class="w-100"></div>
            <div class="col">col</div>
            <div class="col">col</div>
        </div>
    </div>
</section>
