<?php

?>

<section id="product_edit_details_section" class="section">
    <div class="row">
        <div class="col-12 col-lg-6 mb-2">
            <div class="card card-body">
                <h5 class="card-title">Product Details</h5>
                <div class="row">
                    <div class="col-12 col-lg-4 mb-2">
                    
                    </div>
                    <div class="col-12 col-lg-4 mb-2">
                    
                    </div>
                    <div class="col-12 col-lg-4 mb-2">
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
