<?php
	$categories = (isset($page_data, $page_data["types"], $page_data["types"]["category"])) ? $page_data["types"]["category"] : [];
	$categoryDropDown = "<div class='dropdown-menu'>";
	foreach ($categories as $category) {
		$name = $category["name"];
		$id = $category["id"];
		$icon = $category["icon"];
		
		$categoryDropDown .= "<a id='$id' data-categoryid='$id' data-categoryicon='$icon' data-categoryname='$name' class='dropdown-item category-dropdown-item' href='javascript:void(0);'>$name</a>";
		
	}
	$categoryDropDown .= "</div>";
?>

<form class="card card-body p-1 mb-2" novalidate="novalidate">
	
	<div class="p-2">
		<h5 class="card-title font-weight-bold">
			<span>Product Search</span>
		</h5>
		<h6 class="card-subtitle my-2 text-muted" id="product_search_subtitle">&nbsp;</h6>
	</div>
	
	<hr class="ml-3 mr-3 mt-1 mb-3 color-dark">
	
	<div class="row mx-0">
		<!-- Category Dropdown -->
		<div class="col-6 col-md-4 col-lg-3 col-xl-2 p-1 mb-2">
			<button id="buttonProductSearchCategory" name="buttonProductSearchCategory" class="btn btn-category-picker dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				<i class="fas fa-tag btn-guest-picker-icon"></i>
				<span class="btn-guest-picker-details">
                                    <span class="btn-guest-picker-details-title">Category</span>
                                    <span class="btn-guest-picker-details-info">
                                        <span class="btn-guest-picker-details-info-wrapper">
                                            <span id="product_search_category_display">&nbsp;</span>
                                        </span>
                                    </span>
                                </span>
			</button>
			<?php echo $categoryDropDown; ?>
		
		</div>
		<!-- /Category Dropdown -->
		
		<!-- Product Name -->
		<div class="col-6 col-md-4 col-lg-3 col-xl-2 p-1 mb-2">
			<button type="button" id="buttonProductSearchName" name="buttonProductSearchName" class="btn btn-name-picker name-search" data-placement="bottom" data-toggle="popover" data-container="body" data-html="true">
				<i id="product_search_name_icon_display" class="fas fa-hotel btn-name-picker-icon name-search"></i>
				<span class="btn-name-picker-details name-search">
                    <span class="btn-name-picker-details-title name-search">Name</span>
                    <span class="btn-name-picker-details-info name-search">
                        <span class="btn-name-picker-details-info-wrapper name-search">
                            <span id="product_search_name_display" class="name-search"> Any </span>
                        </span>
                    </span>
                </span>
			</button>
		</div>
		<!-- /Product Name -->
		
		<!-- Product City -->
		<div class="col-6 col-md-4 col-lg-3 col-xl-2 p-1 mb-2" data-hotel="true">
			<button type="button" id="buttonProductSearchCity" name="buttonProductSearchCity" class="btn btn-city-picker" data-placement="bottom" data-toggle="popover" data-container="body" data-html="true">
				<i class="fas fa-map-marker-alt btn-city-picker-icon"></i>
				<span class="btn-city-picker-details">
                    <span class="btn-city-picker-details-title">City</span>
                    <span class="btn-city-picker-details-info">
                        <span class="btn-city-picker-details-info-wrapper">
                            <span id="product_search_city_display"> City Name </span>
                        </span>
                    </span>
                </span>
			</button>
		</div>
		<!-- /Product City -->
		
		<!-- Product Check In -->
		<div class="col-6 col-md-4 col-lg-3 col-xl-2 p-1 mb-2" data-hotel="true">
			<button type="button" id="buttonProductSearchCheckIn" name="buttonProductSearchCheckIn"
			        class="btn btn-check-in-picker">
				<i class="fas fa-calendar btn-guest-picker-icon"></i>
				<span class="btn-guest-picker-details">
                            <span class="btn-guest-picker-details-title">Check in</span>
                            <span class="btn-guest-picker-details-info">
                                <span class="btn-guest-picker-details-info-wrapper">
                                    <span id="product_search_check_in_display"> — / — / — </span>
                                </span>
                            </span>
                        </span>
			</button>
		</div>
		<!-- /Product Check In -->
		
		<!-- Product Check Out -->
		<div class="col-6 col-md-4 col-lg-3 col-xl-2 p-1 mb-2" data-hotel="true">
			<button type="button" id="buttonProductSearchCheckOut" name="buttonProductSearchCheckOut" class="btn btn-check-out-picker" data-date="2021-12-05">
				<i class="fas fa-calendar btn-guest-picker-icon"></i>
				<span class="btn-guest-picker-details">
                            <span class="btn-guest-picker-details-title">Check out</span>
                            <span class="btn-guest-picker-details-info">
                                <span class="btn-guest-picker-details-info-wrapper">
                                    
                                    <span id="product_search_check_out_display" class="btn-guest-picker-details-info-wrapper-rooms"> — / — / — </span>
                                
                                </span>
                                
                            </span>
                            
                        </span>
			
			</button>
		
		</div>
		<!-- /Product Check Out -->
		
		<!-- Product Guests -->
		<div class="col-6 col-md-4 col-lg-3 col-xl-2 p-1 mb-2" data-hotel="true">
			<button type="button" id="buttonProductSearchGuest" name="buttonProductSearchGuest" class="btn btn-guest-picker" data-placement="bottom" data-toggle="popover" data-container="body" data-html="true">
				
				<i class="fas fa-bed btn-guest-picker-icon"></i>
				
				<span class="btn-guest-picker-details">
                            
                            <span class="btn-guest-picker-details-title">Guests</span>
                            
                            <span class="btn-guest-picker-details-info">
                                
                                <span class="btn-guest-picker-details-info-wrapper">
                                    
                                    <span id="product_search_room_quantity_display" class="btn-guest-picker-details-info-wrapper-rooms">1 room,</span>
                                    
                                    <span id="product_search_adult_quantity_display" class="btn-guest-picker-details-info-wrapper-rooms">1 adult,</span>
                                    
                                    <span id="product_search_children_quantity_display" class="btn-guest-picker-details-info-wrapper-rooms">0 children</span>
                                </span>
                                
                            </span>
                            
                        </span>
			
			</button>
		</div>
		<!-- /Product Guests -->
	
	</div>
	
	<div class="text-right w-100">
		<a href="javascript:void(0);" id="button_product_search_panel_hotels_clear" class="btn btn-outline-primary btn-small waves-effect waves-light">
			<i class="fas fa-ban"></i>
			<span class="sm-button-span d-none d-md-inline-block">Clear</span>
		</a>
		<a href="javascript:void(0);" id="button_product_search_panel_hotels_submit" class="btn btn-primary btn-small waves-effect waves-light">
			<i class="fas fa-search"></i>
			<span class="sm-button-span d-none d-md-inline-block">Search</span>
		</a>
	</div>
	
	<div id="form_product_search" class="search-form mb-2">
		<!-- HIDDEN FIELDS -->
		<div class="row mx-0">
			
			<div class="col-sm-3 p-1">
				<label for="form_product_search_hotel_product_city_id" class="dev-element d-none">City Id:</label>
				<input type="hidden" id="form_product_search_hotel_product_city_id" name="form_product_search_hotel_product_city_id" class="form-control dev-element" value="" readonly="readonly"/>
			</div>
			
			<div class="col-sm-3 p-1">
				<label for="form_product_search_hotel_product_category_id" class="dev-element d-none">Category Id:</label>
				<input type="hidden" id="form_product_search_hotel_product_category_id" name="form_product_search_hotel_product_category_id" class="form-control dev-element" value="" readonly="readonly"/>
			</div>
			
			<div class="col-sm-3 p-1">
				<label for="form_product_search_hotel_product_product_id" class="dev-element d-none">Product Id:</label>
				<input type="hidden" id="form_product_search_hotel_product_product_id" name="form_product_search_hotel_product_product_id" class="form-control dev-element" value="" readonly="readonly"/>
			</div>
			
			<div class="col-sm-3 p-1">
				<label for="form_product_search_hotel_product_name" class="dev-element d-none">Name:</label>
				<input type="hidden" id="form_product_search_hotel_product_name" name="form_product_search_hotel_product_name" class="form-control dev-element" value="" readonly="readonly"/>
			</div>
			
			<div class="col-sm-3 p-1">
				<label for="form_product_search_hotel_product_arrive_date" class="dev-element d-none">Arrive:</label>
				<input type="hidden" id="form_product_search_hotel_product_arrive_date" name="form_product_search_hotel_product_arrive_date" class="form-control dev-element" value="" readonly="readonly"/>
			</div>
			
			<div class="col-sm-3 p-1">
				<label for="form_product_search_hotel_product_number_of_children" class="dev-element d-none">Children:</label>
				<input type="hidden" id="form_product_search_hotel_product_number_of_children" name="form_product_search_hotel_product_number_of_children" min="0" class="form-control dev-element" value="0" readonly="readonly"/>
			</div>
			
			<div class="col-sm-3 p-1">
				<label for="form_product_search_hotel_product_number_of_adults" class="dev-element d-none">Adults:</label>
				<input type="hidden" id="form_product_search_hotel_product_number_of_adults" name="form_product_search_hotel_product_number_of_adults" min="1" class="form-control dev-element" value="1" readonly="readonly"/>
			</div>
			
			<div class="col-sm-3 p-1">
				<label for="form_product_search_hotel_product_number_of_rooms" class="dev-element d-none">Rooms:</label>
				<input type="hidden" id="form_product_search_hotel_product_number_of_rooms" name="form_product_search_hotel_product_number_of_rooms" min="1" class="form-control dev-element" value="1" readonly="readonly"/>
			</div>
			
			<div class="col-sm-3 p-1">
				<label for="form_product_search_hotel_product_depart_date" class="dev-element d-none">Depart:</label>
				<input type="hidden" id="form_product_search_hotel_product_depart_date" name="form_product_search_hotel_product_depart_date" class="form-control dev-element" placeholder="" readonly="readonly"/>
			</div>
		
		</div>
		<!-- /HIDDEN FIELDS -->
		
		<!--</form>-->
	</div>

</form>

<section class="card card-body p-0 mb-2" id="product_search_results_block">
	<div class="row">
		
		<div class="col-12 col-md-4 mr-0 pr-1 border-right border-light">
			
			<section class="product-filter">
				<div class="row">
					<div class="col-12">
						<div class="form-element">
							<label for="product_search_results_filter_name">Name:</label>
							<input type="search" id="product_search_results_filter_name" name="product_search_results_filter_name" class="form-control"/>
							<div id="product_search_results_filter_name-error" class="error w-100 text-center"></div>
						</div>
					</div>
				</div>
			</section>
			
			<hr class="ml-3 mr-3 mt-1 mb-3 color-dark"/>
			
			<section class="product-filter">
				<div class="row">
					<div class="col-12">
						<h5 class="h5-responsive">Filter By</h5>
						<h6 class="h6">Ammenities</h6>
					</div>
				</div>
			</section>
		
		</div>
		
		<div class="col-12 col-md-8">
			<div class="p-3">
				<div class="row">
					<div class="col-12 col-md-4">
					</div>
					
					<div class="col-12 col-md-4">
					</div>
					
					<div class="col-12 col-md-4">
						<div class="form-element">
							<label for="product_search_results_sort_by">Sort By:</label>
							<select id="product_search_results_sort_by" name="product_search_results_sort_by" class="form-control">
								<option selected="" value="RECOMMENDED">Recommended</option>
								<option value="PRICE_LOW_TO_HIGH">Price</option>
							</select>
						</div>
					</div>
				</div>
				
				<hr class="ml-3 mr-3 mt-1 mb-3 color-dark">
				
				<div id="product_search_results">
					
					<div class="search-result mb-2">
						<div class="w-100 mb-2">
							<div class="row">
								
								<div class="col-md-3">
									<div class="view overlay rounded z-depth-1 h-auto mb-4">
										<img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Others/img%20(29).jpg" alt="Sample image">
										<a>
											<div class="mask rgba-white-slight waves-effect waves-light"></div>
										</a>
									</div>
								</div>
								
								<div class="col-md-9">
									
									<p class="font-weight-bold dark-grey-text mb-1">Hotel Name</p>
									
									<div class="card-data">
										<ul class="list-unstyled mb-1">
											<li class="comment-date font-small grey-text">
												<i class="fas fa-map-marker-alt"></i> Hotel Address
											</li>
										</ul>
									</div>
									
									<ul class="rating mb-1">
										<li>
											<i class="fas fa-star yellow-text"></i>
										</li>
										<li>
											<i class="fas fa-star yellow-text"></i>
										</li>
										<li>
											<i class="fas fa-star yellow-text"></i>
										</li>
										<li>
											<i class="fas fa-star yellow-text"></i>
										</li>
										<li>
											<i class="fas fa-star yellow-text"></i>
										</li>
									</ul>
									
									<div class="d-flex justify-content-between">
										
										<div class="col-11 text-truncate pl-0 mb-3">
											<a href="javascript:void(0)" class="dark-grey-text">
												At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis
											</a>
										</div>
										
										<a><i class="fas fa-angle-double-right"></i></a>
									
									</div>
								</div>
							
							</div>
						</div>
						
						<div class="w-100 mb-2">
							<div class="table-responsive text-nowrap">
								<div class="d-flex flex-nowrap">
									
									<div class="col-pricing">
										<div class="price">$100</div>
										<div class="date">05/01/2022</div>
									</div>
									
									<div class="col-pricing">
										<div class="price">$100</div>
										<div class="date">05/02/2022</div>
									</div>
									
									<div class="col-pricing">
										<div class="price">$100</div>
										<div class="date">05/03/2022</div>
									</div>
									
									<div class="col-pricing">
										<div class="price">$100</div>
										<div class="date">05/04/2022</div>
									</div>
									
									<div class="col-pricing">
										<div class="price">$100</div>
										<div class="date">05/05/2022</div>
									</div>
								
								</div>
							</div>
						</div>
					</div>
					
					<div class="search-result mb-2">
						<div class="w-100 mb-2">
							<div class="row">
								
								<div class="col-md-3">
									<div class="view overlay rounded z-depth-1 h-auto mb-4">
										<img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Others/img%20(29).jpg" alt="Sample image">
										<a>
											<div class="mask rgba-white-slight waves-effect waves-light"></div>
										</a>
									</div>
								</div>
								
								<div class="col-md-9">
									
									<p class="font-weight-bold dark-grey-text mb-1">Hotel Name</p>
									
									<div class="card-data">
										<ul class="list-unstyled mb-1">
											<li class="comment-date font-small grey-text">
												<i class="fas fa-map-marker-alt"></i> Hotel Address
											</li>
										</ul>
									</div>
									
									<ul class="rating mb-1">
										<li>
											<i class="fas fa-star yellow-text"></i>
										</li>
										<li>
											<i class="fas fa-star yellow-text"></i>
										</li>
										<li>
											<i class="fas fa-star yellow-text"></i>
										</li>
										<li>
											<i class="fas fa-star yellow-text"></i>
										</li>
										<li>
											<i class="fas fa-star yellow-text"></i>
										</li>
									</ul>
									
									<div class="d-flex justify-content-between">
										
										<div class="col-11 text-truncate pl-0 mb-3">
											<a href="javascript:void(0)" class="dark-grey-text">
												At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis
											</a>
										</div>
										
										<a><i class="fas fa-angle-double-right"></i></a>
									
									</div>
								</div>
							
							</div>
						</div>
						
						<div class="w-100 mb-2">
							<div class="table-responsive text-nowrap">
								<div class="d-flex flex-nowrap">
									
									<div class="col-pricing">
										<div class="price">$100</div>
										<div class="date">05/01/2022</div>
									</div>
									
									<div class="col-pricing">
										<div class="price">$100</div>
										<div class="date">05/02/2022</div>
									</div>
									
									<div class="col-pricing">
										<div class="price">$100</div>
										<div class="date">05/03/2022</div>
									</div>
									
									<div class="col-pricing">
										<div class="price">$100</div>
										<div class="date">05/04/2022</div>
									</div>
									
									<div class="col-pricing">
										<div class="price">$100</div>
										<div class="date">05/05/2022</div>
									</div>
								
								</div>
							</div>
						</div>
					</div>
				
				</div>
			
			</div>
		</div>
	</div>
</section>

<!-- Popover Name -->
<div id="popoverNameForm" class="d-none name-popover">
	<div class="popover-head">
		<h5 class="card-title mb-1">
			<span class="cPZwQ">&nbsp;</span>
			<a href="javascript:void(0);" id="formProductSearchNameClose" name="formProductSearchNAmeClose" class="popup-window-button-close fas fa-times" aria-hidden="true"></a>
		</h5>
	</div>
	
	<div class="popover-body">
		
		<form id="product_search_hotel_product_name_form" class="form-inline" role="form" novalidate="novalidate">
			
			<div class="w-100">
				
				<div class="row mb-2">
					
					<div class="col-3">
						<label for="formProductSearchName" class="form-label-popover d-flex justify-content-start">
							<i id="formProductSearchIcon" class="fas fa-hotel mr-3"></i> Name
						</label>
					</div>
					
					<div class="col-9">
						<div class="form-element">
							<input type="search" id="formProductSearchName" name="formProductSearchName" class="form-control w-100"/>
							<input type="hidden" id="formProductSearchNameId" name="formProductSearchNameId" class="form-control w-100"/>
						</div>
					</div>
				
				</div>
				
				<div class="row mb-2">
					
					<div class="col">
						<button type="button" id="formProductSearchNameSubmit" name="formProductSearchNameSubmit" class="btn btn-primary btn-sm btn-block">Update</button>
					</div>
				</div>
			
			</div>
		</form>
	
	</div>

</div>
<!-- /Popover Name -->

<!-- Popover City -->
<div id="popoverCityForm" class="d-none city-popover">
	<div class="popover-head">
		<h5 class="card-title mb-1">
			<span class="cPZwQ">&nbsp;</span>
			<a href="javascript:void(0);" id="formProductSearchCityClose" name="formProductSearchCitylose" class="popup-window-button-close city-popover-close fas fa-times" aria-hidden="true"></a>
		</h5>
	</div>
	
	<div class="popover-body">
		
		<form id="product_search_hotel_product_city_form" class="form-inline" role="form" novalidate="novalidate">
			<div class="w-100">
				
				<div class="row mb-2">
					
					<div class="col-3">
						<label for="formProductSearchCity" class="form-label-popover d-flex justify-content-start">
							<i class="fas fa-map-marker-alt mr-3"></i> City
						</label>
					</div>
					
					<div class="col-9">
						<div class="form-element">
							<input type="search" id="formProductSearchCity" name="formProductSearchCity" class="form-control w-100"/>
							<label for="formProductSearchCityId" class="d-none">
								City Id
							</label>
							<input type="hidden" id="formProductSearchCityId" name="formProductSearchCityId"/>
						</div>
					</div>
				
				</div>
				
				<div class="row mb-2">
					
					<div class="col">
						
						<button type="button" id="formProductSearchCitySubmit" name="formProductSearchCitySubmit" class="btn btn-primary btn-sm btn-block city-popover-submit">Update</button>
					
					</div>
				
				</div>
			
			</div>
		
		</form>
	
	</div>

</div>
<!-- /Popover City -->

<!-- Popover Guest -->
<div id="popoverGuestForm" class="d-none guest-popover">
	
	<div class="popover-head">
		<h5 class="card-title mb-1">
			<span class="cPZwQ">&nbsp;</span>
			<a href="javascript:void(0);" id="formProductSearchGuestClose" name="formProductSearchGuestClose" class="popup-window-button-close fas fa-times" aria-hidden="true"></a>
		</h5>
	</div>
	
	<div class="popover-body">
		
		<form id="myForm" class="form-inline" role="form">
			
			<div class="w-100">
				
				<div class="row mb-2">
					
					<div class="col-3">
						<label for="product_search_room_quantity" class="form-label-popover d-flex justify-content-start">
							<i class="fas fa-bed mr-3"></i> Rooms
						</label>
					</div>
					
					<div class="col-9">
						
						<div class="input-group d-flex justify-content-end number-input">
							
							<div class="input-group-prepend" onclick="
                            let input = this.parentNode.querySelector('input[type=number]');
                            input.stepDown();
                            let min = (input.min)?parseInt(input.min):0;
                            let numberValue = input.value;
                            let roomDisplay = document.getElementById('product_search_room_quantity_display')
                            if(parseInt(numberValue)>1){
                                //roomDisplay.innerText = numberValue+ ' rooms,';
                            } else {
                                //roomDisplay.innerText = numberValue + ' room,';
                            }
                            // -- end --">
                                <span class="input-group-text">
                                    <i class="fas fa-minus"></i>
                                </span>
							</div>
							
							<div class="form-element mb-0">
								<input type="number" id="product_search_room_quantity" name="product_search_room_quantity" class="form-control rounded-0 m-0 quantity" min="1" value="1" onclick="this.select()" onchange="let min = (this.min)?parseInt(this.min):0; if(parseInt(this.value)<min){this.value = 1}" placeholder="">
							</div>
							
							<div class="input-group-append" onclick="
                                let input = this.parentNode.querySelector('input[type=number]');
                                input.stepUp();
                                let min = (input.min)?parseInt(input.min):0;
                                let numberValue = input.value;
                                let roomDisplay = document.getElementById('product_search_room_quantity_display')
                                // -- end --">
                                    <span class="input-group-text">
                                        <i class="fas fa-plus"></i>
                                    </span>
							</div>
						
						</div>
					
					</div>
				
				</div>
				
				<div class="row mb-2">
					
					<div class="col-3">
						<label for="product_search_adult_quantity" class="form-label-popover d-flex justify-content-start">
							<i class="fas fa-user-friends mr-3"></i> Adults
						</label>
					</div>
					
					<div class="col-9">
						
						<div class="input-group d-flex justify-content-end number-input">
							
							<div class="input-group-prepend" onclick="let input = this.parentNode.querySelector('input[type=number]'); input.stepDown()">
                                <span class="input-group-text">
                                    <i class="fas fa-minus"></i>
                                </span>
							</div>
							
							<div class="form-element mb-0">
								<input type="number" id="product_search_adult_quantity" name="product_search_adult_quantity" class="form-control rounded-0 m-0 quantity" min="1" value="1" onclick="this.select()" onchange="let min = (this.min)?parseInt(this.min):0;if(parseInt(this.value)<min){this.value = 1}" placeholder="">
							</div>
							
							<div class="input-group-append" onclick="let input = this.parentNode.querySelector('input[type=number]');input.stepUp()">
                                <span class="input-group-text">
                                    <i class="fas fa-plus"></i>
                                </span>
							</div>
						
						</div>
					
					</div>
				
				</div>
				
				<div class="row mb-2">
					
					<div class="col-3">
						<label for="product_search_clild_quantity" class="form-label-popover d-flex justify-content-start">
							<i class="fas fa-child mr-3"></i> Children
						</label>
					</div>
					
					<div class="col-9">
						
						<div class="input-group d-flex justify-content-end number-input">
							
							<div class="input-group-prepend" onclick="let input = this.parentNode.querySelector('input[type=number]'); input.stepDown()">
                                <span class="input-group-text">
                                    <i class="fas fa-minus"></i>
                                </span>
							</div>
							
							<div class="form-element mb-0">
								<input type="number" id="product_search_clild_quantity" name="product_search_clild_quantity" class="form-control rounded-0 m-0 quantity" min="0" value="0" onclick="this.select()" onchange="let min = (this.min)?parseInt(this.min):0;if(parseInt(this.value)<min){this.value = 1}" placeholder="">
							</div>
							
							<div class="input-group-append" onclick="let input = this.parentNode.querySelector('input[type=number]');input.stepUp()">
                                <span class="input-group-text">
                                    <i class="fas fa-plus"></i>
                                </span>
							</div>
						
						</div>
					
					</div>
				
				</div>
				
				<div class="row mb-2">
					
					<div class="col">
						<button type="button" id="formProductSearchGuestSubmit" name="formProductSearchGuestSubmit" class="btn btn-primary btn-sm btn-block">Update</button>
					</div>
				</div>
			
			</div>
		</form>
	
	</div>

</div>
<!-- /Popover Guest -->


