<section>
    <div class="row">
        
        <!-- Product Short Description -->
        <div class="col-12 col-md-6">
            <div class="card mb-2">
                <div class="card-body">
                    
                    <!-- Title -->
                    <h4 class="card-title">Short Description</h4>
                    <hr>
                    <!-- Text -->
                    
                    <div class="row">
                        <div class="col-12">
                            <div class="form-element">
                                <label for="product_description_short" style="display:none">&nbsp;</label>
                                <textarea id="product_description_short" name="product_description_short" class="md-textarea form-control" rows="4"></textarea>
                                <div id="product_description_short-error" class="error w-100 text-center">&nbsp;</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Product Short Description -->
        
        <!-- Detailed Product Description -->
        <div class="col-12 col-md-6">
            <div class="card mb-2">
                <div class="card-body">
                    <!-- Social shares button -->
                    <a id="button_product_description_long_toggle" class="activator but_toggle waves-effect waves-light mr-4" data-texted="product_description_long">
                        <i class="fas fa-sliders-h"></i>
                    </a>
                    <!-- Title -->
                    <h4 class="card-title">Detailed Description</h4>
                    <hr>
                    <!-- Text -->
                    
                    <div class="row">
                        <div class="col-12">
                            <div class="form-element">
                                <label for="product_description_long" style="display:none">Cover Image:</label>
                                <textarea id="product_description_long" name="product_description_long" class="md-textarea tmceEl form-control" rows="4"></textarea>
                                <div id="product_description_long-error" class="error w-100 text-center">&nbsp;</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Detailed Product Description -->
    
    </div>
    
    <div class="row">
        
        <!-- Product Keywords -->
        <div class="col-12 col-md-6">
            <div id="product_keywords" class="card mb-2 keywords">
                <div class="card-body p-0">
                    <input class="user-release-input form-control form-control-lg" type="text" placeholder="Keywords..."/>
                    <div class="container my-2 chips_container">
                    
                    </div>
                </div>
            </div>
        </div>
        <!-- /Product Keywords -->
    
    </div>
    
    <div class="row">
        
        <!-- Product Amenities -->
        <div class="col-12 col-md-6">
            <div id="product_amenities" class="card mb-2 keywords">
                <div class="card-body p-0">
                    <input class="user-release-input form-control form-control-lg" type="text" placeholder="Amenities..."/>
                    <div class="container my-2 chips_container">
                    
                    </div>
                </div>
            </div>
        </div>
        <!-- /Product Amenities -->
    
    </div>
</section>
