<?php
	$sku = "";
	$name = "";
	$enabled = 1;
	$currency = [];
	$rating_types = [];
	
	if (isset($page_data["product_details"])) {
		$product = $page_data["product_details"];
		
		$sku = $product["sku"];
		$name = $product["name"];
		
		if (isset($page_data["types"]["currency"])) {
			$currency = $page_data["types"]["currency"];
		}
		
		if (isset($page_data["types"]["rating_types"])) {
			$rating_types = $page_data["types"]["rating_types"];
		}
	}

?>

<section id="product_edit_details_section" class="section">
	
	<div class="row">
		
		<div class="col-12 col-md-8 mb-2">
			
			<form class="card card-body">
				<h5 class="card-title">Product Details</h5>
				
				<div class="row">
					
					<!-- Name -->
					<div class="col-12 col-sm-6 col-md-8 mb-2">
						<div class="form-element">
							<label for="product_edit_details_name">Name:</label>
							<input type="text" id="product_edit_details_name" name="product_edit_details_name" value="" class="form-control"/>
							<div id="product_edit_details_name-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Name -->
					
					<!-- Enabled -->
					<div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-4 d-flex align-self-end justify-content-end pb-2 mb-2">
						<div class="form-element">
							<div class="custom-control custom-switch">
								<input id="product_edit_details_enabled" name="product_edit_details_enabled" type="checkbox" value="1" class="custom-control-input">
								<label for="product_edit_details_enabled" class="custom-control-label p-0">Enabled</label>
							</div>
							<div id="product_edit_details_enabled-error" class="error w-100 text-center">&nbsp;</div>
						</div>
					</div>
					<!-- /Enabled -->
				
				</div>
				
				<div class="row">
					
					<!-- Rating Id -->
					<div class="col-12 col-md-4 mb-2">
						<div class="form-element">
							<label for="product_edit_details_rating_types_id">Rating:</label>
							<select id="product_edit_details_rating_types_id" name="product_edit_details_rating_types_id" class="form-control">
								<?php
									$options = "<option  value='' disabled selected>-- Rating --</option>";
									foreach ($rating_types AS $k => $value) {
										$name = $value["name"];
										$val = $value["id"];
										$options .= "<option value='$val'>$name</option>";
									}
									echo $options;
								?>
							</select>
							<div id="product_edit_details_rating_types_id-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Rating Id -->
					
					<!-- Currency Id -->
					<div class="col-12 col-md-4 mb-2">
						<div class="form-element">
							<label for="product_edit_details_currency_id">Currency:</label>
							<select id="product_edit_details_currency_id" name="product_edit_details_currency_id" class="form-control">
								<?php
									$options = "<option  value='' disabled selected>-- Currency --</option>";
									foreach ($currency AS $k => $value) {
										$name = $value["name"];
										$val = $value["id"];
										$options .= "<option value='$val'>$name</option>";
									}
									echo $options;
								?>
							</select>
							<div id="product_edit_details_currency_id-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Currency Id -->
					
					<!-- SKU -->
					<div class="col-12 col-lg-4 mb-2">
						<div class="form-element">
							<label for="product_edit_details_sku">SKU:</label>
							<input type="text" id="product_edit_details_sku" name="product_edit_details_sku" value="" class="form-control" readonly="readonly"/>
							<div id="product_edit_details_sku-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /SKU -->
				
				</div>
			</form>
		
		</div>
		
		<div class="col-12 col-md-4 mb-2">
			
			<ul class="list-group">
				<li class="list-group-item d-flex justify-content-between align-items-center">
					<span id="" class="">Cras justo odio</span>
					<span class="badge badge-primary badge-pill">14</span>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					Dapibus ac facilisis in
					<span class="badge badge-primary badge-pill">2</span>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					dfg
					<span class="badge badge-primary badge-pill">1</span>
				</li>
			</ul>
		
		</div>
	
	</div>

</section>
