<div class="card card-body mb-2 p-0">
    <div class="p-2">
        <h5 class="card-title">Product Seasons</h5>
        
        <div>
            <button type="button" id="table_season_product_edit_add_new_button" class="btn btn-outline-primary btn-sm waves-effect waves-light">New</button>
        </div>
    </div>
    <table id="table_season_product_edit" class="table table-hover w-100 mb-0">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Color Scheme</th>
            <th>Disabled DOW</th>
        </tr>
        </thead>
    </table>
</div>
