<section>
    
    <div class="row">
        <div class="col-12">
            <div class="form-element">
                <label for="product_edit_profile_form_profile_name_filter" class="d-none">Profile Search:</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="fas fa-search" aria-hidden="true"></i>
                        </span>
                    </div>
                    <input type="search" id="product_edit_profile_form_profile_name_filter" name="product_edit_profile_form_profile_name_filter" class="form-control" placeholder="Search Profiles"/>
                    <div class="input-group-append">
                        <button type="button" class="btn btn-md btn-primary m-0 px-3 py-2 z-depth-0 waves-effect" id="button_add_product_profile">
                            <i class="fas fa-plus" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>
                <div id="product_edit_profile_form_profile_name_filter-error" class="error w-100 text-center"></div>
            </div>
        </div>
    </div>
    
    <?php include_once(VIEWS_PATH . "/profiles/tables/product_edit_profile_table.phtml"); ?>
    
    <div class="card mb-2" id="edit_product_profile">
        <div class="card-body">
            <form id="product_edit_profile_form" name="product_edit_profile_form" novalidate>
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-4">
                        <div class="form-element">
                            <label for="product_edit_profile_form_profile_id">Id:</label>
                            <input type="text" id="product_edit_profile_form_profile_id" name="product_edit_profile_form_profile_id" class="form-control"/>
                            <div id="product_edit_profile_form_profile_id-error" class="error w-100 text-center"></div>
                        </div>
                    </div>
                    
                    <div class="col-12 col-md-6 col-lg-4">
                        <div class="form-element">
                            <label for="product_edit_profile_form_profile_name">Name:</label>
                            <input type="text" id="product_edit_profile_form_profile_name" name="product_edit_profile_form_profile_name" class="form-control"/>
                            <div id="product_edit_profile_form_profile_name-error" class="error w-100 text-center"></div>
                        </div>
                    </div>
                
                </div>
            </form>
        </div>
    </div>

</section>
