<?php
    $sales_types = (isset($page_data, $page_data["types"], $page_data["types"]["sales_types"])) ? $page_data["types"]["sales_types"] : [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
    ];
    $allot_by_types = (isset($page_data, $page_data["types"], $page_data["types"]["allot_by"])) ? $page_data["types"]["allot_by"] : [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
    ];
    $sales_types_dropdown = "<option value='' disabled readonly selected>-- Sales Type --</option>";
    $allot_by_type_dropdown = "<option value='' disabled readonly selected>-- Allot By --</option>";
    foreach ($sales_types as $sales_type) {
        $name = $sales_type["name"];
        $id = $sales_type["id"];
        
        $sales_types_dropdown .= "<option value='$id'>$name</option>";
        
    }
    foreach ($allot_by_types as $allot_by_type) {
        $name = $allot_by_type["name"];
        $id = $allot_by_type["id"];
        
        $allot_by_type_dropdown .= "<option value='$id'>$name</option>";
        
    }
    
    //echo "<pre>" . var_export(TYPES, 1) . "</pre>";
    //echo "<pre>" . var_export(TYPES, 1) . "</pre>";
?>

<section>
    <div class="row">
        <div class="col-12">
            <div class="form-element">
                <label for="product_edit_profile_form_profile_name_filter" class="d-none">Profile Search:</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="fas fa-search" aria-hidden="true"></i>
                        </span>
                    </div>
                    <input type="search" id="product_edit_profile_form_profile_name_filter" name="product_edit_profile_form_profile_name_filter" class="form-control" placeholder="Search Profiles"/>
                    <div class="input-group-append">
                        <button type="button" class="btn btn-md btn-primary m-0 px-3 py-2 z-depth-0 waves-effect" id="button_add_product_profile">
                            <i class="fas fa-plus" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>
                <div id="product_edit_profile_form_profile_name_filter-error" class="error w-100 text-center"></div>
            </div>
        </div>
    </div>
    
    <?php include_once(VIEWS_PATH . "/profiles/tables/product_edit_profile_table.phtml"); ?>
    
    <div class="card card-body mb-2" id="edit_product_profile">
        <h5 class="card-title">
            <span>Inventory Profile</span>
            <a type="button" href="javascript:void(0);" id="product_edit_profile_form_close_button" class="panel-button-close fas fa-times" aria-hidden="true"></a>
        </h5>
        <h6 class="card-subtitle mb-2 text-muted" id="display_product_profile_name">&nbsp;</h6>
        <hr class="ml-3 mr-3 mt-1 mb-3 color-dark">
        
        <form id="product_edit_profile_form" novalidate="novalidate">
            
            <div class="card card-body z-depth-0 mb-2">
                
                <div class="row">
                    
                    <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-4 mb-2">
                        <div class="form-element">
                            <label for="product_edit_profile_form_profile_id">Id:</label>
                            <input type="text" id="product_edit_profile_form_profile_id" name="product_edit_profile_form_profile_id" class="form-control" readonly="readonly" disabled="">
                            <div id="product_edit_profile_form_profile_id-error" class="error w-100 text-center"></div>
                        </div>
                    </div>
                    
                    <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-4 mb-2">
                        <div class="form-element">
                            <label for="product_edit_profile_form_profile_name">Name:</label>
                            <input type="text" id="product_edit_profile_form_profile_name" name="product_edit_profile_form_profile_name" class="form-control">
                            <div id="product_edit_profile_form_profile_name-error" class="error w-100 text-center"></div>
                        </div>
                    </div>
                    
                    <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-4 d-flex align-self-end justify-content-end pb-2 mb-2">
                        <div class="form-element">
                            <div class="custom-control custom-switch">
                                <input id="product_edit_profile_form_profile_enabled" name="product_edit_profile_form_profile_enabled" type="checkbox" value="1" class="custom-control-input" readonly="readonly" disabled="">
                                <label for="product_edit_profile_form_profile_enabled" class="custom-control-label p-0">Enabled</label>
                            </div>
                            <div id="product_edit_profile_form_profile_enabled-error" class="error w-100 text-center"></div>
                        </div>
                    </div>
                
                </div>
                
                <div class="row">
                    
                    <div class="col-4 mb-2">
                        <div class="form-element">
                            <label for="product_edit_profile_form_profile_sales_types_id">Sales Type:</label>
                            <select id="product_edit_profile_form_profile_sales_types_id" name="product_edit_profile_form_profile_sales_types_id" class="form-control">
                                <?php echo $sales_types_dropdown; ?>
                            </select>
                            <div id="product_edit_profile_form_profile_sales_types_id-error" class="error w-100 text-center"></div>
                        </div>
                    </div>
                    
                    <div class="col-4 mb-2" id="product_edit_profile_form_profile_allot_by_id_block">
                        
                        <div class="form-element">
                            <label for="product_edit_profile_form_profile_allot_by_id">Allot By:</label>
                            <select id="product_edit_profile_form_profile_allot_by_id" name="product_edit_profile_form_profile_allot_by_id" class="form-control">
                                <?php echo $allot_by_type_dropdown; ?>
                            </select>
                            <div id="product_edit_profile_form_profile_allot_by_id-error" class="error w-100 text-center"></div>
                        </div>
                    
                    </div>
                    
                    <div class="col-4 mb-2" id="product_edit_profile_form_profile_expires_block">
                        
                        <div id="profile_expires" data-label="Expires" data-placeholder="Select Expiration Date"></div>
                    
                    </div>
                    
                    <div class="col-4 mb-2">
                        
                        <div class="form-element" id="product_edit_profile_form_profile_days_out_block">
                            <label for="product_edit_profile_form_profile_days_out" class="">Days Out:</label>
                            <input type="number" id="product_edit_profile_form_profile_days_out" name="product_edit_profile_form_profile_days_out" class="form-control">
                            <div id="product_edit_profile_form_profile_days_out-error" class="error w-100 text-center"></div>
                        </div>
                    
                    </div>
                
                </div>
                
                <div class="row">
                    
                    <div class="col-4 mb-2">
                        
                        <div class="form-element" id="product_edit_profile_form_profile_transfer_sales_types_id_block">
                            <label for="product_edit_profile_form_profile_transfer_sales_types_id">Transfer Sales Type:</label>
                            <select id="product_edit_profile_form_profile_transfer_sales_types_id" name="product_edit_profile_form_profile_transfer_sales_types_id" class="form-control">
                                <?php echo $sales_types_dropdown; ?>
                            </select>
                            <div id="product_edit_profile_form_profile_transfer_sales_types_id-error" class="error w-100 text-center"></div>
                        </div>
                    
                    </div>
                    
                    <div class="col-4 mb-2" id="product_edit_profile_form_profile_quantity_block">
                        
                        <div class="form-element" id="product_edit_profile_form_profile_quantity_block">
                            <label for="product_edit_profile_form_profile_quantity" class="">Quantity Allotted:</label>
                            <input type="number" id="product_edit_profile_form_profile_quantity" name="product_edit_profile_form_profile_quantity" class="form-control">
                            <div id="product_edit_profile_form_profile_quantity-error" class="error w-100 text-center"></div>
                        </div>
                    
                    </div>
                    
                    <div class="col-4 mb-2" id="product_edit_profile_form_profile_release_amt_block">
                        
                        <div class="form-element">
                            <label for="product_edit_profile_form_profile_release_amt" class="">Amount to Release:</label>
                            <input type="number" id="product_edit_profile_form_profile_release_amt" name="product_edit_profile_form_profile_release_amt" class="form-control">
                            <div id="product_edit_profile_form_profile_release_amt-error" class="error w-100 text-center"></div>
                        </div>
                    
                    </div>
                
                </div>
                <!-- /Allotment Fields -->
                
                <!-- Additional Fields -->
                <div class="accordion md-accordion" id="accordionEx" role="tablist" aria-multiselectable="true">
                    
                    <!-- Accordion card -->
                    <div class="card card-body border grey lighten-3 z-depth-0 mb-2 ">
                        
                        <!-- Card header -->
                        <div class="card-header p-0 m-0" role="tab" id="headingOne1">
                            <a data-toggle="collapse" data-parent="#accordionEx" href="#collapseOne1" aria-expanded="false" aria-controls="collapseOne1">
                                <h5 class="mb-0">
                                    Additional Fields <i class="fas fa-angle-down rotate-icon"></i>
                                </h5>
                            </a>
                        </div>
                        
                        <!-- Card body -->
                        <div id="collapseOne1" class="collapse" role="tabpanel" aria-labelledby="headingOne1" data-parent="#accordionEx">
                            <hr>
                            <div class="row">
                                <div class="col-12 mb-2">
                                    <div id="product_edit_profile_form_profile_checkin_dow" class="">
                                        <div class="row">
                                            <div class="col-12 col-md-2 col-xl-3"><label>Checkin DOW:</label></div>
                                            <div class="col-12 col-md-10 col-xl-9">
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkin_dowdow_select_all" name="checkin_dowdow_select_all" value="*"><label class="custom-control-label" for="checkin_dowdow_select_all">All</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkin_dowdow_select_sun" name="checkin_dowdow_select_sun" value="0"><label class="custom-control-label" for="checkin_dowdow_select_sun">Sun</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkin_dowdow_select_mon" name="checkin_dowdow_select_mon" value="1"><label class="custom-control-label" for="checkin_dowdow_select_mon">Mon</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkin_dowdow_select_tue" name="checkin_dowdow_select_tue" value="2"><label class="custom-control-label" for="checkin_dowdow_select_tue">Tue</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkin_dowdow_select_wed" name="checkin_dowdow_select_wed" value="3"><label class="custom-control-label" for="checkin_dowdow_select_wed">Wed</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkin_dowdow_select_thu" name="checkin_dowdow_select_thu" value="4"><label class="custom-control-label" for="checkin_dowdow_select_thu">Thu</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkin_dowdow_select_fri" name="checkin_dowdow_select_fri" value="5"><label class="custom-control-label" for="checkin_dowdow_select_fri">Fri</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkin_dowdow_select_sat" name="checkin_dowdow_select_sat" value="6"><label class="custom-control-label" for="checkin_dowdow_select_sat">Sat</label></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-12 mb-2">
                                    <div id="product_edit_profile_form_profile_checkout_dow" class="">
                                        <div class="row">
                                            <div class="col-12 col-md-2 col-xl-3"><label>Checkout DOW:</label></div>
                                            <div class="col-12 col-md-10 col-xl-9">
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkout_dowdow_select_all" name="checkout_dowdow_select_all" value="*"><label class="custom-control-label" for="checkout_dowdow_select_all">All</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkout_dowdow_select_sun" name="checkout_dowdow_select_sun" value="0"><label class="custom-control-label" for="checkout_dowdow_select_sun">Sun</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkout_dowdow_select_mon" name="checkout_dowdow_select_mon" value="1"><label class="custom-control-label" for="checkout_dowdow_select_mon">Mon</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkout_dowdow_select_tue" name="checkout_dowdow_select_tue" value="2"><label class="custom-control-label" for="checkout_dowdow_select_tue">Tue</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkout_dowdow_select_wed" name="checkout_dowdow_select_wed" value="3"><label class="custom-control-label" for="checkout_dowdow_select_wed">Wed</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkout_dowdow_select_thu" name="checkout_dowdow_select_thu" value="4"><label class="custom-control-label" for="checkout_dowdow_select_thu">Thu</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkout_dowdow_select_fri" name="checkout_dowdow_select_fri" value="5"><label class="custom-control-label" for="checkout_dowdow_select_fri">Fri</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="checkout_dowdow_select_sat" name="checkout_dowdow_select_sat" value="6"><label class="custom-control-label" for="checkout_dowdow_select_sat">Sat</label></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-12 mb-2">
                                    <div id="product_edit_profile_form_profile_departure_dow" class="">
                                        <div class="row">
                                            <div class="col-12 col-md-2 col-xl-3"><label>Departure DOW:</label></div>
                                            <div class="col-12 col-md-10 col-xl-9">
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="departure_dowdow_select_all" name="departure_dowdow_select_all" value="*"><label class="custom-control-label" for="departure_dowdow_select_all">All</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="departure_dowdow_select_sun" name="departure_dowdow_select_sun" value="0"><label class="custom-control-label" for="departure_dowdow_select_sun">Sun</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="departure_dowdow_select_mon" name="departure_dowdow_select_mon" value="1"><label class="custom-control-label" for="departure_dowdow_select_mon">Mon</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="departure_dowdow_select_tue" name="departure_dowdow_select_tue" value="2"><label class="custom-control-label" for="departure_dowdow_select_tue">Tue</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="departure_dowdow_select_wed" name="departure_dowdow_select_wed" value="3"><label class="custom-control-label" for="departure_dowdow_select_wed">Wed</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="departure_dowdow_select_thu" name="departure_dowdow_select_thu" value="4"><label class="custom-control-label" for="departure_dowdow_select_thu">Thu</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="departure_dowdow_select_fri" name="departure_dowdow_select_fri" value="5"><label class="custom-control-label" for="departure_dowdow_select_fri">Fri</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="departure_dowdow_select_sat" name="departure_dowdow_select_sat" value="6"><label class="custom-control-label" for="departure_dowdow_select_sat">Sat</label></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-12 mb-2">
                                    <div id="product_edit_profile_form_profile_return_dow" class="">
                                        <div class="row">
                                            <div class="col-12 col-md-2 col-xl-3"><label>Return DOW:</label></div>
                                            <div class="col-12 col-md-10 col-xl-9">
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="return_dowdow_select_all" name="return_dowdow_select_all" value="*"><label class="custom-control-label" for="return_dowdow_select_all">All</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="return_dowdow_select_sun" name="return_dowdow_select_sun" value="0"><label class="custom-control-label" for="return_dowdow_select_sun">Sun</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="return_dowdow_select_mon" name="return_dowdow_select_mon" value="1"><label class="custom-control-label" for="return_dowdow_select_mon">Mon</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="return_dowdow_select_tue" name="return_dowdow_select_tue" value="2"><label class="custom-control-label" for="return_dowdow_select_tue">Tue</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="return_dowdow_select_wed" name="return_dowdow_select_wed" value="3"><label class="custom-control-label" for="return_dowdow_select_wed">Wed</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="return_dowdow_select_thu" name="return_dowdow_select_thu" value="4"><label class="custom-control-label" for="return_dowdow_select_thu">Thu</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="return_dowdow_select_fri" name="return_dowdow_select_fri" value="5"><label class="custom-control-label" for="return_dowdow_select_fri">Fri</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="return_dowdow_select_sat" name="return_dowdow_select_sat" value="6"><label class="custom-control-label" for="return_dowdow_select_sat">Sat</label></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-12 mb-2">
                                    <div id="product_edit_profile_form_profile_weekday_dow" class="">
                                        <div class="row">
                                            <div class="col-12 col-md-2 col-xl-3"><label>Weekdays:</label></div>
                                            <div class="col-12 col-md-10 col-xl-9">
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="weekday_dowdow_select_all" name="weekday_dowdow_select_all" value="*"><label class="custom-control-label" for="weekday_dowdow_select_all">All</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="weekday_dowdow_select_sun" name="weekday_dowdow_select_sun" value="0"><label class="custom-control-label" for="weekday_dowdow_select_sun">Sun</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="weekday_dowdow_select_mon" name="weekday_dowdow_select_mon" value="1"><label class="custom-control-label" for="weekday_dowdow_select_mon">Mon</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="weekday_dowdow_select_tue" name="weekday_dowdow_select_tue" value="2"><label class="custom-control-label" for="weekday_dowdow_select_tue">Tue</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="weekday_dowdow_select_wed" name="weekday_dowdow_select_wed" value="3"><label class="custom-control-label" for="weekday_dowdow_select_wed">Wed</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="weekday_dowdow_select_thu" name="weekday_dowdow_select_thu" value="4"><label class="custom-control-label" for="weekday_dowdow_select_thu">Thu</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="weekday_dowdow_select_fri" name="weekday_dowdow_select_fri" value="5"><label class="custom-control-label" for="weekday_dowdow_select_fri">Fri</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="weekday_dowdow_select_sat" name="weekday_dowdow_select_sat" value="6"><label class="custom-control-label" for="weekday_dowdow_select_sat">Sat</label></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-12 mb-2">
                                    <div id="product_edit_profile_form_profile_inc_days_dow" class="w-100">
                                        <div class="row">
                                            <div class="col-12 col-md-2 col-xl-3"><label>Included Days:</label></div>
                                            <div class="col-12 col-md-10 col-xl-9">
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="inc_days_dowdow_select_all" name="inc_days_dowdow_select_all" value="*"><label class="custom-control-label" for="inc_days_dowdow_select_all">All</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="inc_days_dowdow_select_sun" name="inc_days_dowdow_select_sun" value="0"><label class="custom-control-label" for="inc_days_dowdow_select_sun">Sun</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="inc_days_dowdow_select_mon" name="inc_days_dowdow_select_mon" value="1"><label class="custom-control-label" for="inc_days_dowdow_select_mon">Mon</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="inc_days_dowdow_select_tue" name="inc_days_dowdow_select_tue" value="2"><label class="custom-control-label" for="inc_days_dowdow_select_tue">Tue</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="inc_days_dowdow_select_wed" name="inc_days_dowdow_select_wed" value="3"><label class="custom-control-label" for="inc_days_dowdow_select_wed">Wed</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="inc_days_dowdow_select_thu" name="inc_days_dowdow_select_thu" value="4"><label class="custom-control-label" for="inc_days_dowdow_select_thu">Thu</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="inc_days_dowdow_select_fri" name="inc_days_dowdow_select_fri" value="5"><label class="custom-control-label" for="inc_days_dowdow_select_fri">Fri</label></div>
                                                <div class="custom-control custom-checkbox custom-control-inline"><input type="checkbox" class="custom-control-input dow_select" id="inc_days_dowdow_select_sat" name="inc_days_dowdow_select_sat" value="6"><label class="custom-control-label" for="inc_days_dowdow_select_sat">Sat</label></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-3 mb-2">
                                    <div class="form-element">
                                        <label for="product_edit_profile_form_profile_min_length_days" class="">Min Length Days:</label>
                                        <input type="number" id="product_edit_profile_form_profile_min_length_days" name="product_edit_profile_form_profile_min_length_days" class="form-control">
                                        <div id="product_edit_profile_form_profile_min_length_days-error" class="error w-100 text-center"></div>
                                    </div>
                                </div>
                                
                                <div class="col-3 mb-2">
                                    <div class="form-element">
                                        <label for="product_edit_profile_form_profile_min_duration" class="">Minimum Duration:</label>
                                        <input type="number" id="product_edit_profile_form_profile_min_duration" name="product_edit_profile_form_profile_min_duration" class="form-control">
                                        <div id="product_edit_profile_form_profile_min_duration-error" class="error w-100 text-center"></div>
                                    </div>
                                </div>
                                
                                <div class="col-3 mb-2">
                                    <div class="form-element">
                                        <label for="product_edit_profile_form_profile_max_duration" class="">Maximum Duration:</label>
                                        <input type="number" id="product_edit_profile_form_profile_max_duration" name="product_edit_profile_form_profile_max_duration" class="form-control">
                                        <div id="product_edit_profile_form_profile_max_duration-error" class="error w-100 text-center"></div>
                                    </div>
                                </div>
                                
                                <div class="col-3 mb-2">
                                    <div class="form-element">
                                        <label for="product_edit_profile_form_profile_equal_duration" class="">Equals Duration:</label>
                                        <input type="number" id="product_edit_profile_form_profile_equal_duration" name="product_edit_profile_form_profile_equal_duration" class="form-control">
                                        <div id="product_edit_profile_form_profile_equal_duration-error" class="error w-100 text-center"></div>
                                    </div>
                                </div>
                            
                            </div>
                            
                            <div class="row">
                                
                                <div class="col-4 mb-2">
                                    <div id="profile_advanced_booking_date" data-label="Advanced Booking Date" data-placeholder="Select Date"></div>
                                </div>
                                
                                <div class="col-4 mb-2">
                                    <div class="form-element">
                                        <label for="product_edit_profile_form_profile_advanced_booking_min" class="">Advanced Booking Min:</label>
                                        <input type="number" id="product_edit_profile_form_profile_advanced_booking_min" name="product_edit_profile_form_profile_advanced_booking_min" class="form-control">
                                        <div id="product_edit_profile_form_profile_advanced_booking_min-error" class="error w-100 text-center"></div>
                                    </div>
                                </div>
                                
                                <div class="col-4 mb-2">
                                    <div class="form-element">
                                        <label for="product_edit_profile_form_profile_advanced_booking_max" class="">Advanced Booking Max:</label>
                                        <input type="number" id="product_edit_profile_form_profile_advanced_booking_max" name="product_edit_profile_form_profile_advanced_booking_max" class="form-control">
                                        <div id="product_edit_profile_form_profile_advanced_booking_max-error" class="error w-100 text-center"></div>
                                    </div>
                                </div>
                            </div>
                        
                        </div>
                    
                    </div>
                    <!-- Accordion card -->
                
                </div>
                <!-- /Additional Fields -->
            
            </div>
            
            <div class="text-right w-100">
                <a href="javascript:void(0);" id="product_edit_profile_form_clear_button" class="btn btn-flat primary-text text-center p-1 mx-0 mb-0 waves-effect waves-light">clear</a>
                <a href="javascript:void(0);" id="product_edit_profile_form_submit_button" class="btn btn-primary btn-sm waves-effect waves-light">Save</a>
            </div>
        
        </form>
    
    </div>

</section>

<script type="text/javascript">

</script>

<script type="text/javascript">
    const InventoryProfile = (function () {
        'use strict'
        const _table_profile_product_edit_add_new_button = document.getElementById("table_profile_product_edit_add_new_button")
        const _edit_product_profile = document.getElementById("edit_product_profile")
        const _product_edit_profile_form_profile_transfer_sales_types_id_block = document.getElementById("product_edit_profile_form_profile_transfer_sales_types_id_block")
        const _product_edit_profile_form_profile_allot_by_id_block = document.getElementById("product_edit_profile_form_profile_allot_by_id_block")
        const _product_edit_profile_form_profile_name_filter = document.getElementById("product_edit_profile_form_profile_name_filter")
        const _table_profile_product_edit = document.getElementById("table_profile_product_edit")
        const _product_edit_profile_form_profile_days_out_block = document.getElementById("product_edit_profile_form_profile_days_out_block")
        const _product_edit_profile_form_profile_expires_block = document.getElementById("product_edit_profile_form_profile_expires_block")
        const _product_edit_profile_form_profile_quantity_block = document.getElementById("product_edit_profile_form_profile_quantity_block")
        const _product_edit_profile_form_profile_release_amt_block = document.getElementById("product_edit_profile_form_profile_release_amt_block")
        const _product_edit_profile_form = document.getElementById("product_edit_profile_form")
        const _product_edit_profile_form_profile_id = document.getElementById('product_edit_profile_form_profile_id')
        const _product_edit_profile_form_profile_name = document.getElementById('product_edit_profile_form_profile_name')
        const _product_edit_profile_form_profile_enabled = document.getElementById('product_edit_profile_form_profile_enabled')
        const _product_edit_profile_form_profile_sales_types_id = document.getElementById('product_edit_profile_form_profile_sales_types_id')
        const _product_edit_profile_form_profile_allot_by_id = document.getElementById('product_edit_profile_form_profile_allot_by_id')
        const _product_edit_profile_form_profile_transfer_sales_types_id = document.getElementById('product_edit_profile_form_profile_transfer_sales_types_id')
        const _product_edit_profile_form_profile_days_out = document.getElementById('product_edit_profile_form_profile_days_out')
        const _product_edit_profile_form_profile_quantity = document.getElementById('product_edit_profile_form_profile_quantity')
        const _product_edit_profile_form_profile_release_amt = document.getElementById('product_edit_profile_form_profile_release_amt')
        const _product_edit_profile_form_profile_min_length_days = document.getElementById('product_edit_profile_form_profile_min_length_days')
        const _product_edit_profile_form_profile_min_duration = document.getElementById('product_edit_profile_form_profile_min_duration')
        const _product_edit_profile_form_profile_max_duration = document.getElementById('product_edit_profile_form_profile_max_duration')
        const _product_edit_profile_form_profile_equal_duration = document.getElementById('product_edit_profile_form_profile_equal_duration')
        const _product_edit_profile_form_profile_advanced_booking_min = document.getElementById('product_edit_profile_form_profile_advanced_booking_min')
        const _product_edit_profile_form_profile_advanced_booking_max = document.getElementById('product_edit_profile_form_profile_advanced_booking_max')
        const _product_edit_profile_form_profile_checkin_dow = document.getElementById('product_edit_profile_form_profile_checkin_dow')
        const _product_edit_profile_form_profile_checkout_dow = document.getElementById('product_edit_profile_form_profile_checkout_dow')
        const _product_edit_profile_form_profile_departure_dow = document.getElementById('product_edit_profile_form_profile_departure_dow')
        const _product_edit_profile_form_profile_return_dow = document.getElementById('product_edit_profile_form_profile_return_dow')
        const _product_edit_profile_form_profile_inc_days_dow = document.getElementById('product_edit_profile_form_profile_inc_days_dow')
        const _product_edit_profile_form_profile_weekday_dow = document.getElementById('product_edit_profile_form_profile_weekday_dow')
        const _product_edit_profile_form_close_button = document.getElementById('product_edit_profile_form_close_button')
        const _button_add_product_profile = document.getElementById("button_add_product_profile")
        const _product_edit_profile_form_clear_button = document.getElementById('product_edit_profile_form_clear_button')
        const _product_edit_profile_form_submit_button = document.getElementById('product_edit_profile_form_submit_button')
        const _product_id = document.getElementById("product_id")
        
        let $table_profile_product_edit = $(_table_profile_product_edit)
        let user_id = (document.getElementById('user_id')) ? (!isNaN(parseInt(document.getElementById('user_id').value))) ? parseInt(document.getElementById('user_id').value) : 4 : 4
        let form_rules = {
            rules: {
                product_edit_profile_form_profile_sales_types_id: {
                    required: true,
                },
                product_edit_profile_form_profile_allot_by_id: {
                    required: function (element) {
                        return ($(_product_edit_profile_form_profile_sales_types_id).val() !== "" && $(_product_edit_profile_form_profile_sales_types_id).val() === 1 || $(_product_edit_profile_form_profile_sales_types_id).val() === "1")
                    },
                },
                profile_expires: {
                    required: function (element) {
                        return ($(_product_edit_profile_form_profile_allot_by_id).val() !== "" && $(_product_edit_profile_form_profile_allot_by_id).val() === 1 || $(_product_edit_profile_form_profile_allot_by_id).val() === "1")
                    },
                },
                product_edit_profile_form_profile_days_out: {
                    required: function (element) {
                        return ($(_product_edit_profile_form_profile_allot_by_id).val() !== "" && $(_product_edit_profile_form_profile_allot_by_id).val() === 2 || $(_product_edit_profile_form_profile_allot_by_id).val() === "2")
                    },
                    number: true,
                    min: 1,
                },
                product_edit_profile_form_profile_name: {
                    required: true,
                },
            },
            messages: {
                product_edit_profile_form_profile_sales_types_id: {
                    required: 'Field Required',
                },
                product_edit_profile_form_profile_allot_by_id: {
                    required: 'Field Required',
                },
                profile_expires: {
                    required: 'Field Required',
                },
                product_edit_profile_form_profile_days_out: {
                    required: 'Field Required',
                },
                product_edit_profile_form_profile_name: {
                    required: 'Field Required',
                },
            },
        }
        let globalSelectedProfile = false
        let checkin_dow, checkout_dow, departure_dow, return_dow, weekday_dow, inc_days_dow
        
        $(_button_add_product_profile)
          .on("click", function () {
              //Console.log("InventoryProfile.button_add_product_profile: click()", {})
              populateInventoryProfileForm()
          })
        
        $(_table_profile_product_edit_add_new_button)
          .on("click", function () {
              //Console.log("InventoryProfile.table_profile_product_edit_add_new_button: click()", {})
              _product_edit_profile_form_profile_name_filter.value = ""
              $table_profile_product_edit.clearSelectedRows()
              populateInventoryProfileForm()
          })
        
        $(_product_edit_profile_form_clear_button)
          .on("click", function () {
              //Console.log("InventoryProfile.product_edit_profile_form_clear_button: click()", {})
              $table_profile_product_edit.clearSelectedRows()
              clearInventoryProfileForm()
              _product_edit_profile_form_profile_name_filter.value = ""
          })
        
        $(_product_edit_profile_form_submit_button)
          .on("click", function () {
              //Console.log("InventoryProfile.product_edit_profile_form_submit_button: click()", {})
              save()
          })
        
        $(_product_edit_profile_form_close_button)
          .on("click", function () {
              //Console.log("InventoryProfile.product_edit_profile_form_close_button: click()", {})
              $table_profile_product_edit.clearSelectedRows()
              clearInventoryProfileForm()
              setFormElementDisplay()
              hideForm()
              _product_edit_profile_form_profile_name_filter.value = ""
          })
        
        $(_product_edit_profile_form_profile_sales_types_id)
          .on("change", function () {
              //Console.log("InventoryProfile.product_edit_profile_form_profile_sales_types_id: change()", {})
              setFormElementDisplay()
              InventoryProfile.expiration_date.value("")
              _product_edit_profile_form_profile_days_out.value = ""
              _product_edit_profile_form_profile_allot_by_id.value = ""
          })
        
        $(_product_edit_profile_form_profile_allot_by_id)
          .on("change", function () {
              //Console.log("InventoryProfile.product_edit_profile_form_profile_allot_by_id: change()", {})
              setFormElementDisplay()
              InventoryProfile.expiration_date.value("")
              _product_edit_profile_form_profile_days_out.value = ""
          })
        
        $(_product_edit_profile_form_profile_transfer_sales_types_id)
          .on("change", function () {
              //Console.log("InventoryProfile.product_edit_profile_form_profile_transfer_sales_types_id: change()", {})
          })
        
        //
        
        const defaultDetail = function () {
            return {
                id: null,
                allot_by_id: null,
                sales_types_id: null,
                name: null,
                quantity: null,
                expires: null,
                transfer_sales_types_id: null,
                release_amt: null,
                min_length_days: null,
                checkin_dow: [0, 1, 2, 3, 4, 5, 6],
                checkout_dow: [0, 1, 2, 3, 4, 5, 6],
                departure_dow: [0, 1, 2, 3, 4, 5, 6],
                return_dow: [0, 1, 2, 3, 4, 5, 6],
                inc_days_dow: [0, 1, 2, 3, 4, 5, 6],
                weekday_dow: [0, 1, 2, 3, 4, 5, 6],
                min_duration: null,
                max_duration: null,
                equal_duration: null,
                advanced_booking_min: null,
                advanced_booking_max: null,
                advanced_booking_date: null,
                
                days_out: null,
                enabled: 1,
                date_created: formatDateMySQL(),
                created_by: user_id,
                date_modified: formatDateMySQL(),
                modified_by: user_id,
                note: null,
                sales_types_details: {},
                allot_by_details: {},
                tranfer_sales_type_details: {},
            }
        }
        
        const initAutoComplete = function () {
            //Console.log('InventoryProfile.initAutoComplete()', InventoryProfile)
            let product_id = (!isNaN(parseInt(_product_id.value))) ? parseInt(_product_id.value) : null
            
            $(_product_edit_profile_form_profile_name_filter)
              .on("click", function () {
                  $(this).select()
              })
              .on("search", function () {
                  $table_profile_product_edit.clearSelectedRows()
                  resetInventoryProfileForm()
              })
              .on("change", function () {
                  setTimeout(function () {
                      //*
                      let profile_name = _product_edit_profile_form_profile_name_filter.value
                      
                      if (globalSelectedProfile === false) {
                          if (profile_name === "") {
                              globalSelectedProfile = false
                              $table_profile_product_edit.clearSelectedRows()
                              resetInventoryProfileForm()
                          } else {
                              nameExists(profile_name)
                          }
                      }
                      //*/
                  }, 200)
                  if (_product_edit_profile_form_profile_name_filter.value === "") {
                      $table_profile_product_edit.clearSelectedRows()
                      resetInventoryProfileForm()
                  }
              })
              .autocomplete({
                  serviceUrl: "/api/v1.0/autocomplete/profiles",
                  minChars: 2,
                  cache: false,
                  dataType: "json",
                  triggerSelectOnValidInput: false,
                  params: { "product_id": product_id },
                  paramName: "st",
                  onSelect: function (suggestion) {
                      if (!suggestion.data) {
                          return
                      }
                      $table_profile_product_edit.clearSelectedRows()
                      let id = (!isNaN(parseInt(suggestion.data.id))) ? parseInt(suggestion.data.id) : null
                      let inventory_profile = InventoryProfile.all.get(id)
                      
                      if (inventory_profile) {
                          $table_profile_product_edit.loadRow(inventory_profile)
                          populateInventoryProfileForm(inventory_profile)
                          return
                      }
                      
                      populateInventoryProfileForm()
                      _product_edit_profile_form_profile_name.value = _product_edit_profile_form_profile_name_filter.value
                  },
              })
        }
        
        const nameExists = function (name) {
            //Console.log("InventoryProfile.nameExists(profile_name)", name)
            if (name && name !== "") {
                /**
                 * data to send to the server
                 *
                 * @type {{name}}
                 */
                let dataToSend = {
                    name: name,
                    product_id: (!isNaN(parseInt(_product_id.value))) ? parseInt(_product_id.value) : null,
                }
                
                fetchByName(dataToSend, function (data) {
                    let profile = null
                    
                    if (data && data[0]) {
                        profile = data
                        if (data[0]) {
                            profile = data[0]
                        }
                    }
                    
                    if (profile) {
                        let hasProfile = InventoryProfile.all.get(parseInt(profile.id))
                        let detail
                        
                        if (hasProfile) {
                            detail = set(hasProfile)
                            $table_profile_product_edit.loadRow(detail)
                            populateInventoryProfileForm(detail)
                            return
                        }
                        
                        populateInventoryProfileForm()
                        _product_edit_profile_form_profile_name.value = name
                    }
                })
            }
        }
        
        const fetchByName = function (dataToSend, callback) {
            let url = "/api/v1.0/profiles/validate"
            
            if (dataToSend) {
                try {
                    sendGetRequest(url, dataToSend, function (data, status, xhr) {
                        if (data) {
                            return callback(data)
                        } else {
                            return handleProfileError("Oops: 1")
                        }
                    })
                } catch (e) {
                    Console.log(e)
                    return handleProfileError("Error Validating InventoryProfile")
                }
            } else {
                return handleProfileError("Error Loading InventoryProfile - Missing Data")
            }
        }
        
        const buildInventoryProfileTable = function () {
            //Console.log("InventoryProfile.buildInventoryProfileTable()", InventoryProfile)
            $table_profile_product_edit = $(_table_profile_product_edit).table({
                table_type: "display_list",
                data: [],
                columnDefs: [
                    {
                        title: "Name",
                        targets: 0,
                        data: "name",
                        render: function (data, type, row, meta) {
                            return "<span style='white-space: nowrap;'>" + data + "</span>"
                        },
                    },
                    {
                        title: "Sales Types",
                        targets: 1,
                        data: "sales_types_details",
                        render: function (data, type, row, meta) {
                            //Console.log("sales_types_details", data)
                            let name = (data.name) ? data.name : "N/A"
                            
                            return "<span style='white-space: nowrap;'>" + name + "</span>"
                        },
                    },
                    {
                        title: "Allot By",
                        targets: 2,
                        data: "allot_by_id",
                        render: function (data, type, row, meta) {
                            let nights = "N/A"
                            if (data === null) {
                                nights = "N/A"
                            } else {
                                nights = Types.allot_by.get(data)
                                if (nights) {
                                    nights = nights.name
                                } else {
                                    nights = "N/A"
                                }
                            }
                            return "<span style='white-space: nowrap;'>" + nights + "</span>"
                        },
                    },
                    {
                        title: "Expires",
                        targets: 3,
                        data: "expires",
                        render: function (data, type, row, meta) {
                            let expires
                            if (data === null) {
                                expires = "N/A"
                            } else {
                                let new_string = data.replace(/-|\s/g, "")
                                expires = moment(new_string).format('YYYY-MM-DD')
                            }
                            return "<span style='white-space: nowrap;'>" + expires + "</span>"
                        },
                    },
                    {
                        title: "Release",
                        targets: 4,
                        data: "release_amt",
                        render: function (data, type, row, meta) {
                            let expires = "N/A"
                            if (data) {
                                expires = data
                            }
                            return "<span style='white-space: nowrap;'>" + expires + "</span>"
                        },
                    },
                ],
                rowClick: InventoryProfile.edit,
            })
        }
        
        const buildInventoryProfileRecord = function () {
            let isValid = validateInventoryProfileForm()
            if (isValid) {
                return remove_nulls({
                    id: (!isNaN(parseInt(_product_edit_profile_form_profile_id.value))) ? parseInt(_product_edit_profile_form_profile_id.value) : null,
                    name: (_product_edit_profile_form_profile_name.value !== "") ? _product_edit_profile_form_profile_name.value : null,
                    product_id: (!isNaN(parseInt(_product_id.value))) ? parseInt(_product_id.value) : null,
                    sales_types_id: (!isNaN(parseInt(_product_edit_profile_form_profile_sales_types_id.value))) ? parseInt(_product_edit_profile_form_profile_sales_types_id.value) : null,
                    transfer_sales_types_id: (!isNaN(parseInt(_product_edit_profile_form_profile_transfer_sales_types_id.value))) ? parseInt(_product_edit_profile_form_profile_transfer_sales_types_id.value) : null,
                    allot_by_id: (!isNaN(parseInt(_product_edit_profile_form_profile_allot_by_id.value))) ? parseInt(_product_edit_profile_form_profile_allot_by_id.value) : 3,
                    enabled: (_product_edit_profile_form_profile_enabled.checked === true) ? 1 : 0,
                    expires: InventoryProfile.expiration_date.value(),
                    advanced_booking_date: InventoryProfile.advanced_booking_date.value(),
                    checkin_dow: (formatListOfIds(InventoryProfile.checkin_dow.disabled_dows) === null) ? "" : formatListOfIds(InventoryProfile.checkin_dow.disabled_dows),
                    checkout_dow: (formatListOfIds(InventoryProfile.checkout_dow.disabled_dows) === "") ? "" : formatListOfIds(InventoryProfile.checkout_dow.disabled_dows),
                    departure_dow: (formatListOfIds(InventoryProfile.departure_dow.disabled_dows) === "") ? "" : formatListOfIds(InventoryProfile.departure_dow.disabled_dows),
                    return_dow: (formatListOfIds(InventoryProfile.return_dow.disabled_dows) === "") ? "" : formatListOfIds(InventoryProfile.return_dow.disabled_dows),
                    weekday_dow: (formatListOfIds(InventoryProfile.weekday_dow.disabled_dows) === "") ? "" : formatListOfIds(InventoryProfile.weekday_dow.disabled_dows),
                    inc_days_dow: (formatListOfIds(InventoryProfile.inc_days_dow.disabled_dows) === "") ? "" : formatListOfIds(InventoryProfile.inc_days_dow.disabled_dows),
                    days_out: (!isNaN(parseInt(_product_edit_profile_form_profile_days_out.value))) ? parseInt(_product_edit_profile_form_profile_days_out.value) : null,
                    release_amt: (!isNaN(parseInt(_product_edit_profile_form_profile_release_amt.value))) ? parseInt(_product_edit_profile_form_profile_release_amt.value) : null,
                    min_length_days: (!isNaN(parseInt(_product_edit_profile_form_profile_min_length_days.value))) ? parseInt(_product_edit_profile_form_profile_min_length_days.value) : "",
                    min_duration: (!isNaN(parseInt(_product_edit_profile_form_profile_min_duration.value))) ? parseInt(_product_edit_profile_form_profile_min_duration.value) : null,
                    max_duration: (!isNaN(parseInt(_product_edit_profile_form_profile_max_duration.value))) ? parseInt(_product_edit_profile_form_profile_max_duration.value) : null,
                    equal_duration: (!isNaN(parseInt(_product_edit_profile_form_profile_equal_duration.value))) ? parseInt(_product_edit_profile_form_profile_equal_duration.value) : null,
                    advanced_booking_min: (!isNaN(parseInt(_product_edit_profile_form_profile_advanced_booking_min.value))) ? parseInt(_product_edit_profile_form_profile_advanced_booking_min.value) : null,
                    advanced_booking_max: (!isNaN(parseInt(_product_edit_profile_form_profile_advanced_booking_max.value))) ? parseInt(_product_edit_profile_form_profile_advanced_booking_max.value) : null,
                })
                
            }
            
            return false
        }
        
        const loadAll = function (inventory_profiles) {
            Console.log("InventoryProfile.loadAll(inventory_profiles)", inventory_profiles)
            InventoryProfile.all = new Map()
            if (!inventory_profiles) { inventory_profiles = [] }
            $.each(inventory_profiles, function (k, inventory_profile) {
                //Console.log("InventoryProfile.loadAll - inventory_profile", inventory_profile)
                //Console.log("InventoryProfile.loadAll - inventory_profile", inventory_profile, checkin_dow)
                let detail = set(inventory_profile)
                //Console.log('detail', detail)
                if (!isNaN(parseInt(detail.id))) {
                    if (_table_profile_product_edit) {
                        $table_profile_product_edit.insertRow(detail)
                    }
                    InventoryProfile.all.set(parseInt(detail.id), detail)
                }
            })
            
            Pricing.loadProfileDropdown()
        }
        
        const setFormElementDisplay = function () {
            let sales_types_id = (!isNaN(parseInt(_product_edit_profile_form_profile_sales_types_id.value))) ? parseInt(_product_edit_profile_form_profile_sales_types_id.value) : null
            
            hideAllotmentFields()
            if (sales_types_id) {
                switch (sales_types_id) {
                    case 1:
                        showAllotmentFields()
                        break
                    case 2:
                        break
                    case 3:
                        break
                    case 4:
                        break
                    case 5:
                        break
                    default:
                        break
                }
            }
        }
        
        const showAllotmentFields = function () {
            let allot_by_id = (!isNaN(parseInt(_product_edit_profile_form_profile_allot_by_id.value))) ? parseInt(_product_edit_profile_form_profile_allot_by_id.value) : null
            if (allot_by_id) {
                switch (allot_by_id) {
                    case 1:
                        $(_product_edit_profile_form_profile_days_out_block).hide()
                        $(_product_edit_profile_form_profile_expires_block).show()
                        break
                    case 2:
                        
                        $(_product_edit_profile_form_profile_days_out_block).show()
                        $(_product_edit_profile_form_profile_expires_block).hide()
                        break
                    case 3:
                        
                        $(_product_edit_profile_form_profile_days_out_block).hide()
                        $(_product_edit_profile_form_profile_expires_block).hide()
                        break
                    default:
                        $(_product_edit_profile_form_profile_days_out_block).hide()
                        $(_product_edit_profile_form_profile_expires_block).hide()
                        break
                }
            }
            
            $(_product_edit_profile_form_profile_transfer_sales_types_id_block).show()
            $(_product_edit_profile_form_profile_quantity_block).show()
            $(_product_edit_profile_form_profile_release_amt_block).show()
            $(_product_edit_profile_form_profile_allot_by_id_block).show()
        }
        
        const hideAllotmentFields = function () {
            $(_product_edit_profile_form_profile_days_out_block).hide()
            $(_product_edit_profile_form_profile_expires_block).hide()
            $(_product_edit_profile_form_profile_allot_by_id_block).hide()
            $(_product_edit_profile_form_profile_transfer_sales_types_id_block).hide()
            $(_product_edit_profile_form_profile_quantity_block).hide()
            $(_product_edit_profile_form_profile_release_amt_block).hide()
            $("#accordionEx").collapse("hide")
        }
        
        const hideForm = function () {
            //Console.log("InventoryProfile.hideForm()", hideForm)
            if (_edit_product_profile) {
                hideAllotmentFields()
                $(_edit_product_profile).hide()
                _product_edit_profile_form_profile_name_filter.disabled = false
                
                $("#accordionEx").collapse("hide")
                
            }
        }
        
        const showForm = function () {
            //Console.log("InventoryProfile.showForm()", showForm)
            if (_edit_product_profile) {
                _product_edit_profile_form_profile_name_filter.disabled = true
                $(_edit_product_profile).show()
            }
        }
        
        const resetInventoryProfileForm = function () {
            //Console.log("InventoryProfile.resetInventoryProfileForm()", {})
            clearInventoryProfileForm()
            disableInventoryProfileFormFields()
        }
        
        const clearInventoryProfileForm = function () {
            //Console.log("InventoryProfile.clearInventoryProfileForm()", clearInventoryProfileForm)
            
            disableInventoryProfileFormFields()
            _product_edit_profile_form_profile_id.value = ""
            _product_edit_profile_form_profile_name.value = ""
            _product_edit_profile_form_profile_enabled.checked = true
            _product_edit_profile_form_profile_sales_types_id.value = ""
            _product_edit_profile_form_profile_allot_by_id.value = ""
            _product_edit_profile_form_profile_transfer_sales_types_id.value = ""
            _product_edit_profile_form_profile_days_out.value = ""
            _product_edit_profile_form_profile_quantity.value = ""
            _product_edit_profile_form_profile_release_amt.value = ""
            _product_edit_profile_form_profile_min_length_days.value = ""
            _product_edit_profile_form_profile_min_duration.value = ""
            _product_edit_profile_form_profile_max_duration.value = ""
            _product_edit_profile_form_profile_equal_duration.value = ""
            _product_edit_profile_form_profile_advanced_booking_min.value = ""
            _product_edit_profile_form_profile_advanced_booking_max.value = ""
            
            InventoryProfile.checkin_dow.init([0, 1, 2, 3, 4, 5, 6])
            InventoryProfile.checkout_dow.init([0, 1, 2, 3, 4, 5, 6])
            InventoryProfile.departure_dow.init([0, 1, 2, 3, 4, 5, 6])
            InventoryProfile.return_dow.init([0, 1, 2, 3, 4, 5, 6])
            InventoryProfile.weekday_dow.init([0, 1, 2, 3, 4, 5, 6])
            InventoryProfile.inc_days_dow.init([0, 1, 2, 3, 4, 5, 6])
            
            InventoryProfile.expiration_date.value("")
            InventoryProfile.advanced_booking_date.value("")
            
            setFormElementDisplay()
        }
        
        const validateInventoryProfileForm = function () {
            let isValid = $(_product_edit_profile_form).valid()
            if (isValid) {
                let allotById = (!isNaN(parseInt(_product_edit_profile_form_profile_allot_by_id.value))) ? parseInt(_product_edit_profile_form_profile_allot_by_id.value) : 3
                if (allotById === 1) {
                    let expiration_date = InventoryProfile.expiration_date.value()
                    
                    if (expiration_date === null || expiration_date === "") {
                        setError(document.getElementById("profile_expires"), "Field Required")
                        isValid = false
                    } else {
                        clearError(document.getElementById("profile_expires"))
                    }
                }
            }
            
            return isValid
        }
        
        const disableInventoryProfileFormFields = function () {
            //Console.log('InventoryProfile.disableInventoryProfileFormFields()', this)
            _product_edit_profile_form_profile_name.disabled = false
        }
        
        const populateInventoryProfileForm = function (inventory_profile) {
            //Console.log("InventoryProfile.populateInventoryProfileForm(inventory_profile)", inventory_profile)
            clearInventoryProfileForm()
            if (inventory_profile) {
                _product_edit_profile_form_profile_id.value = (inventory_profile.id) ? inventory_profile.id : ""
                _product_edit_profile_form_profile_name.value = (inventory_profile.name) ? inventory_profile.name : ""
                _product_edit_profile_form_profile_enabled.checked = (inventory_profile.enabled !== 0)
                _product_edit_profile_form_profile_sales_types_id.value = (inventory_profile.sales_types_id) ? inventory_profile.sales_types_id : ""
                _product_edit_profile_form_profile_allot_by_id.value = (inventory_profile.allot_by_id) ? inventory_profile.allot_by_id : ""
                _product_edit_profile_form_profile_transfer_sales_types_id.value = (inventory_profile.transfer_sales_types_id) ? inventory_profile.transfer_sales_types_id : ""
                _product_edit_profile_form_profile_days_out.value = (inventory_profile.days_out) ? inventory_profile.days_out : ""
                _product_edit_profile_form_profile_quantity.value = (inventory_profile.quantity) ? inventory_profile.quantity : ""
                _product_edit_profile_form_profile_release_amt.value = (inventory_profile.release_amt) ? inventory_profile.release_amt : ""
                _product_edit_profile_form_profile_min_length_days.value = (inventory_profile.min_length_days) ? inventory_profile.min_length_days : ""
                _product_edit_profile_form_profile_min_duration.value = (inventory_profile.min_duration) ? inventory_profile.min_duration : ""
                _product_edit_profile_form_profile_max_duration.value = (inventory_profile.max_duration) ? inventory_profile.max_duration : ""
                _product_edit_profile_form_profile_equal_duration.value = (inventory_profile.equal_duration) ? inventory_profile.equal_duration : ""
                _product_edit_profile_form_profile_advanced_booking_min.value = (inventory_profile.advanced_booking_min) ? inventory_profile.advanced_booking_min : ""
                _product_edit_profile_form_profile_advanced_booking_max.value = (inventory_profile.advanced_booking_max) ? inventory_profile.advanced_booking_max : ""
                
                InventoryProfile.checkin_dow.init((inventory_profile.checkin_dow) ? inventory_profile.checkin_dow : [0, 1, 2, 3, 4, 5, 6])
                InventoryProfile.checkout_dow.init((inventory_profile.checkout_dow) ? inventory_profile.checkout_dow : [0, 1, 2, 3, 4, 5, 6])
                InventoryProfile.departure_dow.init((inventory_profile.departure_dow) ? inventory_profile.departure_dow : [0, 1, 2, 3, 4, 5, 6])
                InventoryProfile.return_dow.init((inventory_profile.return_dow) ? inventory_profile.return_dow : [0, 1, 2, 3, 4, 5, 6])
                InventoryProfile.weekday_dow.init((inventory_profile.weekday_dow) ? inventory_profile.weekday_dow : [0, 1, 2, 3, 4, 5, 6])
                InventoryProfile.inc_days_dow.init((inventory_profile.inc_days_dow) ? inventory_profile.inc_days_dow : [0, 1, 2, 3, 4, 5, 6])
                
                InventoryProfile.expiration_date.value((inventory_profile.expires) ? inventory_profile.expires : "")
                InventoryProfile.advanced_booking_date.value((inventory_profile.advanced_booking_date) ? inventory_profile.advanced_booking_date : "")
                
            }
            
            setFormElementDisplay()
            showForm()
        }
        
        const set = function (inventory_profile) {
            Console.log("InventoryProfile.set(inventory_profile)", inventory_profile)
            
            let detail = defaultDetail()
            let sales_types_details, allot_by_details, tranfer_sales_type_details
            if (inventory_profile) {
                let checkinDOW = getListOfIds(inventory_profile.checkin_dow)
                let checkoutDOW = getListOfIds(inventory_profile.checkout_dow)
                let departureDOW = getListOfIds(inventory_profile.departure_dow)
                let returnDOW = getListOfIds(inventory_profile.return_dow)
                let inc_daysDOW = getListOfIds(inventory_profile.inc_days_dow)
                let weekdayDOW = getListOfIds(inventory_profile.weekday_dow)
                
                sales_types_details = Types.sales_types.get((!isNaN(parseInt(inventory_profile.sales_types_id))) ? parseInt(inventory_profile.sales_types_id) : null)
                allot_by_details = Types.allot_by.get((!isNaN(parseInt(inventory_profile.allot_by_id))) ? parseInt(inventory_profile.allot_by_id) : null)
                tranfer_sales_type_details = Types.sales_types.get((!isNaN(parseInt(inventory_profile.transfer_sales_types_id))) ? parseInt(inventory_profile.transfer_sales_types_id) : null)
                detail.id = (!isNaN(parseInt(inventory_profile.id))) ? parseInt(inventory_profile.id) : null
                detail.allot_by_id = (!isNaN(parseInt(inventory_profile.allot_by_id))) ? parseInt(inventory_profile.allot_by_id) : null
                detail.sales_types_id = (!isNaN(parseInt(inventory_profile.sales_types_id))) ? parseInt(inventory_profile.sales_types_id) : null
                detail.name = (inventory_profile.name) ? inventory_profile.name : null
                detail.quantity = (!isNaN(parseInt(inventory_profile.quantity))) ? parseInt(inventory_profile.quantity) : null
                detail.expires = (inventory_profile.expires) ? inventory_profile.expires : null
                detail.transfer_sales_types_id = (!isNaN(parseInt(inventory_profile.transfer_sales_types_id))) ? parseInt(inventory_profile.transfer_sales_types_id) : null
                detail.release_amt = (inventory_profile.release_amt) ? inventory_profile.release_amt : null
                detail.min_length_days = (inventory_profile.min_length_days) ? inventory_profile.min_length_days : null
                detail.min_duration = (inventory_profile.min_duration) ? inventory_profile.min_duration : null
                detail.max_duration = (inventory_profile.max_duration) ? inventory_profile.max_duration : null
                detail.equal_duration = (inventory_profile.equal_duration) ? inventory_profile.equal_duration : null
                detail.advanced_booking_min = (inventory_profile.advanced_booking_min) ? inventory_profile.advanced_booking_min : null
                detail.advanced_booking_max = (inventory_profile.advanced_booking_max) ? inventory_profile.advanced_booking_max : null
                detail.advanced_booking_date = (inventory_profile.advanced_booking_date) ? inventory_profile.advanced_booking_date : null
                
                detail.checkin_dow = checkinDOW
                detail.checkout_dow = checkoutDOW
                detail.departure_dow = departureDOW
                detail.return_dow = returnDOW
                detail.inc_days_dow = inc_daysDOW
                detail.weekday_dow = weekdayDOW
                
                detail.days_out = (inventory_profile.days_out) ? inventory_profile.days_out : null
                detail.enabled = (inventory_profile.enabled) ? inventory_profile.enabled : 1
                detail.date_created = (inventory_profile.date_created) ? inventory_profile.date_created : formatDateMySQL()
                detail.created_by = (!isNaN(parseInt(inventory_profile.created_by))) ? parseInt(inventory_profile.created_by) : user_id
                detail.date_modified = (inventory_profile.date_modified) ? inventory_profile.date_modified : formatDateMySQL()
                detail.modified_by = (!isNaN(parseInt(inventory_profile.modified_by))) ? parseInt(inventory_profile.modified_by) : user_id
                detail.note = (inventory_profile.note) ? inventory_profile.note : null
                detail.sales_types_details = sales_types_details
                detail.allot_by_details = allot_by_details
                detail.tranfer_sales_type_details = tranfer_sales_type_details
            }
            
            InventoryProfile.detail = detail
            return detail
        }
        
        const edit = function (inventory_profile) {
            //Console.log('InventoryProfile.edit(inventory_profile)', inventory_profile)
            if (inventory_profile) {
                $table_profile_product_edit.clearSelectedRows()
                let detail = set(inventory_profile)
                
                showForm()
                _product_edit_profile_form_profile_name_filter.value = detail.name
                _product_edit_profile_form_profile_name_filter.disabled = true
                $table_profile_product_edit.loadRow(detail)
                populateInventoryProfileForm(detail)
            }
            
        }
        
        const save = function () {
            //Console.log('InventoryProfile.save()', save)
            let dataToSend = buildInventoryProfileRecord()
            if (dataToSend) {
                confirmDialog(`Would you like to update?`, (ans) => {
                    if (ans) {
                        //Console.log("InventoryProfile.save - dataToSend", dataToSend)
                        saveProductProfile(dataToSend, function (data) {
                            //Console.log("InventoryProfile.save - data", data)
                            let inventory_profile
                            if (data) {
                                inventory_profile = data
                                if (data[0]) {
                                    inventory_profile = data[0]
                                }
                                let detail = set(inventory_profile)
                                Console.log("detail", detail)
                                let hasProfile = InventoryProfile.all.get(detail.id)
                                Console.log("InventoryProfile.save - hasProfile", hasProfile)
                                InventoryProfile.all.set(detail.id, detail)
                                
                                if (hasProfile) {
                                    $table_profile_product_edit.updateRow(detail)
                                } else {
                                    $table_profile_product_edit.insertRow(detail)
                                }
                                
                                Console.log("InventoryProfile.save - InventoryProfile.all", InventoryProfile.all)
                                toastr.success(`InventoryProfile: ${detail.name} - has been updated`)
                                populateInventoryProfileForm()
                                
                                _product_edit_profile_form_profile_name_filter.value = ""
                                $table_profile_product_edit.loadRow(detail)
                                $table_profile_product_edit.jumpToRow(detail)
                                $table_profile_product_edit.clearSelectedRows()
                                Pricing.resetForm()
                                YearCalendar.resetForm()
                            }
                        })
                    }
                })
                Console.log("YES", inv)
            } else {
                Console.log("save", "NO")
            }
        }
        
        const handleProfileError = function (msg) {
            toastr.error(msg)
        }
        
        const saveProductProfile = function (dataToSend, callback) {
            if (dataToSend) {
                let url = "/api/v1.0/profiles/update"
                try {
                    sendPostRequest(url, dataToSend, function (data, status, xhr) {
                        if (data) {
                            return callback(data)
                        } else {
                            return handleProfileError("Oops: 1")
                        }
                    })
                } catch (e) {
                    Console.log(e)
                }
            }
        }
        
        const init = function (settings) {
            //Console.log("InventoryProfile.init(settings)", settings)
            
            let inventory_profiles = []
            if (settings) {
                if (settings.profiles) {
                    inventory_profiles = settings.profiles
                }
            }
            
            checkin_dow = $(_product_edit_profile_form_profile_checkin_dow).DisabledDOW({
                name: "checkin_dow",
                label: "Checkin DOW",
            })
            
            checkout_dow = $(_product_edit_profile_form_profile_checkout_dow).DisabledDOW({
                name: "checkout_dow",
                label: "Checkout DOW",
            })
            
            departure_dow = $(_product_edit_profile_form_profile_departure_dow).DisabledDOW({
                name: "departure_dow",
                label: "Departure DOW",
            })
            
            return_dow = $(_product_edit_profile_form_profile_return_dow).DisabledDOW({
                name: "return_dow",
                label: "Return DOW",
            })
            
            inc_days_dow = $(_product_edit_profile_form_profile_inc_days_dow).DisabledDOW({
                name: "inc_days_dow",
                label: "Included Days",
            })
            
            weekday_dow = $(_product_edit_profile_form_profile_weekday_dow).DisabledDOW({
                name: "weekday_dow",
                label: "Weekdays",
            })
            
            InventoryProfile.checkin_dow = checkin_dow
            InventoryProfile.checkout_dow = checkout_dow
            InventoryProfile.departure_dow = departure_dow
            InventoryProfile.return_dow = return_dow
            InventoryProfile.weekday_dow = weekday_dow
            InventoryProfile.inc_days_dow = inc_days_dow
            
            $(document).ready(function () {
                if (_table_profile_product_edit) {
                    buildInventoryProfileTable()
                }
                
                if (_product_edit_profile_form_profile_name_filter) {
                    initAutoComplete()
                }
                
                if (_product_edit_profile_form) {
                    validator_init(form_rules)
                    InventoryProfile.expiration_date = $("#profile_expires").dateSelect({
                        onStart: function () {},
                    })
                    InventoryProfile.advanced_booking_date = $("#profile_advanced_booking_date").dateSelect({
                        onStart: function () {},
                    })
                    
                    InventoryProfile.validator = $(_product_edit_profile_form).validate()
                    resetInventoryProfileForm()
                    hideForm()
                }
                
                loadAll(inventory_profiles)
            })
        }
        
        return {
            validator: null,
            all: new Map(),
            detail: {},
            expiration_date: null,
            advanced_booking_date: null,
            checkin_dow: null,
            checkout_dow: null,
            departure_dow: null,
            return_dow: null,
            weekday_dow: null,
            inc_days_dow: null,
            init: function (settings) { init(settings) },
            initAutoComplete: function () { initAutoComplete() },
            edit: function (inventory_profile) {
                edit(inventory_profile)
            },
        }
    })()
</script>

