<section>
    <div class="row">
        <div class="col-12">
            <div class="form-element">
                <label for="product_edit_unit_form_unit_name_filter" class="d-none">Unit Search:</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="fas fa-search" aria-hidden="true"></i>
                        </span>
                    </div>
                    <input type="search" id="product_edit_unit_form_unit_name_filter" name="product_edit_unit_form_unit_name_filter" class="form-control" placeholder="Search Units"/>
                </div>
                <div id="product_edit_unit_form_unit_name_filter-error" class="error w-100 text-center"></div>
            </div>
        </div>
    </div>
    
    <?php include_once(VIEWS_PATH . "/units/tables/product_edit_unit_table.phtml"); ?>
    
    <div class="card card-body mb-2">
        
        <div class="row">
            
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-4">
                <div class="form-element">
                    <label for="product_edit_unit_form_unit_id">Id:</label>
                    <input type="text" id="product_edit_unit_form_unit_id" name="product_edit_unit_form_unit_id" class="form-control" readonly="readonly"/>
                    <div id="product_edit_unit_form_unit_id-error" class="error w-100 text-center"></div>
                </div>
            </div>
            
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-4">
                <div class="form-element">
                    <label for="product_edit_unit_form_unit_name">Name:</label>
                    <input type="text" id="product_edit_unit_form_unit_name" name="product_edit_unit_form_unit_name" class="form-control"/>
                    <div id="product_edit_unit_form_unit_name-error" class="error w-100 text-center"></div>
                </div>
            </div>
            
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-4 d-flex align-self-end justify-content-end pb-2">
                <div class="form-element">
                    <div class="custom-control custom-switch">
                        <input id="product_edit_unit_form_unit_enabled" name="product_edit_unit_form_unit_enabled" type="checkbox" value="1" class="custom-control-input" readonly="readonly">
                        <label for="product_edit_unit_form_unit_enabled" class="custom-control-label p-0">Enabled</label>
                    </div>
                    <div id="product_edit_unit_form_unit_enabled-error" class="error w-100 text-center"></div>
                </div>
            </div>
        
        </div>
        
        <div class="row">
            
            <div class="col-6">
                <div class="form-element">
                    <label for="product_edit_unit_form_unit_room_code">Room Code:</label>
                    <input type="text" id="product_edit_unit_form_unit_room_code" name="product_edit_unit_form_unit_room_code" class="form-control"/>
                    <div id="product_edit_unit_form_unit_room_code-error" class="error w-100 text-center"></div>
                </div>
            </div>
        </div>
        
        <div class="row">
            
            <div class="col-6">
                <div class="form-element">
                    <label for="product_edit_unit_form_unit_min_nights">Minimum Nights:</label>
                    <input type="text" id="product_edit_unit_form_unit_min_nights" name="product_edit_unit_form_unit_min_nights" class="form-control"/>
                    <div id="product_edit_unit_form_unit_min_nights-error" class="error w-100 text-center"></div>
                </div>
            </div>
            
            <div class="col-6">
                <div class="form-element">
                    <label for="product_edit_unit_form_unit_max_nights">Maximum Nights:</label>
                    <input type="text" id="product_edit_unit_form_unit_max_nights" name="product_edit_unit_form_unit_max_nights" class="form-control"/>
                    <div id="product_edit_unit_form_unit_max_nights-error" class="error w-100 text-center"></div>
                </div>
            </div>
        </div>
        
        <div class="row">
            
            <div class="col-6">
                <div class="form-element">
                    <label for="product_edit_unit_form_unit_min_pax">Minimum Pax:</label>
                    <input type="number" id="product_edit_unit_form_unit_min_pax" name="product_edit_unit_form_unit_min_pax" min="1" class="form-control"/>
                    <div id="product_edit_unit_form_unit_min_pax-error" class="error w-100 text-center"></div>
                </div>
            </div>
            
            <div class="col-6">
                <div class="form-element">
                    <label for="product_edit_unit_form_unit_max_pax">Maximum Pax:</label>
                    <input type="number" id="product_edit_unit_form_unit_max_pax" name="product_edit_unit_form_unit_max_pax" min="1" class="form-control"/>
                    <div id="product_edit_unit_form_unit_max_pax-error" class="error w-100 text-center"></div>
                </div>
            </div>
        </div>
        
        <div class="row">
            
            <!-- Unit Short Description -->
            <div class="col-12 col-md-6">
                <div class="form-element">
                    <label for="product_edit_unit_form_unit_description_short">Short Description</label>
                    <textarea id="product_edit_unit_form_unit_description_short" name="product_edit_unit_form_unit_description_short" class="md-textarea form-control" rows="4"></textarea>
                    <div id="product_edit_unit_form_unit_description_short-error" class="error w-100 text-center">&nbsp;</div>
                </div>
            </div>
            <!-- /Unit Short Description -->
            
            <!-- Unit Long Description -->
            <div class="col-12 col-md-6">
                <div class="card mb-2">
                    <div class="card-body">
                        <!-- Social shares button -->
                        <a id="button_provider_description_long_toggle" class="activator but_toggle waves-effect waves-light mr-4" data-texted="provider_description_long">
                            <i class="fas fa-sliders-h"></i>
                        </a>
                        <!-- Title -->
                        <h4 class="card-title">Detailed Description</h4>
                        <hr>
                        <!-- Text -->
                        
                        <div class="row">
                            <div class="col-12">
                                <div class="form-element">
                                    <label for="provider_description_long" style="display:none">Cover Image:</label>
                                    <textarea id="provider_description_long" name="provider_description_long" class="md-textarea tmceEl form-control" rows="4"></textarea>
                                    <div id="provider_description_long-error" class="error w-100 text-center">&nbsp;</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Unit Long Description -->
        
        </div>
    
    </div>

</section>
