<fieldset id="modal_product_tours_fields" data-categoryid="6" class="fieldset-dark">
	<legend class="">
		<h6>Tour Fields</h6>
	</legend>
	
	<div class="row">
		
		<!-- City -->
		<div class="col-12 col-md-8">
			<div class="form-element">
				<label for="modal_product_city_tours">City:</label>
				<input type="text" id="modal_product_city_tours" name="modal_product_city_tours" class="form-control"/>
				<div id="modal_product_city_tours-error" class="error w-100 text-center"></div>
			</div>
		</div>
		<!-- /City -->
	
	</div>

</fieldset>
