<!-- Address Table -->
<section class="panel z-depth-0 mb-0 w-100">
    <header class="panel-heading">
        <div class="row">

            <div class="col-8">
                <h4 class="panel-title">Address List</h4>
            </div>

            <div class="col-4 d-flex align-items-center justify-content-end">
                <div class="panel-actions p-0 m-0">
                    <a class="panel-action fas fa-filter" data-toggle="collapse" href="#provider_index_table_filters" aria-expanded="false" aria-controls="provider_index_table_filters"></a>
                    <a id="button_add_address_table" href="javascript:void(0);" class="panel-action fas fa-plus" data-toggle="panel-button" aria-hidden="true"></a>
                </div>
            </div>

        </div>
    </header>

    <div class="panel-body">

        <div class="collapse" id="provider_index_table_filters">
            <div class="card rgba-blue-grey-slight m-2">
                <div class="row">

                    <!-- -->
                    <div class="col-12 col-lg-4 mb-1">
                        <div class="form-element">
                        </div>
                    </div>
                    <!-- / -->

                </div>
            </div>
        </div>

        <table id="table_address" class="table w-100 table-striped" style=""></table>

    </div>

</section>
