<?php
    /**
     * id
     * role_id
     * email
     * name_first
     * name_last
     * username
     * role
     * pass
     * salt
     * enabled
     * date_created
     * created_by
     * date_modified
     * modified_by
     * note
     */

    if (!isset($data)) {
        $data = [];
    }
    extract($data);
    $id = (isset($id)) ? $id : null;
    $role_id = (isset($role_id)) ? $role_id : null;
    $email = (isset($email)) ? $email : null;
    $name_first = (isset($name_first)) ? $name_first : null;
    $name_last = (isset($name_last)) ? $name_last : null;
    $username = (isset($username)) ? $username : null;
    $role = (isset($role)) ? $role : null;
    $pass = (isset($pass)) ? $pass : null;
    $salt = (isset($salt)) ? $salt : null;
    $enabled = (isset($enabled)) ? $enabled : null;
    $date_created = (isset($date_created)) ? $date_created : null;
    $created_by = (isset($created_by)) ? $created_by : null;
    $date_modified = (isset($date_modified)) ? $date_modified : null;
    $modified_by = (isset($modified_by)) ? $modified_by : null;
    $note = (isset($note)) ? $note : null;

?>
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="x-apple-disable-message-reformatting">
    <title></title>

    <!--[if mso]>
    <noscript>
        <xml>
            <o:OfficeDocumentSettings>
                <o:PixelsPerInch>96</o:PixelsPerInch>
            </o:OfficeDocumentSettings>
        </xml>
    </noscript>
    <![endif]-->
    <style>
      table, td, div, h1, p {
        font-family: Arial, sans-serif;
        }
    </style>
</head>

<body style="margin:0;padding:0;">
<table role="presentation" style="width:602px;border-collapse:collapse;border:1px solid #cccccc;border-spacing:0;text-align:left;">
    <tr>
        <td style="padding:0;">
            Hello!
        </td>
    </tr>
</table>
</body>
</html>
