<fieldset id="modal_product_rail_fields" data-categoryid="4" class="fieldset-dark">
	<legend class="">
		<h6>Rail Fields</h6>
	</legend>
	
	<!-- Departing Station -->
	<fieldset class="px-2 border border-1 rounded my-2 border-light">
		<legend class="card-subtitle mb-2 text-muted">Departing Station</legend>
		
		<!-- Departing Station Search -->
		<div class="row">
			
			<!-- Departing Station Search -->
			<div class="col-10">
				<div class="form-element">
					<label for="modal_product_depart_from_station" class="d-none">Name:</label>
					<div class="input-group">
						<div class="input-group-prepend">
	                        <span class="input-group-text">
	                            <i class="fas fa-search" aria-hidden="true"></i>
	                        </span>
						</div>
						<input type="search" id="modal_product_depart_from_station" name="modal_product_depart_from_station" class="form-control" placeholder="Search Stations"/>
					</div>
					<div id="modal_product_depart_from_station-error" class="error w-100 text-center"></div>
				</div>
			</div>
			<!-- /Departing Station Search -->
			
			<!-- Departing Station Search Edit -->
			<div class="col-2 mt-2">
				<a href="javascript:void(0);" id="modal_product_depart_from_station_edit_link" data-station-id="1" class="">Edit</a>
			</div>
			<!-- /Departing Station Search Edit -->
		
		</div>
		<!-- /Departing Station Search -->
		
		<!-- Departing Station -->
		<div class="card card-body grey lighten-4 mb-2" id="modal_product_depart_from_station_add_block">
			
			<fieldset class="px-2 border border-1 rounded my-2 border-light">
				<legend class="card-subtitle mb-2 text-muted">Detail</legend>
				
				<div class="row">
					
					<!-- Departing Station Id -->
					<div class="col-12 col-md-4">
						<div class="form-element">
							<label for="modal_product_depart_from_new_station_id">Id:</label>
							<input type="text" id="modal_product_depart_from_new_station_id" name="modal_product_depart_from_new_station_id" class="form-control" readonly="readonly"/>
							<div id="modal_product_depart_from_new_station_id-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Departing Station Id -->
					
					<!-- Departing Station IATA Code -->
					<div class="col-12 col-md-4">
						<div class="form-element">
							<label for="modal_product_depart_from_station_iata_code">IATA Code:</label>
							<input type="text" id="modal_product_depart_from_station_iata_code" name="modal_product_depart_from_station_iata_code" class="form-control" maxlength="5"/>
							<div id="modal_product_depart_from_station_iata_code-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Departing Station IATA Code -->
					
					<!-- Depart From Local Code -->
					<div class="col-12 col-md-4">
						<div class="form-element">
							<label for="modal_product_depart_from_local_code">Local Code:</label>
							<input type="text" id="modal_product_depart_from_local_code" name="modal_product_depart_from_local_code" class="form-control"/>
							<div id="modal_product_depart_from_local_code-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Depart From Local Code -->
				
				</div>
				
				<div class="row">
					
					<!-- Depart From GPS Coords -->
					<div class="col-12 col-md-6">
						<div class="form-element">
							<label for="modal_product_depart_from_gps_code">GPS Coords:</label>
							<input type="text" id="modal_product_depart_from_gps_code" name="modal_product_depart_from_gps_code" class="form-control"/>
							<div id="modal_product_depart_from_gps_code-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Depart From GPS Coords -->
				
				</div>
			
			</fieldset>
			
			<fieldset class="px-2 border border-1 rounded my-2 border-light">
				<legend class="card-subtitle mb-2 text-muted">Address</legend>
				
				<div class="row">
					
					<!-- Departing Station Street 1 -->
					<div class="col-12">
						<div class="form-element">
							<label for="modal_product_depart_from_station_street_1">Street 1:</label>
							<input type="search" id="modal_product_depart_from_station_street_1" name="modal_product_depart_from_station_street_1" class="form-control"/>
							<div id="modal_product_depart_from_station_street_1-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Departing Station Street 1 -->
				
				</div>
				
				<div class="row">
					
					<!-- Departing Station Street 2 -->
					<div class="col-12">
						<div class="form-element">
							<label for="modal_product_depart_from_station_street_2">Street 2:</label>
							<input type="search" id="modal_product_depart_from_station_street_2" name="modal_product_depart_from_station_street_2" class="form-control"/>
							<div id="modal_product_depart_from_station_street_2-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Departing Station Street 1 -->
				
				</div>
				
				<div class="row">
					
					<!-- Departing Station City/Province/Country -->
					<div class="col-12 col-md-9">
						<div class="form-element">
							<label for="modal_product_depart_from_station_city">City/Province/Country:</label>
							<input type="search" id="modal_product_depart_from_station_city" name="modal_product_depart_from_station_city" class="form-control"/>
							<div id="modal_product_depart_from_station_city-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Departing Station City/Province/Country -->
					
					<!-- Departing Station Postal Code -->
					<div class="col-12 col-md-3">
						<div class="form-element">
							<label for="modal_product_depart_from_station_postal_code">Postal Code:</label>
							<input type="text" id="modal_product_depart_from_station_postal_code" name="modal_product_depart_from_station_postal_code" class="form-control"/>
							<div id="modal_product_depart_from_station_postal_code-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Departing Station Postal Code -->
				
				</div>
				
				<div class="row">
					
					<!-- Depart From GPS Coords -->
					<div class="col-12 col-md-6">
						<div class="form-element">
							<label for="modal_product_depart_from_gps_code">GPS Coords:</label>
							<input type="text" id="modal_product_depart_from_gps_code" name="modal_product_depart_from_gps_code" class="form-control"/>
							<div id="modal_product_depart_from_gps_code-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Depart From GPS Coords -->
				
				</div>
			
			</fieldset>
			
			<fieldset class="px-2 border border-1 rounded my-2 border-light">
				<legend class="card-subtitle mb-2 text-muted">Links</legend>
				
				<div class="row">
					
					<!-- Depart From Home Link -->
					<div class="col-12">
						<div class="form-element">
							<label for="modal_product_depart_from_home_link">Home Link:</label>
							<input type="url" id="modal_product_depart_from_home_link" name="modal_product_depart_from_home_link" class="form-control"/>
							<div id="modal_product_depart_from_home_link-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Depart From Home Link -->
				
				</div>
				
				<div class="row">
					
					<!-- Depart From Wiki Link -->
					<div class="col-12">
						<div class="form-element">
							<label for="modal_product_depart_from_wikipedia_link">Wiki Link:</label>
							<input type="url" id="modal_product_depart_from_wikipedia_link" name="modal_product_depart_from_wikipedia_link" class="form-control"/>
							<div id="modal_product_depart_from_wikipedia_link-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Depart From Wiki Link -->
				
				</div>
			
			</fieldset>
			
			<fieldset class="px-2 border border-1 rounded my-2 border-light">
				<legend class="card-subtitle mb-2 text-muted">Meta</legend>
				
				<!-- Depart From Keywords -->
				<section id="modal_product_depart_from_keywords_station" class="card card-body mb-2 keyword">
					<label for="modal_product_depart_from_keywords_station_search" class="d-none">Keywords:</label>
					<input type="text" id="modal_product_depart_from_keywords_station_search" class="user-release-input form-control form-control-lg" placeholder="Keywords..."/>
					<div id="modal_product_depart_from_keywords_station_container" class="w-100 my-2 chips_container"></div>
				</section>
				<!-- /Depart From Keywords -->
			
			</fieldset>
			
			<!-- Departing Station Hidden Elements -->
			<div class="row">
				
				<div class="col-3">
					<label for="modal_product_depart_from_station_city_id" class="dev-element d-none">City Id:</label>
					<input type="hidden" id="modal_product_depart_from_station_city_id" class="form-control dev-element" value="" readonly="readonly"/>
				</div>
				
				<div class="col-3">
					<label for="modal_product_depart_from_station_province_id" class="dev-element d-none">Province Id:</label>
					<input type="hidden" id="modal_product_depart_from_station_province_id" class="form-control dev-element" value="" readonly="readonly"/>
				</div>
				
				<div class="col-3">
					<label for="modal_product_depart_from_station_country_id" class="dev-element d-none">Country Id:</label>
					<input type="hidden" id="modal_product_depart_from_station_country_id" class="form-control dev-element" value="" readonly="readonly"/>
				</div>
			
			</div>
			<!-- /Departing Station Hidden Elements -->
			
			<!-- Departing Station Buttons -->
			<div class="row">
				
				<!-- Departing Station Cancel Button -->
				<div class="col-6 text-left">
					<button type="button" id="modal_product_depart_from_station_cancel_button" class="btn btn-outline-primary btn-sm white waves-effect waves-light">Cancel</button>
				</div>
				<!-- /Departing Station Cancel Button -->
				
				<!-- Departing Station Submit Button -->
				<div class="col-6 text-right">
					<button type="button" id="modal_product_depart_from_station_submit_button" class="btn btn-primary btn-sm waves-effect waves-light">Save</button>
				</div>
				<!-- /Departing Station Submit Button -->
			
			</div>
			<!-- /Departing Station Buttons -->
		
		</div>
		<!-- /Departing Station -->
		
		<!-- Departing Station Departing Date, Departing Time -->
		<div class="row">
			
			<!-- Departing Station Departing Date -->
			<div class="col-12 col-md-6">
				<div id="modal_product_depart_from_station_date" data-label="Departing Date" data-placeholder="Select Departing Date"></div>
			</div>
			<!-- /Departing Station Departing Date -->
			
			<!-- Departing Station Departing Time -->
			<div class="col-12 col-md-6">
				<div id="modal_product_depart_from_station_time" data-label="Departing Time" data-placeholder="Select Departing Time"></div>
			</div>
			<!-- /Departing Station Departing Time -->
		
		</div>
		<!-- /Departing Station Departing Date, Departing Time -->
	
	</fieldset>
	<!-- Departing Station -->
	
	<!-- Arriving Station -->
	<fieldset class="px-2 border border-1 rounded my-2 border-light">
		
		<legend class="card-subtitle mb-2 text-muted">Arriving Station</legend>
		
		<!-- Arriving Station Search -->
		<div class="row">
			
			<!-- Arriving Station Search -->
			<div class="col-10">
				<div class="form-element">
					<label for="modal_product_arrive_to_station" class="d-none">Name:</label>
					<div class="input-group">
						<div class="input-group-prepend">
					<span class="input-group-text">
						<i class="fas fa-search" aria-hidden="true"></i>
					</span>
						</div>
						<input type="search" id="modal_product_arrive_to_station" name="modal_product_arrive_to_station" class="form-control" placeholder="Search Stations"/>
					</div>
					<div id="modal_product_arrive_to_station-error" class="error w-100 text-center"></div>
				</div>
			</div>
			<!-- /Arriving Station Search -->
			
			<!-- Arriving Station Search Edit -->
			<div class="col-2 mt-2">
				<a href="javascript:void(0);" id="modal_product_arrive_to_station_edit_link" data-station-id="1" class="">Edit</a>
			</div>
			<!-- /Arriving Station Search Edit -->
		
		</div>
		<!-- /Arriving Station Search -->
		
		<!-- Arriving Station -->
		<div class="card card-body grey lighten-4 mb-2" id="modal_product_arrive_to_station_add_block">
			
			<div class="row">
				
				<!-- Arriving Station Id -->
				<div class="col-12 col-md-4">
					<div class="form-element">
						<label for="modal_product_arrive_to_new_station_id">Id:</label>
						<input type="text" id="modal_product_arrive_to_new_station_id" name="modal_product_arrive_to_new_station_id" class="form-control" readonly="readonly"/>
						<div id="modal_product_arrive_to_new_station_id-error" class="error w-100 text-center"></div>
					</div>
				</div>
				<!-- /Arriving Station Id -->
				
				<!-- Arriving Station IATA Code -->
				<div class="col-12 col-md-4">
					<div class="form-element">
						<label for="modal_product_arrive_to_station_iata_code">IATA Code:</label>
						<input type="text" id="modal_product_arrive_to_station_iata_code" name="modal_product_arrive_to_station_iata_code" class="form-control" maxlength="5"/>
						<div id="modal_product_arrive_to_station_iata_code-error" class="error w-100 text-center"></div>
					</div>
				</div>
				<!-- /Arriving Station IATA Code -->
			
			</div>
			
			<div class="row">
				
				<!-- Arriving Station Street 1 -->
				<div class="col-12">
					<div class="form-element">
						<label for="modal_product_arrive_to_station_street_1">Street 1:</label>
						<input type="search" id="modal_product_arrive_to_station_street_1" name="modal_product_arrive_to_station_street_1" class="form-control"/>
						<div id="modal_product_arrive_to_station_street_1-error" class="error w-100 text-center"></div>
					</div>
				</div>
				<!-- /Arriving Station Street 1 -->
			
			</div>
			
			<div class="row">
				
				<!-- Arriving Station Street 2 -->
				<div class="col-12">
					<div class="form-element">
						<label for="modal_product_arrive_to_station_street_2">Street 2:</label>
						<input type="search" id="modal_product_arrive_to_station_street_2" name="modal_product_arrive_to_station_street_2" class="form-control"/>
						<div id="modal_product_arrive_to_station_street_2-error" class="error w-100 text-center"></div>
					</div>
				</div>
				<!-- /Arriving Station Street 1 -->
			
			</div>
			
			<div class="row">
				
				<!-- Arriving Station City/Province/Country -->
				<div class="col-12 col-md-9">
					<div class="form-element">
						<label for="modal_product_arrive_to_station_city">City/Province/Country:</label>
						<input type="search" id="modal_product_arrive_to_station_city" name="modal_product_arrive_to_station_city" class="form-control"/>
						<div id="modal_product_arrive_to_station_city-error" class="error w-100 text-center"></div>
					</div>
				</div>
				<!-- /Arriving Station City/Province/Country -->
				
				<!-- Arriving Station Postal Code -->
				<div class="col-12 col-md-3">
					<div class="form-element">
						<label for="modal_product_arrive_to_station_postal_code">Postal Code:</label>
						<input type="text" id="modal_product_arrive_to_station_postal_code" name="modal_product_arrive_to_station_postal_code" class="form-control"/>
						<div id="modal_product_arrive_to_station_postal_code-error" class="error w-100 text-center"></div>
					</div>
				</div>
				<!-- /Arriving Station Postal Code -->
			
			</div>
			
			<div class="row">
				
				<div class="col-3">
					<label for="modal_product_arrive_to_station_city_id" class="dev-element d-none">City Id:</label>
					<input type="hidden" id="modal_product_arrive_to_station_city_id" class="form-control dev-element" value="" readonly="readonly"/>
				</div>
				
				<div class="col-3">
					<label for="modal_product_arrive_to_station_province_id" class="dev-element d-none">Province Id:</label>
					<input type="hidden" id="modal_product_arrive_to_station_province_id" class="form-control dev-element" value="" readonly="readonly"/>
				</div>
				
				<div class="col-3">
					<label for="modal_product_arrive_to_station_country_id" class="dev-element d-none">Country Id:</label>
					<input type="hidden" id="modal_product_arrive_to_station_country_id" class="form-control dev-element" value="" readonly="readonly"/>
				</div>
			
			</div>
			
			<div class="row">
				
				<div class="col-6 text-left">
					<button type="button" id="modal_product_arrive_to_station_cancel_button" class="btn btn-outline-primary btn-sm white waves-effect waves-light">Cancel</button>
				</div>
				
				<div class="col-6 text-right">
					<button type="button" id="modal_product_arrive_to_station_submit_button" class="btn btn-primary btn-sm waves-effect waves-light">Save</button>
				</div>
			
			</div>
		
		</div>
		<!-- /Arriving Station -->
		
		<!-- Arriving Station Arriving Date, Arriving Time -->
		<div class="row">
			
			<!-- Arriving Station Arriving Date -->
			<div class="col-12 col-md-6">
				<div id="modal_product_arrive_to_station_date" data-label="Arriving Date" data-placeholder="Select Arriving Date"></div>
			</div>
			<!-- /Arriving Station Arriving Date -->
			
			<!-- Arriving Station Arriving Time -->
			<div class="col-12 col-md-6">
				<div id="modal_product_arrive_to_station_time" data-label="Arriving Time" data-placeholder="Select Arriving Time"></div>
			</div>
			<!-- /Arriving Station Arriving Time -->
		
		</div>
		<!-- /Arriving Station Arriving Date, Arriving Time -->
		
		<!-- Arriving Keywords -->
		<section id="modal_product_arrive_to_keywords_station" class="card card-body mb-2 keyword">
			<label for="modal_product_arrive_to_keywords_station_search" class="d-none">Keywords:</label>
			<input type="text" id="modal_product_arrive_to_keywords_station_search" class="user-release-input form-control form-control-lg" placeholder="Keywords..."/>
			<div id="modal_product_arrive_to_keywords_station_container" class="w-100 my-2 chips_container"></div>
		</section>
		<!-- /Arriving Keywords -->
		
		<!-- Arriving Station Hidden Fields -->
		<div class="row">
			
			<!-- Departing From Station Id -->
			<div class="col-12 col-md-6">
				<label for="modal_product_depart_from_station_id" class="dev-element d-none">Departing From Station Id:</label>
				<input type="hidden" id="modal_product_depart_from_station_id" name="modal_product_depart_from_station_id" class="form-control dev-element" value="" readonly="readonly">
			</div>
			<!-- /Departing From Station Id -->
			
			<!-- Arriving To Station Id -->
			<div class="col-12 col-md-6">
				<label for="modal_product_arrive_to_station_id" class="dev-element d-none">Arriving To Station Id:</label>
				<input type="hidden" id="modal_product_arrive_to_station_id" name="modal_product_arrive_to_station_id" class="form-control dev-element" value="" readonly="readonly">
			</div>
			<!-- /Arriving To Station Id -->
		
		</div>
		<!-- /Arriving Station Hidden Fields -->
	
	</fieldset>
	<!-- /Arriving Station -->
	
	<!-- Day Span -->
	<div class="row">
		
		<!-- Day Span -->
		<div class="col-12 col-md-6">
			<div class="form-element">
				<label id="modal_product_day_span_station-label" for="modal_product_day_span_station">Day Span</label>
				<input type="number" id="modal_product_day_span_station" name="modal_product_day_span_station" class="form-control" minlength="1" value="1" placeholder=""/>
				<div id="modal_product_day_span_station-error" class="error w-100 text-center"></div>
			</div>
		</div>
		<!-- /Day Span -->
	
	</div>
	<!-- /Day Span -->

</fieldset>
