<!-- Edit Address Form -->
<form id="form_edit_address" name="form_edit_address" class="" style="" novalidate>

    <!-- Panel -->
    <section class="panel z-depth-0 w-100 mb-0" style="">

        <!-- Panel Heading -->
        <header class="panel-heading" style="">
            <div class="row">

                <!-- Panel Heading Title -->
                <div class="col-8">
                    <h4 class="panel-title">Address Details</h4>
                </div>
                <!-- /Panel Heading Title -->

                <!-- Panel Heading Actions -->
                <div class="col-4 d-flex align-items-center justify-content-end" style="">
                    <div class="panel-actions p-0 m-0" style="">

                        <!-- Address Enabled -->
                        <div class="custom-control custom-switch" style="">
                            <input id="address_enabled" name="address_enabled" type="checkbox" value="1" class="custom-control-input" style="">
                            <label for="address_enabled" class="custom-control-label" style="">Enabled</label>
                        </div>
                        <!-- /Address Enabled -->

                    </div>
                </div>
                <!-- /Panel Heading Actions -->

            </div>
        </header>
        <!-- /Panel Heading -->

        <!-- Panel Body -->
        <div class="panel-body px-0 w-100" style="">
            <div class="row" style="">

                <div class="col-12 col-lg-6 mb-1" style="">
                    <div class="container-fluid">
                        <div class="row" style="">

                            <!-- Address Id -->
                            <div class="col-12 col-lg-6 mb-1" style="">
                                <div class="form-element" style="">
                                    <label for="address_id" style="">Address Id:</label>
                                    <input type="text" id="address_id" name="address_id" class="form-control" style="" aria-label="Address Id" placeholder="" autocomplete="off" readonly/>
                                    <div id="address_id-error" class="error w-100 text-center" style="">&nbsp;</div>
                                </div>
                            </div>
                            <!-- /Address Id -->

                            <!-- Address Enabled -->
                            <div class="col-12 col-lg-6 mb-1" style="">
                                <div class="form-element">

                                    <div class="error w-100 text-center" style="">&nbsp;</div>
                                </div>
                            </div>
                            <!-- /Address Enabled -->

                        </div>

                        <div class="row" style="">

                            <!-- Address Street 1 -->
                            <div class="col-12 col-lg-12 mb-1" style="">
                                <div class="form-element" style="">
                                    <label for="address_street_1" style="">Street 1:</label>
                                    <input type="text" id="address_street_1" name="address_street_1" class="form-control" style="" aria-label="Address Id" placeholder="" autocomplete="off" readonly/>
                                    <div id="address_street_1-error" class="error w-100 text-center" style="">&nbsp;</div>
                                </div>
                            </div>
                            <!-- /Address Street 1 -->

                        </div>

                        <div class="row" style="">

                            <!-- Address Street 2 -->
                            <div class="col-12 col-lg-12 mb-1" style="">
                                <div class="form-element" style="">
                                    <label for="address_street_2" style="">Street 2:</label>
                                    <input type="text" id="address_street_2" name="address_street_2" class="form-control" style="" aria-label="Address Id" placeholder="" autocomplete="off" readonly/>
                                    <div id="address_street_2-error" class="error w-100 text-center" style="">&nbsp;</div>
                                </div>
                            </div>
                            <!-- /Address Street 2 -->

                        </div>

                        <div class="row" style="">

                            <!-- Address Street 3 -->
                            <div class="col-12 col-lg-12 mb-1" style="">
                                <div class="form-element" style="">
                                    <label for="address_street_3" style="">Street 3:</label>
                                    <input type="text" id="address_street_3" name="address_street_3" class="form-control" style="" aria-label="Address Id" placeholder="" autocomplete="off" readonly/>
                                    <div id="address_street_3-error" class="error w-100 text-center" style="">&nbsp;</div>
                                </div>
                            </div>
                            <!-- /Address Street 3 -->

                        </div>

                        <div class="row" style="">

                        </div>

                        <div class="row" style="">
                            <!-- Address Postal Code -->
                            <div class="col-12 col-lg-12 mb-1" style="">
                                <div class="form-element" style="">
                                    <label for="address_postal_code" style="">Postal Code:</label>
                                    <input type="text" id="address_postal_code" name="address_postal_code" class="form-control" style="" aria-label="Address Id" placeholder="" autocomplete="off" readonly/>
                                    <div id="address_postal_code-error" class="error w-100 text-center" style="">&nbsp;</div>
                                </div>
                            </div>
                            <!-- /Address Postal Code -->
                        </div>

                    </div>
                </div>

                <div class="col-12 col-lg-6 mb-1" style="">
                    <?php include_once(VIEWS_PATH . "/addresses/tables/provider_edit_address_table.phtml"); ?>
                </div>

            </div>

        </div>
        <!-- /Panel Body -->

        <!-- Panel Footer -->
        <div class="panel-footer pb-0 text-right">
            <button type="button" id="button_submit_form_edit_provider" class="btn btn-primary btn-sm" style="">Save Provider Details</button>
        </div>
        <!-- /Panel Footer -->

    </section>
    <!-- /Panel -->

</form>
<!-- /Edit Provider Form -->
