<?php
    
    use Framework\App\Middlewares\Auth;
    
    $page_data = [];
    if (isset($data)) {
        $page_data = $data;
    }
    if (!Auth::logged_in()) {
        ?>
        
        <!DOCTYPE html>
        <html lang="en">
        <?php
            include_once(VIEWS_PATH . "/_includes/head.phtml"); ?>
        <body>
        <style>
          
          html,
          body,
          header,
          .view {
            height: 100%;
            }
          
          @media (max-width: 740px) {
            html,
            body,
            header,
            .view {
              height: 100vh;
              }
            }
        
        </style>
        
        <header>
            <div class="view">
                <div class="mask rgba-blue-slight d-flex justify-content-center align-items-center">
                    <div class="container">
                        <div class="row wow fadeIn">
                            <div class="col-md-12 text-center">
                                <h1 class="display-3 font-weight-bold mb-0 pt-md-5 pt-5 wow fadeInUp">404</h1>
                                
                                <h5>Page Not Found !</h5>
                                
                                <div class="wow fadeInUp" data-wow-delay="0.4s">
                                    <a href="/" class="btn btn-primary btn-round"><i class="fas fa-home left"></i> Home!</a>
                                    <a class="btn btn-outline-purple btn-rounded"><i class="fas fa-book left"></i> Contact Us</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        
        </header>
        <!--
        <h1 class="animation-slide-top">404</h1>
        <p>Page Not Found !</p>
        <p class="error-advise">YOU SEEM TO BE TRYING TO FIND HIS WAY HOME</p>
        <a class="btn btn-primary btn-round" href="../index.html">GO TO HOME PAGE</a>
        <footer class="page-copyright">
            <p>WEBSITE BY Creation Studio</p>
            <p>© 2018. All RIGHT RESERVED.</p>
            <div class="social">
                <a class="btn btn-icon btn-pure" href="javascript:void(0)">
                    <i class="icon bd-twitter" aria-hidden="true"></i>
                </a>
                <a class="btn btn-icon btn-pure" href="javascript:void(0)">
                    <i class="icon bd-facebook" aria-hidden="true"></i>
                </a>
                <a class="btn btn-icon btn-pure" href="javascript:void(0)">
                    <i class="icon bd-dribbble" aria-hidden="true"></i>
                </a>
            </div>
        </footer>
        -->
        <?php
            include_once(VIEWS_PATH . "/_includes/body/scripts.phtml"); ?>
        
        <script type="text/javascript">
            $(function () {
                Logger.init()
            })
        </script>
        </body>
        </html>
        <?php
    } else {
        ?>
        <div class="row wow fadeIn">
            <div class="col-md-12 text-center">
                <h1 class="display-3 font-weight-bold mb-0 pt-md-5 pt-5 wow fadeInUp">404</h1>
                
                <h5>Page Not Found !</h5>
                
                <div class="wow fadeInUp" data-wow-delay="0.4s">
                    <a href="/" class="btn btn-primary btn-round"><i class="fas fa-home left"></i> Home!</a>
                    <a class="btn btn-outline-purple btn-rounded"><i class="fas fa-book left"></i> Contact Us</a>
                </div>
            </div>
        </div>
        <?php
    }
?>
