<!-- Edit Vendor Form -->
<form id="form_edit_vendor" name="form_edit_vendor" class="" style="" novalidate>
    
    <!-- Panel -->
    <section class="panel z-depth-0 w-100 mb-0" style="">
        
        <!-- Panel Heading -->
        <header class="panel-heading" style="">
            <div class="row">
                <div class="col-8">
                    <h4 class="panel-title">Vendor Details</h4>
                </div>
                
                <div class="col-4 d-flex align-items-center justify-content-end">
                    <div class="panel-actions p-0 m-0">
                        <div class="custom-control custom-switch">
                            <input type="checkbox" value="1" class="custom-control-input" id="provider_enabled">
                            <label class="custom-control-label" for="provider_enabled">Enabled</label>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- /Panel Heading -->
        
        <!-- Panel Body -->
        <div class="panel-body px-0 w-100" style="">
            <div class="row">

                <!-- Vendor SKU -->
                <div class="col-12 col-md-4 col-lg-3" style="">
                    <div class="form-element">
                        <label for="vendor_sku">Vendor SKU:</label>
                        <input type="text" id="vendor_sku" name="vendor_sku" class="form-control" style="" aria-label="Vendor SKU" placeholder="" autocomplete="off"/>
                        <div id="vendor_sku-error" class="error w-100 text-center">&nbsp;</div>
                    </div>
                </div>
                <!-- /Vendor SKU -->
            </div>
        </div>
        <!-- /Panel Body -->
        
        <!-- Panel Footer -->
        <div class="panel-footer pb-0 text-right">
            <button class="btn btn-primary btn-sm" type="button" id="button_submit_form_edit_vendor">Save Vendor Details</button>
        </div>
        <!-- /Panel Footer -->
    
    </section>
    <!-- /Panel -->

</form>
<!-- /Edit Vendor Form -->
