<?php
    $company_phone_1 = (isset($page_data["company_detail"]["phone_1"])) ? $page_data["company_detail"]["phone_1"] : "phone1";
    $company_phone_2 = (isset($page_data["company_detail"]["phone_2"])) ? $page_data["company_detail"]["phone_2"] : "phone2";
    $company_fax = (isset($page_data["company_detail"]["fax"])) ? $page_data["company_detail"]["fax"] : "fax";
    $company_website = (isset($page_data["company_detail"]["website"])) ? $page_data["company_detail"]["website"] : "website";
    $company_email = (isset($page_data["company_detail"]["email"])) ? $page_data["company_detail"]["email"] : "Title";
    $company_name = (isset($page_data["company_detail"]["name"])) ? $page_data["company_detail"]["name"] : "Title";
    $company_status_id = (isset($page_data["company_detail"]["status_id"])) ? $page_data["company_detail"]["status_id"] : "fax";
    $company_cover_image = (isset($page_data["company_detail"]["cover_image"])) ? $page_data["company_detail"]["cover_image"] : "fax";
    $company_note = (isset($page_data["company_detail"]["note"])) ? $page_data["company_detail"]["note"] : "fax";
    $company_keywords = (isset($page_data["company_detail"]["keywords"])) ? $page_data["company_detail"]["keywords"] : "";
    $company_description_short = (isset($page_data["company_detail"]["description_short"])) ? $page_data["company_detail"]["description_short"] : "fax";
    $company_description_long = (isset($page_data["company_detail"]["description_long"])) ? $page_data["company_detail"]["description_long"] : "fax";
    $bodytag = str_replace(", ", ",", $company_keywords);
    $keywords = $pieces = explode(",", $bodytag);
    $keywords_list = "";
    foreach ($keywords AS $keyword) {
        
        $keywords_list .= "
            <span class='badge badge-primary ml-2'>$keyword</span>
        ";
    }
?>

<div class="page-project">
    <div class="row gx-1 ">
        
        <div class="col-lg-8 col-xl-9">
            <section class="section mb-2 wow fadeIn">
                
                <div class="card">
                    <!-- Card image -->
                    <div class="view view-cascade overlay">
                        
                        <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Slides/img%20(134).jpg" alt="Card image cap">
                        <div class="mask rgba-white-slight"></div>
                    
                    </div>
                    <!--
                    <div class="card-body card-body-cascade text-center">
                        <h2><a><strong>This is title of the news</strong></a></h2>
                        <p>Written by <a>Abby Madison</a>, 26/08/2016</p>
                    </div>
                    -->
                </div>
                
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            <span id="vender_overview_name">
                                <?php echo $company_name; ?>
                            </span>
                        </h5>
                        <h6 class="card-subtitle mb-2 text-muted">
                            
                            <span id="vender_overview_short_desc">
                            <?php echo $company_description_short; ?>
                            </span>
                        </h6>
                        
                        <hr class="ml-3 mr-3 mt-1 mb-3 color-dark">
                        
                        <div>
                            <?php echo $company_description_long; ?>
                            <h4 id="section-1">Article section one.</h4>
                            <p class="card-text">
                                At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum
                                deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate
                                non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum
                                et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.
                            </p>
                            
                            <p>
                                Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod
                                maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus
                                autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates
                                repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus,
                                ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus.</p>
                            
                            <blockquote class="blockquote mt-4 mb-4">
                                <p class="mb-0"><em>Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe
                                                    eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic
                                                    tenetur a sapiente delectus.</em></p>
                                <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
                            </blockquote>
                            
                            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,
                               totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae
                               vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit
                               aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem.
                            </p>
                            
                            <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit,
                               sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat
                               voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit
                               laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit
                               qui in ea voluptate velit esse quam nihil molestiae consequatur.</p>
                            
                            <div class="mt-4 d-flex justify-content-end">
                                <?php echo $keywords_list; ?>
                            </div>
                        
                        </div>
                        
                        <a class="card-link">Card link</a>
                        <a class="card-link">Another link</a>
                    </div>
                </div>
            </section>
        </div>
        
        <div class="col-lg-4 col-xl-3">
            
            <div class="card ">
                <div class="card-block">
                    <p class="mb-10">
                        <span class="float-right pl-10">4h 30m</span>
                        Time estimated
                    </p>
                    <p>
                        <span class="float-right pl-10">2h 10m</span>
                        Time working
                    </p>
                    
                    <div class="progress progress-xs mb-10">
                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" style="width: 60%;">
                        </div>
                    </div>
                </div>
                
                <div class="card-block">
                    <h4 class="project-option-title">Label</h4>
                    <pre>
                        <?php
                            //vendor_detail
                            echo var_export($page_data["company_detail"], 1); ?>
                    </pre>
                </div>
            
            </div>
        </div>
    
    </div>
</div>
