<section id="product_edit_vendor_section" class="section">
	
	<div class="row">
		
		<div class="col-12 col-md-8 mb-2">
		
		</div>
		
		<div class="col-12 col-md-4 mb-2">
			
			<ul class="list-group">
				<li class="list-group-item d-flex justify-content-between align-items-center">
					<span id="" class="">Cras justo odio</span>
					<span class="badge badge-primary badge-pill">14</span>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					Dapibus ac facilisis in
					<span class="badge badge-primary badge-pill">2</span>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					dfg
					<span class="badge badge-primary badge-pill">1</span>
				</li>
			</ul>
		
		</div>
	
	</div>

</section>
