<?php

    $contact_types = [];
    if (isset($data["types"]["contact_types"])) {
        $contact_types = $data["types"]["contact_types"];
    }

?>
<!-- Contact Table -->
<section class="panel z-depth-0 mb-0 w-100">
    <header class="panel-heading">
        <div class="row">

            <div class="col-8">
                <h4 class="panel-title">Contact List</h4>
            </div>
            <!-- /Panel Heading Title -->
            
            <!-- Panel Heading Actions -->
            <div class="col-4 d-flex align-items-center justify-content-end" style="">
                <div class="panel-actions p-0 m-0">
                    
                    <!--Toggle Filters -->
                    <a href="#contact_table_filters" class="panel-action fas fa-filter" data-toggle="collapse" aria-expanded="false" aria-controls="provider_index_table_filters"></a>
                    <!-- /Toggle Filters -->
                    
                    <!--Add Contact -->
                    <a id="button_add_contact_table" href="javascript:void(0);" class="panel-action fas fa-plus" data-toggle="panel-button" aria-hidden="true"></a>
                    <!--/Add Contact -->
                
                </div>
            
            </div>
            <!-- /Panel Heading Actions -->
        
        </div>
    </header>
    <!-- /Panel Heading -->
    
    <!-- Panel Body -->
    <div class="panel-body">
        
        <div id="contact_table_filters" class="collapse" style="">
            <div class="card rgba-blue-grey-slight m-2" style="">
                <div class="row" style="">

                    <!-- Contact Types -->
                    <div class="col-12 col-lg-4 mb-1" style="">
                        <div class="form-element" style="">
                            <label for="filter_contact_types">Contact Types:</label>
                            <select id="filter_contact_types" name="filter_contact_types" class="custom-select" style="" multiple>
                                <?php
                                    echo "<option value=''>All</option>";
                                    foreach ($contact_types AS $k => $d) {
                                        $val = $d["id"];
                                        $text = $d["name"];

                                        echo "<option value='$val'>$text</option>";
                                    }
                                ?>
                            </select>
                            <div id="filter_contact_types-error" class="error w-100 text-center" style="">&nbsp;</div>
                        </div>
                    </div>
                    <!-- /Contact Types -->
                
                </div>
            </div>
        </div>
        
        <table id="table_contact" class="table w-100 table-striped" style=""></table>
    
    </div>
    <!-- /Panel Body -->

</section>
<!-- /Contact Table -->
