<?php
	if (!isset($page_data)) {
		$page_data = [];
	}
	
	$airport_types = [];
	if (isset($page_data) && isset($page_data["types"]) && isset($page_data["types"]["airport_types"])) {
		$airport_types = $page_data["types"]["airport_types"];
	}
?>
<!-- Flights -->
<fieldset id="modal_product_flight_fields" data-categoryid="2" class="fieldset-dark">
	<!-- Title -->
	<legend class="">
		<h6>Airport Fields</h6>
	</legend>
	<!-- /Title -->
	
	<!-- Depart From Fields -->
	<fieldset id="modal_product_depart_from_fields" class="fieldset-light">
		<!-- Title -->
		<legend class="">
			<h6>Departing From</h6>
		</legend>
		<!-- /Title -->
		
		<!-- Departing Airport Search -->
		<div class="row">
			
			<!-- Departing Airport Search -->
			<div class="col-10">
				<div class="form-element">
					<label for="modal_product_depart_from_airport" class="d-none">Name:</label>
					<div class="input-group">
						<div class="input-group-prepend">
	                    <span class="input-group-text">
	                        <i class="fas fa-search" aria-hidden="true"></i>
	                    </span>
						</div>
						<input type="search" id="modal_product_depart_from_airport" name="modal_product_depart_from_airport" class="form-control" placeholder="Departing From Airport"/>
					</div>
					<div id="modal_product_depart_from_airport-error" class="error w-100 text-center"></div>
				</div>
			</div>
			<!-- /Departing Airport Search -->
			
			<!-- Departing Airport Search Edit -->
			<div class="col-2 mt-2">
				<a href="javascript:void(0);" id="modal_product_depart_from_airport_edit_link" data-station-id="1" data-toggle="hidden" class="">Edit</a>
			</div>
			<!-- /Departing Airport Search Edit -->
		
		</div>
		<!-- /Departing Airport Search -->
		
		<!-- Departing Airport Form -->
		<div id="modal_product_depart_from_airport_add_block" class="card card-body grey lighten-4 mb-2">
			<!-- Title -->
			<h5 class="card-title">
				<span>Airport Form</span>
				<a href="javascript:void(0);" id="modal_product_depart_from_airport_add_block_close_button" class="panel-button-close fas fa-times" aria-hidden="true"></a>
			</h5>
			<!-- /Title -->
			
			<!-- Departing Airport Detail -->
			<fieldset class="px-2 border border-1 rounded my-2 border-light">
				<legend class="card-subtitle mb-2 text-muted">Detail</legend>
				
				<!-- Departing Airport Id, Departing Airport IATA Code, Departing Airport Type -->
				<div class="row">
					
					<!-- Departing Airport Id -->
					<div class="col-12 col-md-4">
						<div class="form-element">
							<label for="modal_product_depart_from_new_airport_id">Id:</label>
							<input type="text" id="modal_product_depart_from_new_airport_id" name="modal_product_depart_from_new_airport_id" class="form-control" readonly="readonly"/>
							<div id="modal_product_depart_from_new_airport_id-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Departing Airport Id -->
					
					<!-- Departing Airport IATA Code -->
					<div class="col-12 col-md-4">
						<div class="form-element">
							<label for="modal_product_depart_from_airport_iata_code">IATA Code:</label>
							<input type="text" id="modal_product_depart_from_airport_iata_code" name="modal_product_depart_from_airport_iata_code" class="form-control" maxlength="3"/>
							<div id="modal_product_depart_from_airport_iata_code-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Departing Airport IATA Code -->
					
					<!-- Departing Airport Type -->
					<div class="col-12 col-md-4">
						<div class="form-element">
							<label for="modal_product_depart_from_airport_types_id">Airport Type:</label>
							<select id="modal_product_depart_from_airport_types_id" name="modal_product_depart_from_airport_types_id" class="form-control">
								<?php
									$options = "<option  value='' disabled selected>-- Airport Type --</option>";
									foreach ($airport_types AS $k => $value) {
										$name = $value["name"];
										$val = $value["id"];
										$options .= "<option value='$val'>$name</option>";
									}
									echo $options;
								?>
							</select>
							<div id="modal_product_depart_from_airport_types_id-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Departing Airport Type -->
				
				</div>
				<!-- /Departing Airport Id, Departing Airport IATA Code, Departing Airport Type -->
			
			</fieldset>
			
			<!-- Address Fields -->
			<fieldset class="px-2 border border-1 rounded my-2 border-light">
				<legend class="card-subtitle mb-2 text-muted">Address</legend>
				
				<div class="row">
					
					<!-- Departing Airport Street 1 -->
					<div class="col-12">
						<div class="form-element">
							<label for="modal_product_depart_from_airport_street_1">Street 1:</label>
							<input type="text" id="modal_product_depart_from_airport_street_1" name="modal_product_depart_from_airport_street_1" class="form-control"/>
							<div id="modal_product_depart_from_airport_street_1-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Departing Airport Street 1 -->
				
				</div>
				
				<div class="row">
					
					<!-- Departing Airport Street 2 -->
					<div class="col-12">
						<div class="form-element">
							<label for="modal_product_depart_from_airport_street_2">Street 2:</label>
							<input type="text" id="modal_product_depart_from_airport_street_2" name="modal_product_depart_from_airport_street_2" class="form-control"/>
							<div id="modal_product_depart_from_airport_street_2-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Departing Airport Street 2 -->
				
				</div>
				
				<div class="row">
					
					<!-- Departing Airport City/Province/Country -->
					<div class="col-12 col-md-9">
						<div class="form-element">
							<label for="modal_product_depart_from_airport_city">City/Province/Country:</label>
							<input type="search" id="modal_product_depart_from_airport_city" name="modal_product_depart_from_airport_city" class="form-control"/>
							<div id="modal_product_depart_from_airport_city-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Departing Airport City/Province/Country -->
					
					<!-- Departing Airport Postal Code -->
					<div class="col-12 col-md-3">
						<div class="form-element">
							<label for="modal_product_depart_from_airport_postal_code">Postal Code:</label>
							<input type="text" id="modal_product_depart_from_airport_postal_code" name="modal_product_depart_from_airport_postal_code" class="form-control"/>
							<div id="modal_product_depart_from_airport_postal_code-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Departing Airport Postal Code -->
				
				</div>
				
				<div class="row">
					
					<!-- Depart From GPS Coords -->
					<div class="col-12 col-md-6">
						<div class="form-element">
							<label for="modal_product_depart_from_airport_gps_code">GPS Coords:</label>
							<input type="text" id="modal_product_depart_from_airport_gps_code" name="modal_product_depart_from_airport_gps_code" class="form-control"/>
							<div id="modal_product_depart_from_airport_gps_code-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Depart From GPS Coords -->
				
				</div>
			
			</fieldset>
			<!-- /Address Fields -->
			
			<!-- Airport Links -->
			<fieldset class="px-2 border border-1 rounded my-2 border-light">
				<legend class="card-subtitle mb-2 text-muted">Links</legend>
				
				<div class="row">
					
					<!-- Depart From Home Link -->
					<div class="col-12">
						<div class="form-element">
							<label for="modal_product_depart_from_airport_home_link">Home Link:</label>
							<input type="url" id="modal_product_depart_from_airport_home_link" name="modal_product_depart_from_airport_home_link" class="form-control"/>
							<div id="modal_product_depart_from_airport_home_link-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Depart From Home Link -->
				
				</div>
				
				<div class="row">
					
					<!-- Depart From Wiki Link -->
					<div class="col-12">
						<div class="form-element">
							<label for="modal_product_depart_from_airport_wikipedia_link">Wiki Link:</label>
							<input type="url" id="modal_product_depart_from_airport_wikipedia_link" name="modal_product_depart_from_airport_wikipedia_link" class="form-control"/>
							<div id="modal_product_depart_from_airport_wikipedia_link-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Depart From Wiki Link -->
				
				</div>
			
			</fieldset>
			<!-- /Airport Links -->
			
			<!-- Airport Meta -->
			<fieldset class="px-2 border border-1 rounded my-2 border-light">
				<legend class="card-subtitle mb-2 text-muted">Meta</legend>
				
				<!-- Depart From Keywords -->
				<section id="modal_product_depart_from_keywords_airport" class="card card-body mb-2 keyword">
					<label for="modal_product_depart_from_keywords_airport_search" class="d-none">Keywords:</label>
					<input type="text" id="modal_product_depart_from_keywords_airport_search" class="user-release-input form-control form-control-lg" placeholder="Keywords..."/>
					<div id="modal_product_depart_from_keywords_airport_container" class="w-100 my-2 chips_container"></div>
				</section>
				<!-- /Depart From Keywords -->
			
			</fieldset>
			<!-- /Airport Meta -->
			
			<!-- Depart Hidden Fields -->
			<div class="row">
				
				<div class="col-3">
					<label for="modal_product_depart_from_airport_city_id" class="dev-element d-none">City Id:</label>
					<input type="hidden" id="modal_product_depart_from_airport_city_id" class="form-control dev-element" value="" readonly="readonly"/>
				</div>
				
				<div class="col-3">
					<label for="modal_product_depart_from_airport_province_id" class="dev-element d-none">Province Id:</label>
					<input type="hidden" id="modal_product_depart_from_airport_province_id" class="form-control dev-element" value="" readonly="readonly"/>
				</div>
				
				<div class="col-3">
					<label for="modal_product_depart_from_airport_country_id" class="dev-element d-none">Country Id:</label>
					<input type="hidden" id="modal_product_depart_from_airport_country_id" class="form-control dev-element" value="" readonly="readonly"/>
				</div>
			
			</div>
			<!-- /Depart Hidden Fields -->
			
			<!-- Departing Airport Buttons -->
			<div class="row">
				
				<div class="col-6 text-left">
					<button type="button" id="modal_product_depart_from_airport_cancel_button" class="btn btn-outline-primary btn-sm white waves-effect waves-light">Cancel</button>
				</div>
				
				<div class="col-6 text-right">
					<button type="button" id="modal_product_depart_from_airport_submit_button" class="btn btn-primary btn-sm waves-effect waves-light">Save</button>
				</div>
			
			</div>
			<!-- /Departing Airport Buttons -->
		
		</div>
		<!-- /Departing Airport Form -->
		
		<!-- Departing Airport: Departing Time, Departing Date -->
		<div class="row">
			
			<!-- Departing Date -->
			<div class="col-12 col-md-6">
				<div id="modal_product_depart_from_date" data-label="Departing Date" data-placeholder="Select Departing Date"></div>
			</div>
			<!-- /Departing Date -->
			
			<!-- Departing Time -->
			<div class="col-12 col-md-6">
				<div id="modal_product_depart_from_time" data-label="Departing Time" data-placeholder="Select Departing Time"></div>
			</div>
			<!-- /Departing Time -->
		
		</div>
		<!-- /Departing Airport: Departing Time, Departing Date -->
	
	</fieldset>
	<!-- /Depart From Fields -->
	
	<!-- Arrive To Fields -->
	<fieldset id="modal_product_arrive_to_fields" class="fieldset-light">
		<!-- Title -->
		<legend class="">
			<h6>Arriving To</h6>
		</legend>
		
		<!-- Arriving Airport Search -->
		<div class="row">
			
			<!-- Arriving Airport Search -->
			<div class="col-10">
				<div class="form-element">
					<label id="modal_product_arrive_to_airport-label" for="modal_product_arrive_to_airport" class="d-none">Name:</label>
					<div class="input-group">
						<div class="input-group-prepend">
		                    <span class="input-group-text">
		                        <i class="fas fa-search" aria-hidden="true"></i>
		                    </span>
						</div>
						<input type="search" id="modal_product_arrive_to_airport" name="modal_product_arrive_to_airport" class="form-control" placeholder="Arriving To Airport"/>
					</div>
					<div id="modal_product_arrive_to_airport-error" class="error w-100 text-center"></div>
				</div>
			</div>
			<!-- /Arriving Airport Search -->
			
			<!-- Arriving Airport Search Edit -->
			<div class="col-2 mt-2">
				<a href="javascript:void(0);" id="modal_product_arrive_to_airport_edit_link" data-station-id="1" data-toggle="hidden" class="">Edit</a>
			</div>
			<!-- /Arriving Airport Search Edit -->
		
		</div>
		<!-- /Arriving Airport Search -->
		
		<!-- Arriving Airport Form -->
		<div id="modal_product_arrive_to_airport_add_block" class="card card-body grey lighten-4 mb-2">
			<h5 class="card-title">
				<span>Airport Form</span>
				<a href="javascript:void(0);" id="modal_product_arrive_to_airport_add_block_close_button" class="panel-button-close fas fa-times" aria-hidden="true"></a>
			</h5>
			
			<!-- Arriving Airport Detail -->
			<fieldset class="px-2 border border-1 rounded my-2 border-light">
				<legend class="card-subtitle mb-2 text-muted">Detail</legend>
				
				<!-- Arriving Airport Id, Arriving Airport IATA Code, Arriving Airport Type -->
				<div class="row">
					
					<!-- Arriving Airport ID -->
					<div class="col-12 col-md-4">
						<div class="form-element">
							<label for="modal_product_arrive_to_new_airport_id">Id:</label>
							<input type="text" id="modal_product_arrive_to_new_airport_id" name="modal_product_arrive_to_new_airport_id" class="form-control" readonly="readonly"/>
							<div id="modal_product_arrive_to_new_airport_id-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Arriving Airport Id -->
					
					<!-- Arriving Airport IATA Code -->
					<div class="col-12 col-md-4">
						<div class="form-element">
							<label for="modal_product_arrive_to_airport_iata_code">IATA Code:</label>
							<input type="text" id="modal_product_arrive_to_airport_iata_code" name="modal_product_arrive_to_airport_iata_code" maxlength="3" class="form-control"/>
							<div id="modal_product_arrive_to_airport_iata_code-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- Arriving Airport IATA Code -->
					
					<!-- Arriving Airport Type -->
					<div class="col-12 col-md-4">
						<div class="form-element">
							<label for="modal_product_arrive_to_airport_types_id">Airport Type:</label>
							<select id="modal_product_arrive_to_airport_types_id" name="modal_product_arrive_to_airport_types_id" class="form-control">
								<?php
									$options = "<option  value='' disabled selected>-- Airport Type --</option>";
									foreach ($airport_types AS $k => $value) {
										$name = $value["name"];
										$val = $value["id"];
										$options .= "<option value='$val'>$name</option>";
									}
									echo $options;
								?>
							</select>
							<div id="modal_product_arrive_to_airport_types_id-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Arriving Airport Type -->
				
				</div>
				<!-- /Arriving Airport Id, Arriving Airport IATA Code, Arriving Airport Type -->
			
			</fieldset>
			<!-- /Arriving Airport Detail -->
			
			<!-- Arriving Airport Address -->
			<fieldset class="px-2 border border-1 rounded my-2 border-light">
				<legend class="card-subtitle mb-2 text-muted">Address</legend>
				
				<div class="row">
					
					<!-- Arriving Airport Street 1 -->
					<div class="col-12">
						<div class="form-element">
							<label for="modal_product_arrive_to_airport_street_1">Street 1:</label>
							<input type="text" id="modal_product_arrive_to_airport_street_1" name="modal_product_arrive_to_airport_street_1" class="form-control"/>
							<div id="modal_product_arrive_to_airport_street_1-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Arriving Airport Street 1 -->
				
				</div>
				
				<div class="row">
					
					<!-- Arriving Airport Street 2 -->
					<div class="col-12">
						<div class="form-element">
							<label for="modal_product_arrive_to_airport_street_2">Street 2:</label>
							<input type="text" id="modal_product_arrive_to_airport_street_2" name="modal_product_arrive_to_airport_street_2" class="form-control"/>
							<div id="modal_product_arrive_to_airport_street_2-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Departing Airport Street 2 -->
				
				</div>
				
				<div class="row">
					
					<!-- Arriving Airport City -->
					<div class="col-12 col-md-9">
						<div class="form-element">
							<label for="modal_product_arrive_to_airport_city">City/Province/Country:</label>
							<input type="search" id="modal_product_arrive_to_airport_city" name="modal_product_arrive_to_airport_city" class="form-control"/>
							<div id="modal_product_arrive_to_airport_city-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Arriving Airport City -->
					
					<!-- Arriving Airport Postal Code -->
					<div class="col-12 col-md-9">
						<div class="form-element">
							<label for="modal_product_arrive_to_airport_postal_code">Postal Code:</label>
							<input type="text" id="modal_product_arrive_to_airport_postal_code" name="modal_product_arrive_to_airport_postal_code" class="form-control"/>
							<div id="modal_product_arrive_to_airport_postal_code-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Arriving Airport Postal Code -->
				
				</div>
				
				<div class="row">
					
					<!-- Arriving Airport GPS Coords -->
					<div class="col-12 col-md-6">
						<div id="modal_product_arrive_to_airport_gps_code-wrap" class="form-element">
							<label id="modal_product_arrive_to_airport_gps_code-label" for="modal_product_arrive_to_airport_gps_code">GPS Coords:</label>
							<input type="text" id="modal_product_arrive_to_airport_gps_code" name="modal_product_arrive_to_airport_gps_code" class="form-control"/>
							<div id="modal_product_arrive_to_airport_gps_code-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Arriving Airport GPS Coords -->
				
				</div>
			
			</fieldset>
			<!-- /Arriving Airport Address -->
			
			<!-- Arriving Airport Links -->
			<fieldset class="px-2 border border-1 rounded my-2 border-light">
				<legend class="card-subtitle mb-2 text-muted">Links</legend>
				
				<div class="row">
					
					<!-- Arrive From Home Link -->
					<div class="col-12">
						<div class="form-element">
							<label for="modal_product_arrive_to_airport_home_link">Home Link:</label>
							<input type="url" id="modal_product_arrive_to_airport_home_link" name="modal_product_arrive_to_airport_home_link" class="form-control"/>
							<div id="modal_product_arrive_to_airport_home_link-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Arrive From Home Link -->
				
				</div>
				
				<div class="row">
					
					<!-- Arrive From Wiki Link -->
					<div class="col-12">
						<div class="form-element">
							<label for="modal_product_arrive_to_airport_wikipedia_link">Wiki Link:</label>
							<input type="url" id="modal_product_arrive_to_airport_wikipedia_link" name="modal_product_arrive_to_airport_wikipedia_link" class="form-control"/>
							<div id="modal_product_arrive_to_airport_wikipedia_link-error" class="error w-100 text-center"></div>
						</div>
					</div>
					<!-- /Arrive From Wiki Link -->
				
				</div>
			
			</fieldset>
			<!-- Arriving Airport Links -->
			
			<!-- Arriving Airport Meta -->
			<fieldset class="px-2 border border-1 rounded my-2 border-light">
				<legend class="card-subtitle mb-2 text-muted">Meta</legend>
				
				<!-- Arrive To Keywords -->
				<section id="modal_product_arrive_to_keywords_airport" class="card card-body mb-2 keyword">
					<label for="modal_product_arrive_to_keywords_airport_search" class="d-none">Keywords:</label>
					<input type="text" id="modal_product_arrive_to_keywords_airport_search" class="user-release-input form-control form-control-lg" placeholder="Keywords..."/>
					<div id="modal_product_arrive_to_keywords_airport_container" class="w-100 my-2 chips_container"></div>
				</section>
				<!-- /Arrive To Keywords -->
			
			</fieldset>
			<!-- /Arriving Airport Meta -->
			
			<!-- Arriving Airport Hidden Fields -->
			<div class="row">
				
				<div class="col-3">
					<label for="modal_product_arrive_to_airport_city_id" class="dev-element d-none">City Id:</label>
					<input type="hidden" id="modal_product_arrive_to_airport_city_id" class="form-control dev-element" value="" readonly="readonly"/>
				</div>
				
				<div class="col-3">
					<label for="modal_product_arrive_to_airport_province_id" class="dev-element d-none">Province Id:</label>
					<input type="hidden" id="modal_product_arrive_to_airport_province_id" class="form-control dev-element" value="" readonly="readonly"/>
				</div>
				
				<div class="col-3">
					<label for="modal_product_arrive_to_airport_country_id" class="dev-element d-none">Country Id:</label>
					<input type="hidden" id="modal_product_arrive_to_airport_country_id" class="form-control dev-element" value="" readonly="readonly"/>
				</div>
			
			</div>
			<!-- /Arriving Airport /Hidden Fields -->
			
			<!-- Arriving Airport Buttons -->
			<div class="row">
				
				<!-- Arriving Cancel Button -->
				<div class="col-6 text-left">
					<button type="button" id="modal_product_arrive_to_airport_cancel_button" class="btn btn-outline-primary btn-sm white waves-effect waves-light">Cancel</button>
				</div>
				<!-- /Arriving Cancel Button -->
				
				<!-- Arriving Save Button -->
				<div class="col-6 text-right">
					<button type="button" id="modal_product_arrive_to_airport_submit_button" class="btn btn-primary btn-sm waves-effect waves-light">Save</button>
				</div>
				<!-- /Arriving Save Button -->
			
			</div>
			<!-- /Arriving Airport Buttons -->
		
		</div>
		<!-- /Arriving Airport Form -->
		
		<!-- /Arriving Airport: Departing Time, Departing Date -->
		<div class="row">
			
			<!-- Arriving Airport Date -->
			<div class="col-12 col-md-6">
				<div id="modal_product_arrive_to_date" data-label="Arriving Date" data-placeholder="Select Arriving Date"></div>
			</div>
			<!-- /Arriving Airport Date -->
			
			<!-- Arriving Airport Time -->
			<div class="col-12 col-md-6">
				<div id="modal_product_arrive_to_time" data-label="Arriving Time" data-placeholder="Select Arriving Time"></div>
			</div>
			<!-- /Arriving Airport Time -->
		
		</div>
		<!-- /Arriving Airport: Departing Time, Departing Date -->
	
	</fieldset>
	<!-- /Arrive To Fields -->
	
	<!-- Day Span -->
	<div class="row">
		
		<!-- Day Span -->
		<div class="col-12 col-md-6">
			<div class="form-element">
				<label id="modal_product_day_span_airport-label" for="modal_product_day_span_airport">Day Span</label>
				<input type="number" id="modal_product_day_span_airport" name="modal_product_day_span_airport" class="form-control" minlength="1" value="1" placeholder=""/>
				<div id="modal_product_day_span_airport-error" class="error w-100 text-center"></div>
			</div>
		</div>
		<!-- /Day Span -->
	
	</div>
	<!-- /Day Span -->

</fieldset>
<!-- /Flights -->
