<?php
    $pageHeading = "Page Heading";

    if (defined("PAGEHEADING")) {
        $pageHeading = PAGEHEADING;
    }

    if (defined("PAGEDESCRIPTION")) {
        $pageDescription = PAGEDESCRIPTION;
    }

?>

<div class="page" id="page">

    <div class="page-header" id="page_header">
        <h1 class="page-title" id="page_title">
            <?php
                if (defined("PAGE_HEADING")) {
                    echo PAGE_HEADING;
                } else {
                    echo "Trips2Italy";
                }
            ?>
        </h1>

        <?php
            if (defined("PAGE_SUBHEADING")) {
                echo "<p class='page-description'>" . PAGE_SUBHEADING . "</p>";
            }

        ?>
        
        <ol class="breadcrumb ">
            <?php
                if (defined("BREAD_CRUMBS")) {
                    echo BREAD_CRUMBS;
                }
            ?>
        </ol>
        
        <div class="page-header-actions">
            <?php echo (isset($page_heading_buttons)) ? $page_heading_buttons : "&nbsp;"; ?>
        </div>

    </div>
    <?php include_once(__DIR__ . "/alert_box.phtml"); ?>
    <div class="page-content container-fluid">
        <?php
            if (defined("MAIN")) {
                include_once(MAIN);
            }
        ?>
    </div>

</div>
