<!-- Edit Company Form -->
<form id="form_edit_company" name="form_edit_company" class="" style="" novalidate>
    
    <!-- Panel -->
    <section class="panel z-depth-0 w-100 mb-0" style="">

        <!-- Panel Body -->
        <div class="panel-body px-0 w-100" style="">
            <div class="row">
                
                <!-- Company Name -->
                <div class="col-12 col-lg-6 mb-1" style="">
                    <div class="form-element" style="">
                        <label for="company_name" style="">Company Name:</label>
                        <input type="text" id="company_name" name="company_name" class="form-control" style="" aria-label="Provider Id" placeholder="" autocomplete="off"/>
                        <div id="company_name-error" class="error w-100 text-center" style="">&nbsp;</div>
                    </div>
                </div>
                <!-- /Company Name -->
            </div>
        </div>
        <!-- /Panel Body -->
        
        <!-- Panel Footer -->
        <div class="panel-footer pb-0 text-right">
            <button class="btn btn-primary btn-sm" type="button" id="button_submit_form_edit_company">Save Company Details</button>
        </div>
        <!-- /Panel Footer -->
    
    </section>
    <!-- /Panel -->

</form>
<!-- /Edit Company Form -->
