<?php
	$location_types = [];
	if (isset($data["types"]["location_types"])) {
		$location_types = $data["types"]["location_types"];
	}
?>
<section id="">
	<!-- Edit Location Form -->
	<div class="row">
		<div class="col-12 col-md-6 col-lg-6 col-xl-5">
			<form id="form_edit_location_filter" name="form_edit_location_filter" class="" novalidate>
				<!-- Card -->
				<div class="card mb-2">
					
					<!-- Card Body -->
					<div class="card-body">
						
						<h5 class="card-title"><span>Location Details</span></h5>
						<h6 class="card-subtitle mb-2 text-muted">Panel subtitle</h6>
						<hr class="ml-3 mr-3 mt-1 mb-3 color-dark">
						
						<div class="row">
							<div class="col-12">
								<input type="hidden" id="location_name_filter_id" name="location_name_filter_id" class=""/>
								<label for="location_name">Location:</label>
								<div class="form-element">
									<div class="input-group">
										<input type="search" class="form-control form-field" id="location_name_filter" name="location_name_filter" placeholder="Location" aria-label="Location" aria-describedby="button_provider_edit_location" autocomplete="off">
										<div class="input-group-append">
											<button class="btn btn-md btn-primary m-0 px-3 py-2 z-depth-0 waves-effect" type="button" id="button_edit_location">
												<i class="fas fa-edit"></i>
											</button>
										</div>
									</div>
									<div class="error w-100 text-center" id="location_name_filter-error" data-ref="location_name_filter">&nbsp;</div>
								</div>
								<div class="form-element d-flex align-items-center justify-content-around">
									<!-- Short -->
									<div class="form-check form-check-inline">
										<input type="radio" class="form-check-input" id="location_display_short" name="location_display" value="short">
										<label class="form-check-label" for="location_display_short" style="padding-top: .22rem;">Short</label>
									</div>
									
									<!-- Medium -->
									<div class="form-check form-check-inline">
										<input type="radio" class="form-check-input" id="location_display_medium" name="location_display" value="medium">
										<label class="form-check-label" for="location_display_medium" style="padding-top: .22rem;">Medium</label>
									</div>
									
									<!-- Long -->
									<div class="form-check form-check-inline">
										<input type="radio" class="form-check-input" id="location_display_long" name="location_display" value="long">
										<label class="form-check-label" for="location_display_long" style="padding-top: .22rem;">Long</label>
									</div>
								
								</div>
							</div>
						</div>
					
					</div>
					<!-- /Panel Body -->
				
				</div>
			</form>
		</div>
		
		<div class="col-12 col-md-6 col-lg-6 col-xl-7">
			<form id="form_edit_location" name="form_edit_location" class="" novalidate>
				<div class="card mb-2" id="form_location_details">
					<div class="card-body">
						<h5 class="card-title">
							<span>Panel title</span>
							<a id="button_close_edit_location_form" href="javascript:void(0);" class="panel-button-close fas fa-times" aria-hidden="true"></a>
						</h5>
						<h6 class="card-subtitle mb-2 text-muted">&nbsp;</h6>
						<hr class="ml-3 mr-3 mt-1 mb-3 color-dark">
						
						<div class="">
							<div class="row">
								
								<!-- LOCATION ID -->
								<div class="col-12 col-md-4">
									
									<div class="form-element">
										<label for="location_id">Location Id:</label>
										<input type="text" id="location_id" name="location_id" class="form-control" value="" readonly>
										<div class="error w-100 text-center" id="location_id-error">&nbsp;</div>
									</div>
								
								</div>
								<!-- /LOCATION ID -->
								
								<!-- LOCATION TYPES ID -->
								<div class="col-12 col-md-5">
									
									<div class="form-element">
										<label for="location_types_id">Location Type:</label>
										<select id="location_types_id" name="location_types_id" class="form-control">
											<?php
												echo "<option  value='' disabled selected>-- Location Types --</option>";
												foreach ($location_types AS $k => $v) {
													$val = $v["id"];
													$text = $v["name"];
													echo "<option value='$val'>$text</option>";
												}
											?>
										</select>
										<div class="error w-100 text-center" id="location_types_id-error">&nbsp;</div>
									</div>
								
								</div>
								<!-- /LOCATION TYPES ID -->
								
								<!-- LOCATION ENABLED -->
								<div class="col-12 col-md-3 d-flex align-self-center justify-content-end pb-2">
									<div class="custom-control custom-switch">
										<input id="location_enabled" name="location_enabled" type="checkbox" value="1" class="custom-control-input">
										<label for="location_enabled" class="custom-control-label p-0">Enabled</label>
									</div>
								</div>
								<!-- /LOCATION ENABLED -->
							
							</div>
							
							<div class="row">
								
								<div class="col-lg-12">
									
									<div class="form-element">
										
										<label for="location_name">Location Name:</label>
										<input type="text" id="location_name" name="location_name" class="form-control"/>
										<div class="error w-100 text-center" id="location_name-error">&nbsp;</div>
									
									</div>
								
								</div>
							
							</div>
							
							<div class="row">
								
								<div class="col-lg-12">
									
									<div class="form-element">
										
										<label for="location_street_1">Street 1:</label>
										<input type="text" id="location_street_1" name="location_street_1" class="form-control"/>
										<div class="error w-100 text-center" id="location_street_1-error">&nbsp;</div>
									
									</div>
								
								</div>
							
							</div>
							
							<div class="row">
								
								<div class="col-lg-12">
									
									<div class="form-element">
										
										<label for="location_street_2">Street 2:</label>
										<input type="text" id="location_street_2" name="location_street_2" class="form-control"/>
										<div class="error w-100 text-center" id="location_street_2-error"></div>
									
									</div>
								
								</div>
							
							</div>
							
							<div class="row">
								
								<div class="col-12 col-md-4">
									
									<div class="form-element">
										
										<label for="location_country_id">Country:</label>
										<select class="form-control" name="location_country_id" id="location_country_id" data-type="country" style="width:100%;" required>
										
										</select>
										<div class="error w-100 text-center" id="location_country_id-error"></div>
									
									</div>
								
								</div>
								
								<div class="col-12 col-md-4">
									
									<div class="form-element">
										
										<label for="location_province_id">Province:</label>
										<select class="form-control" name="location_province_id" id="location_province_id" data-type="province" style="width:100%;" required></select>
										<div class="error w-100 text-center" id="location_province_id-error"></div>
									
									</div>
								
								</div>
								
								<div class="col-12 col-md-4">
									
									<div class="form-element">
										
										<label for="location_city_id">City:</label>
										<select class="form-control" name="location_city_id" id="location_city_id" data-type="city" style="width:100%;" required></select>
										<div class="error w-100 text-center" id="location_city_id-error"></div>
									
									</div>
								
								</div>
							
							</div>
							
							<div class="row">
								
								<div class="col-lg-12">
									
									<div class="form-element">
										
										<label for="location_zipcode">Postal Code:</label>
										<input type="text" id="location_zipcode" name="location_zipcode" class="form-control"/>
										<div class="error w-100 text-center" id="location_zipcode-error"></div>
									
									</div>
								
								</div>
							
							</div>
						
						</div>
						
						<div class="text-right w-100">
							<a href="javascript:void(0);" id="button_clear_form_edit_location" class="btn btn-flat primary-text text-center p-1 mx-0 mb-0 waves-effect waves-light">clear</a>
							<a href="javascript:void(0);" id="button_submit_form_edit_location" class="btn btn-primary btn-sm waves-effect waves-light">Save</a>
						</div>
					
					</div>
				</div>
			</form>
		</div>
	</div>
</section>
<!-- /Edit Location Form -->
