<?php
    if (!isset($page_data)) {
        $page_data = [];
    }
    
    $settings = json_encode($page_data, 1);
    $init = "Vendor.edit($settings);";
    if (!defined("COUNTRIES")) {
        define("COUNTRIES", $page_data["types"]["countries"]);
    }
    
    $coverImage = $page_data["company_detail"]["cover_image"];
    $companyName = $page_data["company_detail"]["name"];
    $description_short = $page_data["company_detail"]["description_short"];
?>
<section id="vendor_edit">
    <div class="row">
        <div class="col">
            <!-- Tab Content -->
            <div class="tab-content p-0">
                <!-- Vendor Overview -->
                <div class="tab-pane" id="panel_tab_vendor_overview" role="tabpanel">
                    <?php
                        include_once(VIEWS_PATH . "/vendors/forms/overview.phtml"); ?>
                </div>
                <!-- /Vendor Overview -->
                
                <!-- Company Detail -->
                <div class="tab-pane active" id="panel_tab_company_detail" role="tabpanel">
                    <?php
                        include_once(VIEWS_PATH . "/companies/forms/edit_company_form.phtml"); ?>
                </div>
                <!-- /Company Detail -->
                
                <!-- Vendor Detail -->
                <div class="tab-pane" id="panel_tab_vendor_detail" role="tabpanel">
                    <?php
                        include_once(VIEWS_PATH . "/vendors/forms/edit_vendor_form.phtml"); ?>
                </div>
                <!-- /Vendor Detail -->
                
                <!-- Contact Detail -->
                <div class="tab-pane" id="panel_tab_contact_detail" role="tabpanel">
                    <?php
                        include_once(VIEWS_PATH . "/contacts/forms/contact_edit_form.phtml"); ?>
                </div>
                <!-- /Contact Detail -->
                
                <!-- Address Detail -->
                <div class="tab-pane" id="panel_tab_address_detail" role="tabpanel">
                    <?php
                        include_once(VIEWS_PATH . "/addresses/forms/address_edit_form.phtml"); ?>
                </div>
                <!-- /Address Detail -->
                
                <!-- Meta Detail -->
                <div class="tab-pane" id="panel_tab_meta_detail" role="tabpanel">
                    
                    <?php
                        include_once(VIEWS_PATH . "/companies/forms/company_meta_form.phtml"); ?>
                </div>
                <!-- /Meta Detail -->
            
            </div>
            <!-- /Tab Content -->
        </div>
    </div>
</section>

<script type="text/javascript">
    $(function () {
        Types.init(<?php echo TYPES;?>)
        <?php echo $init;?>
    })
</script>
